\ room-names.fs - the rooms by name (generated by tools/roomnames.py). Placeholders: the
\ area of the pause screen's map a room is on and its place in that page's list. Rename them
\ for what they are as they are walked (and keep the comment with the area).
IN: room-names

$0    constant front-garden-1           \ Belli Castle: Front Garden
$1    constant castle-1f-1              \ Belli Castle: 1F
$2    constant castle-1f-2              \ Belli Castle: 1F
$3    constant castle-1f-11             \ Belli Castle: 1F
$4    constant castle-1f-12             \ Belli Castle: 1F
$5    constant castle-2f-9              \ Belli Castle: 2F
$6    constant castle-3f-1              \ Belli Castle: 3F
$7    constant castle-b1-4              \ Belli Castle: B1
$8    constant castle-1f-13             \ Belli Castle: 1F
$9    constant castle-1f-3              \ Belli Castle: 1F
$A    constant castle-2f-1              \ Belli Castle: 2F
$B    constant castle-b1-5              \ Belli Castle: B1
$C    constant castle-b1-6              \ Belli Castle: B1
$E    constant castle-1f-14             \ Belli Castle: 1F
$F    constant castle-1f-4              \ Belli Castle: 1F
$10   constant castle-1f-5              \ Belli Castle: 1F
$11   constant castle-1f-6              \ Belli Castle: 1F
$12   constant castle-b1-1              \ Belli Castle: B1
$13   constant front-garden-2           \ Belli Castle: Front Garden
$14   constant castle-b1-2              \ Belli Castle: B1
$15   constant castle-1f-7              \ Belli Castle: 1F
$16   constant castle-b1-3              \ Belli Castle: B1
$17   constant castle-2f-10             \ Belli Castle: 2F
$18   constant castle-1f-8              \ Belli Castle: 1F
$19   constant castle-1f-15             \ Belli Castle: 1F
$1A   constant castle-1f-16             \ Belli Castle: 1F
$1B   constant castle-1f-17             \ Belli Castle: 1F
$1C   constant castle-1f-18             \ Belli Castle: 1F
$1D   constant castle-b1-7              \ Belli Castle: B1
$1E   constant castle-1f-19             \ Belli Castle: 1F
$1F   constant castle-2f-11             \ Belli Castle: 2F
$20   constant castle-2f-2              \ Belli Castle: 2F
$21   constant castle-2f-3              \ Belli Castle: 2F
$22   constant castle-2f-6              \ Belli Castle: 2F
$23   constant castle-2f-7              \ Belli Castle: 2F
$24   constant castle-2f-8              \ Belli Castle: 2F
$25   constant castle-1f-9              \ Belli Castle: 1F
$26   constant castle-2f-12             \ Belli Castle: 2F
$28   constant castle-2f-13             \ Belli Castle: 2F
$29   constant castle-1f-10             \ Belli Castle: 1F
$2A   constant front-garden-3           \ Belli Castle: Front Garden
$2B   constant front-garden-4           \ Belli Castle: Front Garden
$2C   constant castle-3f-2              \ Belli Castle: 3F
$2D   constant front-garden-5           \ Belli Castle: Front Garden
$2E   constant old-mansion-1f-1         \ Belli Castle: Old Mansion 1F
$2F   constant castle-2f-14             \ Belli Castle: 2F
$30   constant castle-2f-15             \ Belli Castle: 2F
$31   constant castle-2f-4              \ Belli Castle: 2F
$32   constant castle-2f-5              \ Belli Castle: 2F
$40   constant old-mansion-1f-2         \ Belli Castle: Old Mansion 1F
$41   constant old-mansion-1f-3         \ Belli Castle: Old Mansion 1F
$42   constant old-mansion-1f-4         \ Belli Castle: Old Mansion 1F
$43   constant old-mansion-1f-5         \ Belli Castle: Old Mansion 1F
$44   constant old-mansion-b1-1         \ Belli Castle: Old Mansion B1
$45   constant old-mansion-2f-1         \ Belli Castle: Old Mansion 2F
$46   constant old-mansion-1f-6         \ Belli Castle: Old Mansion 1F
$47   constant old-mansion-1f-7         \ Belli Castle: Old Mansion 1F
$48   constant old-mansion-1f-8         \ Belli Castle: Old Mansion 1F
$49   constant old-mansion-1f-9         \ Belli Castle: Old Mansion 1F
$4A   constant old-mansion-2f-2         \ Belli Castle: Old Mansion 2F
$4B   constant old-mansion-b1-2         \ Belli Castle: Old Mansion B1
$4C   constant old-mansion-b1-3         \ Belli Castle: Old Mansion B1
$4D   constant old-mansion-1f-10        \ Belli Castle: Old Mansion 1F
$4E   constant old-mansion-1f-11        \ Belli Castle: Old Mansion 1F
$4F   constant old-mansion-1f-12        \ Belli Castle: Old Mansion 1F
$50   constant old-mansion-b1-4         \ Belli Castle: Old Mansion B1
$51   constant old-mansion-b1-5         \ Belli Castle: Old Mansion B1
$52   constant old-mansion-1f-13        \ Belli Castle: Old Mansion 1F
$53   constant old-mansion-1f-14        \ Belli Castle: Old Mansion 1F
$54   constant old-mansion-1f-15        \ Belli Castle: Old Mansion 1F
$55   constant old-mansion-1f-16        \ Belli Castle: Old Mansion 1F
$56   constant old-mansion-2f-3         \ Belli Castle: Old Mansion 2F
$57   constant old-mansion-2f-4         \ Belli Castle: Old Mansion 2F
$58   constant old-mansion-2f-5         \ Belli Castle: Old Mansion 2F
$59   constant old-mansion-2f-6         \ Belli Castle: Old Mansion 2F
$5B   constant old-mansion-2f-7         \ Belli Castle: Old Mansion 2F
$5C   constant old-mansion-2f-8         \ Belli Castle: Old Mansion 2F
$5D   constant old-mansion-1f-17        \ Belli Castle: Old Mansion 1F
$5E   constant old-mansion-2f-9         \ Belli Castle: Old Mansion 2F
$5F   constant old-mansion-2f-10        \ Belli Castle: Old Mansion 2F
$60   constant old-mansion-3f-1         \ Belli Castle: Old Mansion 3F
$61   constant old-mansion-b1-7         \ Belli Castle: Old Mansion B1
$62   constant old-mansion-2f-11        \ Belli Castle: Old Mansion 2F
$63   constant old-mansion-3f-2         \ Belli Castle: Old Mansion 3F
$66   constant old-mansion-b1-6         \ Belli Castle: Old Mansion B1
$67   constant chaos-forest-1           \ Chaos Forest
$68   constant old-mansion-1f-18        \ Belli Castle: Old Mansion 1F
$69   constant old-mansion-2f-12        \ Belli Castle: Old Mansion 2F
$6A   constant old-mansion-2f-13        \ Belli Castle: Old Mansion 2F
$6B   constant old-mansion-1f-19        \ Belli Castle: Old Mansion 1F
$6C   constant old-mansion-1f-20        \ Belli Castle: Old Mansion 1F
$6D   constant old-mansion-1f-21        \ Belli Castle: Old Mansion 1F
$6E   constant old-mansion-1f-22        \ Belli Castle: Old Mansion 1F
$6F   constant old-mansion-1f-23        \ Belli Castle: Old Mansion 1F
$70   constant old-mansion-1f-24        \ Belli Castle: Old Mansion 1F
$80   constant lake-pathway-2           \ Lake Pathway
$81   constant house-of-truth-1f-1      \ House of Truth: 1F
$82   constant house-of-truth-2f-1      \ House of Truth: 2F
$83   constant house-of-truth-2f-2      \ House of Truth: 2F
$84   constant house-of-truth-b1-1      \ House of Truth: B1
$85   constant house-of-truth-b1-2      \ House of Truth: B1
$86   constant house-of-truth-b1-3      \ House of Truth: B1
$87   constant house-of-truth-b1-4      \ House of Truth: B1
$88   constant house-of-truth-1f-2      \ House of Truth: 1F
$8A   constant house-of-truth-1f-3      \ House of Truth: 1F
$8C   constant house-of-truth-1f-4      \ House of Truth: 1F
$8D   constant house-of-truth-1f-5      \ House of Truth: 1F
$8E   constant house-of-truth-1f-6      \ House of Truth: 1F
$8F   constant house-of-truth-1f-7      \ House of Truth: 1F
$91   constant house-of-truth-1f-8      \ House of Truth: 1F
$92   constant house-of-truth-1f-9      \ House of Truth: 1F
$93   constant house-of-truth-b1-5      \ House of Truth: B1
$94   constant house-of-truth-b1-6      \ House of Truth: B1
$95   constant house-of-truth-b1-7      \ House of Truth: B1
$96   constant house-of-truth-b1-8      \ House of Truth: B1
$97   constant house-of-truth-b1-9      \ House of Truth: B1
$98   constant house-of-truth-b1-10     \ House of Truth: B1
$99   constant house-of-truth-b1-11     \ House of Truth: B1
$9A   constant house-of-truth-b1-12     \ House of Truth: B1
$9B   constant house-of-truth-1f-10     \ House of Truth: 1F
$C0   constant water-tower-b1-1         \ Water Tower: B1
$C1   constant water-tower-1f-1         \ Water Tower: 1F
$C2   constant water-tower-2f-1         \ Water Tower: 2F
$C3   constant water-tower-4f-1         \ Water Tower: 4F
$C5   constant water-tower-7f-1         \ Water Tower: 7F
$C6   constant water-tower-7f-2         \ Water Tower: 7F
$C7   constant water-tower-8f-1         \ Water Tower: 8F
$C8   constant lake-pathway-1           \ Lake Pathway
$100  constant chaos-forest-2           \ Chaos Forest
$101  constant chaos-forest-3           \ Chaos Forest
$102  constant chaos-forest-4           \ Chaos Forest
$103  constant chaos-forest-5           \ Chaos Forest
$104  constant chaos-forest-6           \ Chaos Forest
$105  constant chaos-forest-7           \ Chaos Forest
$106  constant chaos-forest-8           \ Chaos Forest
$107  constant chaos-forest-9           \ Chaos Forest
$108  constant chaos-forest-10          \ Chaos Forest
$109  constant chaos-forest-11          \ Chaos Forest
$10A  constant chaos-forest-12          \ Chaos Forest
$10B  constant chaos-forest-13          \ Chaos Forest

\ a room's name, for the console and traces ("unnamed-room": not on any map)
: room-name ( room -- addr len )
    case
        $0 of  s" front-garden-1"  endof
        $1 of  s" castle-1f-1"  endof
        $2 of  s" castle-1f-2"  endof
        $3 of  s" castle-1f-11"  endof
        $4 of  s" castle-1f-12"  endof
        $5 of  s" castle-2f-9"  endof
        $6 of  s" castle-3f-1"  endof
        $7 of  s" castle-b1-4"  endof
        $8 of  s" castle-1f-13"  endof
        $9 of  s" castle-1f-3"  endof
        $A of  s" castle-2f-1"  endof
        $B of  s" castle-b1-5"  endof
        $C of  s" castle-b1-6"  endof
        $E of  s" castle-1f-14"  endof
        $F of  s" castle-1f-4"  endof
        $10 of  s" castle-1f-5"  endof
        $11 of  s" castle-1f-6"  endof
        $12 of  s" castle-b1-1"  endof
        $13 of  s" front-garden-2"  endof
        $14 of  s" castle-b1-2"  endof
        $15 of  s" castle-1f-7"  endof
        $16 of  s" castle-b1-3"  endof
        $17 of  s" castle-2f-10"  endof
        $18 of  s" castle-1f-8"  endof
        $19 of  s" castle-1f-15"  endof
        $1A of  s" castle-1f-16"  endof
        $1B of  s" castle-1f-17"  endof
        $1C of  s" castle-1f-18"  endof
        $1D of  s" castle-b1-7"  endof
        $1E of  s" castle-1f-19"  endof
        $1F of  s" castle-2f-11"  endof
        $20 of  s" castle-2f-2"  endof
        $21 of  s" castle-2f-3"  endof
        $22 of  s" castle-2f-6"  endof
        $23 of  s" castle-2f-7"  endof
        $24 of  s" castle-2f-8"  endof
        $25 of  s" castle-1f-9"  endof
        $26 of  s" castle-2f-12"  endof
        $28 of  s" castle-2f-13"  endof
        $29 of  s" castle-1f-10"  endof
        $2A of  s" front-garden-3"  endof
        $2B of  s" front-garden-4"  endof
        $2C of  s" castle-3f-2"  endof
        $2D of  s" front-garden-5"  endof
        $2E of  s" old-mansion-1f-1"  endof
        $2F of  s" castle-2f-14"  endof
        $30 of  s" castle-2f-15"  endof
        $31 of  s" castle-2f-4"  endof
        $32 of  s" castle-2f-5"  endof
        $40 of  s" old-mansion-1f-2"  endof
        $41 of  s" old-mansion-1f-3"  endof
        $42 of  s" old-mansion-1f-4"  endof
        $43 of  s" old-mansion-1f-5"  endof
        $44 of  s" old-mansion-b1-1"  endof
        $45 of  s" old-mansion-2f-1"  endof
        $46 of  s" old-mansion-1f-6"  endof
        $47 of  s" old-mansion-1f-7"  endof
        $48 of  s" old-mansion-1f-8"  endof
        $49 of  s" old-mansion-1f-9"  endof
        $4A of  s" old-mansion-2f-2"  endof
        $4B of  s" old-mansion-b1-2"  endof
        $4C of  s" old-mansion-b1-3"  endof
        $4D of  s" old-mansion-1f-10"  endof
        $4E of  s" old-mansion-1f-11"  endof
        $4F of  s" old-mansion-1f-12"  endof
        $50 of  s" old-mansion-b1-4"  endof
        $51 of  s" old-mansion-b1-5"  endof
        $52 of  s" old-mansion-1f-13"  endof
        $53 of  s" old-mansion-1f-14"  endof
        $54 of  s" old-mansion-1f-15"  endof
        $55 of  s" old-mansion-1f-16"  endof
        $56 of  s" old-mansion-2f-3"  endof
        $57 of  s" old-mansion-2f-4"  endof
        $58 of  s" old-mansion-2f-5"  endof
        $59 of  s" old-mansion-2f-6"  endof
        $5B of  s" old-mansion-2f-7"  endof
        $5C of  s" old-mansion-2f-8"  endof
        $5D of  s" old-mansion-1f-17"  endof
        $5E of  s" old-mansion-2f-9"  endof
        $5F of  s" old-mansion-2f-10"  endof
        $60 of  s" old-mansion-3f-1"  endof
        $61 of  s" old-mansion-b1-7"  endof
        $62 of  s" old-mansion-2f-11"  endof
        $63 of  s" old-mansion-3f-2"  endof
        $66 of  s" old-mansion-b1-6"  endof
        $67 of  s" chaos-forest-1"  endof
        $68 of  s" old-mansion-1f-18"  endof
        $69 of  s" old-mansion-2f-12"  endof
        $6A of  s" old-mansion-2f-13"  endof
        $6B of  s" old-mansion-1f-19"  endof
        $6C of  s" old-mansion-1f-20"  endof
        $6D of  s" old-mansion-1f-21"  endof
        $6E of  s" old-mansion-1f-22"  endof
        $6F of  s" old-mansion-1f-23"  endof
        $70 of  s" old-mansion-1f-24"  endof
        $80 of  s" lake-pathway-2"  endof
        $81 of  s" house-of-truth-1f-1"  endof
        $82 of  s" house-of-truth-2f-1"  endof
        $83 of  s" house-of-truth-2f-2"  endof
        $84 of  s" house-of-truth-b1-1"  endof
        $85 of  s" house-of-truth-b1-2"  endof
        $86 of  s" house-of-truth-b1-3"  endof
        $87 of  s" house-of-truth-b1-4"  endof
        $88 of  s" house-of-truth-1f-2"  endof
        $8A of  s" house-of-truth-1f-3"  endof
        $8C of  s" house-of-truth-1f-4"  endof
        $8D of  s" house-of-truth-1f-5"  endof
        $8E of  s" house-of-truth-1f-6"  endof
        $8F of  s" house-of-truth-1f-7"  endof
        $91 of  s" house-of-truth-1f-8"  endof
        $92 of  s" house-of-truth-1f-9"  endof
        $93 of  s" house-of-truth-b1-5"  endof
        $94 of  s" house-of-truth-b1-6"  endof
        $95 of  s" house-of-truth-b1-7"  endof
        $96 of  s" house-of-truth-b1-8"  endof
        $97 of  s" house-of-truth-b1-9"  endof
        $98 of  s" house-of-truth-b1-10"  endof
        $99 of  s" house-of-truth-b1-11"  endof
        $9A of  s" house-of-truth-b1-12"  endof
        $9B of  s" house-of-truth-1f-10"  endof
        $C0 of  s" water-tower-b1-1"  endof
        $C1 of  s" water-tower-1f-1"  endof
        $C2 of  s" water-tower-2f-1"  endof
        $C3 of  s" water-tower-4f-1"  endof
        $C5 of  s" water-tower-7f-1"  endof
        $C6 of  s" water-tower-7f-2"  endof
        $C7 of  s" water-tower-8f-1"  endof
        $C8 of  s" lake-pathway-1"  endof
        $100 of  s" chaos-forest-2"  endof
        $101 of  s" chaos-forest-3"  endof
        $102 of  s" chaos-forest-4"  endof
        $103 of  s" chaos-forest-5"  endof
        $104 of  s" chaos-forest-6"  endof
        $105 of  s" chaos-forest-7"  endof
        $106 of  s" chaos-forest-8"  endof
        $107 of  s" chaos-forest-9"  endof
        $108 of  s" chaos-forest-10"  endof
        $109 of  s" chaos-forest-11"  endof
        $10A of  s" chaos-forest-12"  endof
        $10B of  s" chaos-forest-13"  endof
        >r  s" unnamed-room"  r>
    endcase ;
