/* Static initialisers (MW __sinit_*), run before main by the runtime (native: native/platform/main.c).
 * Generated by tools/sinit_gen.py from the straight-line ones: they copy constant state
 * PTMFs (and a few other values) from .data into .bss globals. */
#include <string.h>
#include "common.h"
#include "ptmf.h"
#include "random.h"
#include "system.h"
#include "msl.h"

extern const PTMF Debilitas_StartWander_ptmf;
extern const PTMF Debilitas_StartTurnToFiona_ptmf;
extern const PTMF Debilitas_StartLunge_ptmf;
extern const PTMF Debilitas_StartGrab_ptmf;
extern PTMF D_003AF2D0;
extern PTMF D_003AF2EC;
extern PTMF D_003AF308;
extern PTMF D_003AF324;
extern const PTMF Palette_FlatLow_ptmf;
extern const PTMF Palette_FlatHigh_ptmf;
extern const PTMF Palette_Colour_ptmf;
extern const PTMF Palette_RandomGrey_ptmf;
extern const PTMF Palette_Grey_ptmf;
extern const PTMF Palette_Threshold_ptmf;
extern const PTMF Palette_Alpha11_ptmf;
extern const PTMF Pursuer_StateStand_ptmf;
extern const PTMF D_003EC150;
extern const PTMF Pursuer_StateWalkThenAnim_ptmf;
extern const PTMF D_003EC170;
extern const PTMF D_003EC180;
extern const PTMF D_003EC190;
extern const PTMF D_003EC1A0;
extern const PTMF D_003EC1B0;
extern const PTMF D_003EC1C0;
extern const PTMF D_003EC1D0;
extern const PTMF D_003EC1E0;
extern const PTMF D_003EC1F0;
extern const PTMF D_003EC200;
extern const PTMF D_003EC210;
extern const PTMF D_003EC220;
extern const PTMF D_003EC230;
extern const PTMF D_003EC240;
extern const PTMF D_003EC250;
extern const PTMF D_003EC260;
extern const PTMF Pursuer_AttackNextStep_ptmf2;
extern const PTMF Pursuer_StateFaceFiona_ptmf;
extern const PTMF Pursuer_StateWalkOn_ptmf;
extern const PTMF Pursuer_StateLookAround_ptmf;
extern const PTMF Pursuer_StateWalkGesture_ptmf;
extern const PTMF Pursuer_StateWalkGesture_ptmf2;
extern const PTMF Pursuer_StateWalkGesture_ptmf3;
extern const PTMF Pursuer_StateSidestepRoom_ptmf;
extern const PTMF Pursuer_StateSidestepRoom_ptmf2;
extern const PTMF D_003EC300;
extern const PTMF Pursuer_StateWalkThen404_ptmf;
extern const PTMF Pursuer_StateFlinch_ptmf;
extern const PTMF Pursuer_StateKnockedDown_ptmf;
extern const PTMF Pursuer_StateHurt_ptmf;
extern const PTMF Pursuer_StateHitAtDoor_ptmf;
extern const PTMF Pursuer_StateDoorAhead_ptmf;
extern const PTMF Pursuer_StateHewieBites_ptmf;
extern const PTMF Pursuer_StateSpecialAnim_ptmf;
extern const PTMF D_003EC390;
extern const PTMF D_003EC3A0;
extern const PTMF D_003EC3B0;
extern const PTMF D_003EC3C0;
extern const PTMF D_003EC3D0;
extern PTMF kPursuerSteps;
extern PTMF D_003EC3FC;
extern PTMF D_003EC418;
extern PTMF D_003EC434;
extern PTMF D_003EC450;
extern PTMF D_003EC46C;
extern PTMF D_003EC488;
extern PTMF D_003EC4A4;
extern PTMF D_003EC4C0;
extern PTMF D_003EC4DC;
extern PTMF D_003EC4F8;
extern PTMF D_003EC514;
extern PTMF D_003EC530;
extern PTMF D_003EC54C;
extern PTMF D_003EC568;
extern PTMF D_003EC584;
extern PTMF D_003EC5A0;
extern PTMF D_003EC5BC;
extern PTMF D_003EC5D8;
extern PTMF D_003EC5F4;
extern PTMF D_003EC610;
extern PTMF D_003EC62C;
extern PTMF D_003EC648;
extern PTMF D_003EC664;
extern PTMF D_003EC680;
extern PTMF D_003EC69C;
extern PTMF D_003EC6B8;
extern PTMF D_003EC6D4;
extern PTMF D_003EC6F0;
extern PTMF D_003EC70C;
extern PTMF D_003EC728;
extern PTMF D_003EC744;
extern PTMF D_003EC760;
extern PTMF D_003EC77C;
extern PTMF D_003EC798;
extern PTMF D_003EC7B4;
extern PTMF D_003EC7D0;
extern PTMF D_003EC7EC;
extern PTMF D_003EC808;
extern PTMF D_003EC824;
extern PTMF D_003EC840;
extern PTMF D_003EC85C;
extern const PTMF D_003EC878;
extern const PTMF D_003EC888;
extern const PTMF D_003EC898;
extern const PTMF D_003EC8A8;
extern const PTMF D_003EC8B8;
extern const PTMF D_003EC8C8;
extern const PTMF Room00_Cmd00_ptmf;
extern const PTMF Room00_Cmd01_ptmf;
extern const PTMF D_003EE730;
extern const PTMF Room02_Cmd00_ptmf;
extern const PTMF Room02_Cmd01_ptmf;
extern const PTMF Room02_Cmd02_ptmf;
extern const PTMF Room02_Cmd03_ptmf;
extern const PTMF Room02_Cond00_ptmf;
extern const PTMF Room02_Cond01_ptmf;
extern const PTMF Room03_Cmd00_ptmf;
extern const PTMF Room03_Cmd01_ptmf;
extern const PTMF Room04_Cmd00_ptmf;
extern const PTMF Room04_Cmd01_ptmf;
extern const PTMF Room04_Cmd02_ptmf;
extern const PTMF Room04_Cmd03_ptmf;
extern const PTMF Room06_Cmd00_ptmf;
extern const PTMF Room08_Cmd00_ptmf;
extern const PTMF Room08_Cmd01_ptmf;
extern const PTMF Room08_Cond00_ptmf;
extern const PTMF Room08_Cond01_ptmf;
extern const PTMF Room09_Cond00_ptmf;
extern const PTMF Room0A_Cmd00_ptmf;
extern const PTMF Room0A_Cmd01_ptmf;
extern const PTMF Room0B_Cond00_ptmf;
extern const PTMF Room0C_Cmd00_ptmf;
extern const PTMF Room0C_Cmd01_ptmf;
extern const PTMF Room0C_Cmd02_ptmf;
extern const PTMF Room0C_Cmd03_ptmf;
extern const PTMF Room0F_Cmd00_ptmf;
extern const PTMF Room0F_Cmd01_ptmf;
extern const PTMF Room0F_Cmd02_ptmf;
extern const PTMF Room0F_Cmd03_ptmf;
extern const PTMF Room0F_Cmd04_ptmf;
extern const PTMF Room10_Cond00_ptmf;
extern const PTMF Room12_Cmd00_ptmf;
extern const PTMF Room12_Cond00_ptmf;
extern const PTMF Room13_Cmd00_ptmf;
extern const PTMF Room14_Cmd00_ptmf;
extern const PTMF Room15_Cmd00_ptmf;
extern const PTMF Room15_Cond00_ptmf;
extern const PTMF Room18_Cmd00_ptmf;
extern const PTMF Room19_Cond00_ptmf;
extern const PTMF Room1A_Cmd00_ptmf;
extern const PTMF Room1A_Cmd01_ptmf;
extern const PTMF Room1B_Cmd00_ptmf;
extern const PTMF Room1C_Cmd00_ptmf;
extern const PTMF Room1C_Cmd01_ptmf;
extern const PTMF Room1D_Cmd00_ptmf;
extern const PTMF Room1D_Cmd01_ptmf;
extern const PTMF Room1D_Cond00_ptmf;
extern const PTMF Room1F_Cmd00_ptmf;
extern const PTMF Room20_Cmd00_ptmf;
extern const PTMF Room20_Cmd01_ptmf;
extern const PTMF Room20_Cmd02_ptmf;
extern const PTMF Room20_Cmd03_ptmf;
extern const PTMF Room20_Cmd04_ptmf;
extern const PTMF Room20_Cmd05_ptmf;
extern const PTMF Room20_Cond00_ptmf;
extern const PTMF Room20_Cond01_ptmf;
extern const PTMF Room20_Cond02_ptmf;
extern const PTMF Room21_Cmd00_ptmf;
extern const PTMF Room21_Cmd01_ptmf;
extern const PTMF Room21_Cmd02_ptmf;
extern const PTMF Room21_Cmd03_ptmf;
extern const PTMF Room21_Cmd04_ptmf;
extern const PTMF Room21_Cmd05_ptmf;
extern const PTMF Room21_Cmd06_ptmf;
extern const PTMF Room21_Cond00_ptmf;
extern const PTMF Room23_Cond00_ptmf;
extern const PTMF Room23_Cmd00_ptmf;
extern const PTMF Room23_Cmd01_ptmf;
extern const PTMF Room24_KilnGlow_ptmf;
extern const PTMF Room24_Smoke_ptmf;
extern const PTMF Room24_ColourPulse_ptmf;
extern const PTMF Room25_Cmd00_ptmf;
extern const PTMF Room25_Cond00_ptmf;
extern const PTMF Room26_Cond00_ptmf;
extern const PTMF Room26_Cmd00_ptmf;
extern const PTMF Room26_Cmd01_ptmf;
extern const PTMF Room26_Cmd02_ptmf;
extern const PTMF Room28_Cond00_ptmf;
extern const PTMF Room29_Cond00_ptmf;
extern const PTMF Room29_Cond01_ptmf;
extern const PTMF Room2A_Cmd00_ptmf;
extern const PTMF Room2A_HandlerStep_ptmf;
extern const PTMF Room2A_Cmd02_ptmf;
extern const PTMF Room2A_Cmd03_ptmf;
extern const PTMF Room2B_Cmd00_ptmf;
extern const PTMF Room2D_Cmd00_ptmf;
extern const PTMF Room2D_Cmd01_ptmf;
extern const PTMF Room2D_Cmd02_ptmf;
extern const PTMF Room2D_Cond00_ptmf;
extern const PTMF Room40_Cmd00_ptmf;
extern const PTMF Room43_Cmd00_ptmf;
extern const PTMF Room45_Cmd00_ptmf;
extern const PTMF Room49_Cmd00_ptmf;
extern const PTMF Room49_Cmd01_ptmf;
extern const PTMF Room49_Cmd02_ptmf;
extern const PTMF Room4B_Cmd00_ptmf;
extern const PTMF Room4B_Cmd01_ptmf;
extern const PTMF Room4B_Cond00_ptmf;
extern const PTMF Room4C_Cmd00_ptmf;
extern const PTMF Room4C_Cmd01_ptmf;
extern const PTMF Room4C_Cmd02_ptmf;
extern const PTMF Room4E_Cmd00_ptmf;
extern const PTMF Room4E_Cmd01_ptmf;
extern const PTMF Room4E_Cmd02_ptmf;
extern const PTMF Room4F_Cmd00_ptmf;
extern const PTMF Room4F_Cmd01_ptmf;
extern const PTMF Room4F_Cmd02_ptmf;
extern const PTMF Room4F_Cmd03_ptmf;
extern const PTMF Room4F_CreatureVanish_ptmf;
extern const PTMF Room50_Cmd00_ptmf;
extern const PTMF Room51_Cmd00_ptmf;
extern const PTMF Room51_Cmd01_ptmf;
extern const PTMF Room52_Cmd00_ptmf;
extern const PTMF Room52_Cond00_ptmf;
extern const PTMF Room56_Cmd00_ptmf;
extern const PTMF Room59_Cmd00_ptmf;
extern const PTMF Room5A_Cmd00_ptmf;
extern const PTMF Room5C_Cmd00_ptmf;
extern const PTMF Room5C_Cond00_ptmf;
extern const PTMF Room5D_Cmd00_ptmf;
extern const PTMF Room5D_Cmd01_ptmf;
extern const PTMF Room2F_Cond00_ptmf;
extern const PTMF Room30_Cond00_ptmf;
extern const PTMF Debilitas3_StateNone_ptmf;
extern const PTMF Debilitas3_StartTurnToFiona_ptmf;
extern const PTMF Debilitas3_StartLunge_ptmf;
extern const PTMF Debilitas3_StartGrab_ptmf;
extern PTMF D_004135D0;
extern PTMF D_004135EC;
extern PTMF D_00413608;
extern PTMF D_00413624;
extern const PTMF Riccardo_StartFlurry_ptmf;
extern const PTMF Riccardo_StartLunge_ptmf;
extern PTMF D_004148A0;
extern PTMF D_004148BC;
extern const PTMF Room46_CharHook_ptmf;
extern const PTMF Room46_PursuerBusy_ptmf;
extern const PTMF Room102_Cmd00_ptmf;
extern const PTMF Room103_Cmd00_ptmf;
extern const PTMF Room104_Cmd00_ptmf;
extern const PTMF Room105_Cmd00_ptmf;
extern const PTMF Room106_Cmd00_ptmf;
extern const PTMF Room107_Cond00_ptmf;
extern const PTMF Room107_Cmd00_ptmf;
extern const PTMF Room107_Cmd01_ptmf;
extern const PTMF Room108_Cmd00_ptmf;
extern const PTMF Room109_Cmd00_ptmf;
extern const PTMF Room109_Cmd01_ptmf;
extern const PTMF Room10A_Cond00_ptmf;
extern const PTMF Room10A_Cmd00_ptmf;
extern const PTMF Room10B_Cmd00_ptmf;
extern const PTMF Room10B_Cond00_ptmf;
extern const PTMF Room_EmptyHook_ptmf;
extern const PTMF D_0041B640;
extern const PTMF D_0041B650;
extern const PTMF D_0041B660;
extern PTMF D_0041B670;
extern PTMF D_0041B68C;
extern PTMF D_0041B6A8;
extern PTMF D_0041B6C4;
extern const PTMF Room27_Cmd00_ptmf;
extern const PTMF Room2E_Cmd00_ptmf;
extern const PTMF Room2E_Cmd01_ptmf;
extern const PTMF Room2E_Cmd02_ptmf;
extern const PTMF Room2E_Cmd03_ptmf;
extern const PTMF Room2E_Cmd04_ptmf;
extern const PTMF Room66_CharHook_ptmf;
extern const PTMF Room66_Effect_ptmf;
extern const PTMF Room66_Sink_ptmf;
extern const PTMF Room66_Fire_ptmf;
extern const PTMF Room66_ColourPulse_ptmf;
extern const PTMF Room66_Letters_ptmf;
extern const PTMF Room66_CharPast_ptmf;
extern const PTMF Room55_Effect_ptmf;
extern const PTMF Room63_Cmd00_ptmf;
extern const PTMF Room62_Cmd00_ptmf;
extern const PTMF Room62_Cmd01_ptmf;
extern const PTMF Lorenzo2_StartSink_ptmf;
extern const PTMF Lorenzo2_StartStalkBelow_ptmf;
extern const PTMF Lorenzo2_StartGrab_ptmf;
extern PTMF D_00422690;
extern PTMF D_004226AC;
extern PTMF D_004226C8;
extern const PTMF Room48_Cmd00_ptmf;
extern const PTMF Room48_Cmd01_ptmf;
extern const PTMF Room48_Cmd02_ptmf;
extern const PTMF Room48_Cmd03_ptmf;
extern const PTMF Room48_Cmd04_ptmf;
extern const PTMF Room48_Cmd05_ptmf;
extern const PTMF Room48_Cond00_ptmf;
extern const PTMF Room54_GroupStep_ptmf;
extern const PTMF Room54_DoorRegions_ptmf;
extern const PTMF Room60_Cmd00_ptmf;
extern const PTMF Room60_Cmd01_ptmf;
extern const PTMF Room60_Cmd02_ptmf;
extern const PTMF Room60_Cmd03_ptmf;
extern const PTMF Room60_Cmd04_ptmf;
extern const PTMF Room60_Cmd05_ptmf;
extern const PTMF Room61_Cmd00_ptmf;
extern const PTMF Room61_Cmd01_ptmf;
extern const PTMF Room31_RoomEffect_ptmf;
extern const PTMF Room31_Fan_ptmf;
extern const PTMF Room31_WindowLight_ptmf;
extern const PTMF Room32_Cmd00_ptmf;
extern const PTMF Room32_Cmd01_ptmf;
extern const PTMF Room32_Cmd02_ptmf;
extern const PTMF Room32_Cmd03_ptmf;
extern const PTMF Room32_Cmd04_ptmf;
extern const PTMF Room32_Cmd05_ptmf;
extern const PTMF Room86_Cmd00_ptmf;
extern const PTMF RoomC0_Cmd00_ptmf;
extern const PTMF RoomC0_Cmd01_ptmf;
extern const PTMF RoomC0_Cmd02_ptmf;
extern const PTMF RoomC0_Cmd03_ptmf;
extern const PTMF RoomC0_Cmd04_ptmf;
extern const PTMF RoomC0_Cond00_ptmf;
extern const PTMF Kind27_StateNone_ptmf;
extern const PTMF Kind27_StartTurnToFiona_ptmf;
extern const PTMF Kind27_StartLunge_ptmf;
extern const PTMF Kind27_StartGrab_ptmf;
extern PTMF D_0042E540;
extern PTMF D_0042E55C;
extern PTMF D_0042E578;
extern PTMF D_0042E594;
extern const PTMF RoomC7_Cmd00_ptmf;
extern const PTMF RoomC7_Cmd01_ptmf;
extern const PTMF RoomC7_Cmd02_ptmf;
extern const PTMF RoomC7_Cmd03_ptmf;
extern const PTMF RoomC7_Cmd04_ptmf;
extern const PTMF RoomC7_Cmd05_ptmf;
extern const PTMF RoomC7_Cmd06_ptmf;
extern const PTMF RoomC7_Cond00_ptmf;
extern const PTMF RoomC7_Cond01_ptmf;
extern const PTMF Room84_Cmd00_ptmf;
extern const PTMF Room85_Cmd00_ptmf;
extern const PTMF Room87_Cmd00_ptmf;
extern const PTMF Room88_Cmd00_ptmf;
extern const PTMF Room8C_Cmd00_ptmf;
extern const PTMF Room8C_Cmd01_ptmf;
extern const PTMF Room8C_Cmd02_ptmf;
extern const PTMF Room8C_Cmd03_ptmf;
extern const PTMF Room8C_Cmd04_ptmf;
extern const PTMF Room8D_Cmd00_ptmf;
extern const PTMF Room8D_Cmd01_ptmf;
extern const PTMF Room8D_Cmd02_ptmf;
extern const PTMF Room8E_Cmd00_ptmf;
extern const PTMF Room8E_Cmd01_ptmf;
extern const PTMF Room8F_Cmd00_ptmf;
extern const PTMF Room8F_Cmd01_ptmf;
extern const PTMF Room8F_Cmd02_ptmf;
extern const PTMF Room8F_Cmd03_ptmf;
extern const PTMF Room8F_Cond00_ptmf;
extern const PTMF Room91_Cmd00_ptmf;
extern const PTMF Room91_Cmd01_ptmf;
extern const PTMF Room91_Cmd02_ptmf;
extern const PTMF Room91_Cmd03_ptmf;
extern const PTMF Room92_Cmd00_ptmf;
extern const PTMF Room92_Cmd01_ptmf;
extern const PTMF Room92_Cmd02_ptmf;
extern const PTMF Room92_Cmd03_ptmf;
extern const PTMF Room92_Cmd04_ptmf;
extern const PTMF Room92_Cmd05_ptmf;
extern const PTMF Room92_Cmd06_ptmf;
extern const PTMF Room92_Cmd07_ptmf;
extern const PTMF Room92_Cmd08_ptmf;
extern const PTMF Room92_Cmd09_ptmf;
extern const PTMF Room92_Cmd10_ptmf;
extern const PTMF Room92_Cmd11_ptmf;
extern const PTMF Room92_Cmd12_ptmf;
extern const PTMF Room92_Cmd13_ptmf;
extern const PTMF Room97_Cmd00_ptmf;
extern const PTMF Room69_Cmd00_ptmf;
extern const PTMF Room6A_Cmd00_ptmf;
extern const PTMF Room6A_Cmd01_ptmf;
extern const PTMF Room6C_Cond00_ptmf;
extern const PTMF Room6C_Cond01_ptmf;
extern const PTMF Room6D_Cond00_ptmf;
extern const PTMF Room6D_Cond01_ptmf;
extern const PTMF Room6F_Cmd00_ptmf;
extern const PTMF Room6F_Cond00_ptmf;
extern const PTMF Room80_Cmd00_ptmf;
extern const PTMF RoomC1_Cond00_ptmf;
extern const PTMF RoomC2_Cmd00_ptmf;
extern const PTMF RoomC2_Cmd01_ptmf;
extern const PTMF RoomC2_Cond00_ptmf;
extern const PTMF RoomC3_Cmd00_ptmf;
extern const PTMF RoomC3_Cmd01_ptmf;
extern const PTMF RoomC3_Cmd02_ptmf;
extern const PTMF RoomC3_Cond00_ptmf;
extern const PTMF RoomC5_Cmd00_ptmf;
extern const PTMF RoomC8_Cmd00_ptmf;
extern const PTMF Room98_SlamShake_ptmf;
extern const PTMF Room99_SlamShake_ptmf;
extern const PTMF Room9A_Cmd00_ptmf;
extern const PTMF Room9B_Cmd00_ptmf;
extern const PTMF Room93_SlamShake_ptmf;
extern const PTMF Room94_Cmd00_ptmf;
extern const PTMF Room95_Cmd00_ptmf;
extern const PTMF Room96_Cmd00_ptmf;
extern const PTMF Kind39_StartSink_ptmf;
extern const PTMF Kind39_StartStalkBelow_ptmf;
extern const PTMF Kind39_StartGrab_ptmf;
extern PTMF D_00444CE0;
extern PTMF D_00444CFC;
extern PTMF D_00444D18;
extern const PTMF Room37_Fan_ptmf;
extern const PTMF RoomD0_ClockStop_ptmf;
extern const PTMF RoomD0_ClockSave_ptmf;
extern const PTMF RoomD0_ClockDrawSaved_ptmf;
extern const PTMF RoomD0_ProgressCall_ptmf;
extern const PTMF RoomD1_Cmd00_ptmf;
extern const PTMF RoomD1_Cmd01_ptmf;
extern const PTMF RoomD1_Cond00_ptmf;
extern const PTMF RoomD2_Cmd00_ptmf;
extern const PTMF RoomD2_Cond00_ptmf;
extern const PTMF RoomD3_Cmd00_ptmf;
extern const PTMF RoomD3_Cond00_ptmf;
extern const PTMF RoomD4_Cmd00_ptmf;
extern const PTMF RoomD4_Cond00_ptmf;
extern const PTMF RoomD5_Cmd00_ptmf;
extern const PTMF RoomD5_Cmd01_ptmf;
extern const PTMF RoomD5_Cmd02_ptmf;
extern const PTMF RoomD5_Cond00_ptmf;
extern const PTMF RoomD6_Cmd00_ptmf;
extern const PTMF RoomD6_Cmd01_ptmf;
extern const PTMF RoomD6_Cond00_ptmf;
extern const PTMF D_00447B70;
extern const PTMF RoomD7_Cond01_ptmf;
extern const PTMF RoomD7_Cmd00_ptmf;
extern const PTMF RoomD7_Cmd01_ptmf;
extern const PTMF RoomD7_Cmd02_ptmf;
extern const PTMF D_00447E20;
extern const PTMF RoomD8_Cond01_ptmf;
extern const PTMF RoomD8_Cmd00_ptmf;
extern const PTMF RoomD8_Cmd01_ptmf;
extern const PTMF RoomD9_Cmd00_ptmf;
extern const PTMF RoomD9_Cmd01_ptmf;
extern const PTMF RoomD9_Cmd02_ptmf;
extern const PTMF RoomD9_Cond00_ptmf;
extern const PTMF RoomE0_ClockStart_ptmf;
extern const PTMF RoomE0_Fan_ptmf;
extern const PTMF RoomE0_WindowLight_ptmf;
extern const PTMF RoomE0_DoorLight_ptmf;
extern const PTMF RoomE0_ClockDraw_ptmf;
extern const PTMF RoomE0_ChooseExit_ptmf;
extern const PTMF RoomE0_ProgressCall_ptmf;
extern const PTMF RoomE1_Cmd00_ptmf;
extern const PTMF RoomE1_Cond00_ptmf;
extern const PTMF RoomE2_Cmd00_ptmf;
extern const PTMF RoomE2_Cond00_ptmf;
extern const PTMF RoomE3_Cmd00_ptmf;
extern const PTMF RoomE3_Cond00_ptmf;
extern const PTMF RoomE4_Cmd00_ptmf;
extern const PTMF RoomE4_Cmd01_ptmf;
extern const PTMF RoomE4_Cond00_ptmf;
extern const PTMF RoomE5_Cmd00_ptmf;
extern const PTMF RoomE5_Cmd01_ptmf;
extern const PTMF RoomE5_Cond00_ptmf;
extern const PTMF RoomE6_Cmd00_ptmf;
extern const PTMF RoomE6_Cmd01_ptmf;
extern const PTMF RoomE6_Cond00_ptmf;
extern const PTMF RoomE7_Cmd00_ptmf;
extern const PTMF RoomE7_Cond00_ptmf;
extern const PTMF RoomE8_Cmd00_ptmf;
extern const PTMF RoomE8_Cond00_ptmf;
extern const PTMF RoomE9_Cmd00_ptmf;
extern const PTMF RoomE9_Cmd01_ptmf;
extern const PTMF RoomE9_Cmd02_ptmf;
extern const PTMF RoomE9_Cmd03_ptmf;
extern const PTMF RoomE9_Cond00_ptmf;
extern PTMF kPursuerMove;
extern PTMF kPursuerWaitMove;
extern PTMF kPursuerMoveA;
extern PTMF kPursuerStairsMove;
extern PTMF kPursuerIdleMove;
extern PTMF kPursuerMoveB;
extern PTMF kPaletteGenerators;
extern PTMF D_0047E30C;
extern PTMF D_0047E318;
extern PTMF D_0047E324;
extern PTMF D_0047E330;
extern PTMF D_0047E33C;
extern PTMF D_0047E348;
extern PTMF D_01990700;
extern PTMF D_0199070C;
extern PTMF Room00_CondTable;
extern PTMF Room02_CmdTable;
extern PTMF D_0199073C;
extern PTMF D_01990748;
extern PTMF D_01990754;
extern PTMF Room02_CondTable;
extern PTMF D_0199076C;
extern PTMF Room03_CmdTable;
extern PTMF D_0199078C;
extern PTMF Room04_CmdTable;
extern PTMF D_019907AC;
extern PTMF D_019907B8;
extern PTMF D_019907C4;
extern PTMF Room06_CmdTable;
extern PTMF Room08_CmdTable;
extern PTMF D_019907EC;
extern PTMF Room08_CondTable;
extern PTMF D_0199080C;
extern PTMF Room09_CondTable;
extern PTMF Room0A_CmdTable;
extern PTMF D_0199083C;
extern PTMF Room0B_CondTable;
extern PTMF Room0C_CmdTable;
extern PTMF D_0199086C;
extern PTMF D_01990878;
extern PTMF D_01990884;
extern PTMF Room0F_CmdTable;
extern PTMF D_0199089C;
extern PTMF D_019908A8;
extern PTMF D_019908B4;
extern PTMF D_019908C0;
extern PTMF Room10_CondTable;
extern PTMF Room12_CmdTable;
extern PTMF Room12_CondTable;
extern PTMF Room13_CmdTable;
extern PTMF Room14_CmdTable;
extern PTMF Room15_CmdTable;
extern PTMF Room15_CondTable;
extern PTMF Room18_CmdTable;
extern PTMF Room19_CondTable;
extern PTMF Room1A_CmdTable;
extern PTMF D_0199096C;
extern PTMF Room1B_CmdTable;
extern PTMF Room1C_CmdTable;
extern PTMF D_0199099C;
extern PTMF Room1D_CmdTable;
extern PTMF D_019909BC;
extern PTMF Room1D_CondTable;
extern PTMF Room1F_CmdTable;
extern PTMF Room20_CmdTable;
extern PTMF D_019909FC;
extern PTMF D_01990A08;
extern PTMF D_01990A14;
extern PTMF D_01990A20;
extern PTMF D_01990A2C;
extern PTMF Room20_CondTable;
extern PTMF D_01990A4C;
extern PTMF D_01990A58;
extern PTMF Room21_CmdTable;
extern PTMF D_01990A7C;
extern PTMF D_01990A88;
extern PTMF D_01990A94;
extern PTMF D_01990AA0;
extern PTMF D_01990AAC;
extern PTMF D_01990AB8;
extern PTMF Room21_CondTable;
extern PTMF Room23_CondTable;
extern PTMF Room23_CmdTable;
extern PTMF D_01990AFC;
extern PTMF Room24_CmdTable;
extern PTMF D_01990B1C;
extern PTMF D_01990B28;
extern PTMF Room25_CmdTable;
extern PTMF Room25_CondTable;
extern PTMF Room26_CondTable;
extern PTMF Room26_CmdTable;
extern PTMF D_01990B7C;
extern PTMF D_01990B88;
extern PTMF Room28_CondTable;
extern PTMF Room29_CondTable;
extern PTMF D_01990BBC;
extern PTMF Room2A_CmdTable;
extern PTMF D_01990BDC;
extern PTMF D_01990BE8;
extern PTMF D_01990BF4;
extern PTMF Room2B_CmdTable;
extern PTMF Room2D_CmdTable;
extern PTMF D_01990C1C;
extern PTMF D_01990C28;
extern PTMF Room2D_CondTable;
extern PTMF Room40_CmdTable;
extern PTMF Room43_CmdTable;
extern PTMF Room45_CmdTable;
extern PTMF Room49_CmdTable;
extern PTMF D_01990C8C;
extern PTMF D_01990C98;
extern PTMF Room4B_CmdTable;
extern PTMF D_01990CBC;
extern PTMF Room4B_CondTable;
extern PTMF Room4C_CmdTable;
extern PTMF D_01990CEC;
extern PTMF D_01990CF8;
extern PTMF Room4E_CmdTable;
extern PTMF D_01990D1C;
extern PTMF D_01990D28;
extern PTMF D_01990D40;
extern PTMF D_01990D4C;
extern PTMF D_01990D58;
extern PTMF D_01990D64;
extern PTMF Room4F_CondTable;
extern PTMF Room50_CmdTable;
extern PTMF Room51_CmdTable;
extern PTMF D_01990D9C;
extern PTMF Room52_CmdTable;
extern PTMF Room52_CondTable;
extern PTMF Room56_CmdTable;
extern PTMF Room59_CmdTable;
extern PTMF Room5A_CmdTable;
extern PTMF Room5C_CmdTable;
extern PTMF Room5C_CondTable;
extern PTMF Room5D_CmdTable;
extern PTMF D_01990E2C;
extern PTMF Room2F_CondTable;
extern PTMF Room30_CondTable;
extern PTMF Room46_CmdTable;
extern PTMF Room46_CondTable;
extern PTMF Room102_CmdTable;
extern PTMF Room103_CmdTable;
extern PTMF Room104_CmdTable;
extern PTMF Room105_CmdTable;
extern PTMF Room106_CmdTable;
extern PTMF Room107_CondTable;
extern PTMF Room107_CmdTable;
extern PTMF D_01990F0C;
extern PTMF Room108_CmdTable;
extern PTMF Room109_CmdTable;
extern PTMF D_01990F3C;
extern PTMF Room10A_CondTable;
extern PTMF Room10A_CmdTable;
extern PTMF Room10B_CmdTable;
extern PTMF Room10B_CondTable;
extern PTMF Room27_CmdTable;
extern PTMF Room2E_CmdTable;
extern PTMF D_01990FFC;
extern PTMF D_01991008;
extern PTMF D_01991014;
extern PTMF D_01991020;
extern PTMF Room66_CmdTable;
extern PTMF D_0199103C;
extern PTMF D_01991048;
extern PTMF D_01991054;
extern PTMF D_01991060;
extern PTMF Room66_CondTable;
extern PTMF D_0199107C;
extern PTMF Room55_CmdTable;
extern PTMF Room63_CmdTable;
extern PTMF Room62_CmdTable;
extern PTMF D_019910BC;
extern PTMF Room48_CmdTable;
extern PTMF D_0199114C;
extern PTMF D_01991158;
extern PTMF D_01991164;
extern PTMF D_01991170;
extern PTMF D_0199117C;
extern PTMF Room48_CondTable;
extern PTMF Room54_CmdTable;
extern PTMF D_019911AC;
extern PTMF Room60_CmdTable;
extern PTMF D_019911CC;
extern PTMF D_019911D8;
extern PTMF D_019911E4;
extern PTMF D_019911F0;
extern PTMF D_019911FC;
extern PTMF Room61_CmdTable;
extern PTMF D_0199155C;
extern PTMF Room31_CmdTable;
extern PTMF D_0199157C;
extern PTMF D_01991588;
extern PTMF Room32_CmdTable;
extern PTMF D_019915AC;
extern PTMF D_019915B8;
extern PTMF D_019915C4;
extern PTMF D_019915D0;
extern PTMF D_019915DC;
extern PTMF Room86_CmdTable;
extern PTMF RoomC0_CmdTable;
extern PTMF D_0199161C;
extern PTMF D_01991628;
extern PTMF D_01991634;
extern PTMF D_01991640;
extern PTMF RoomC0_CondTable;
extern PTMF RoomC7_CmdTable;
extern PTMF D_0199166C;
extern PTMF D_01991678;
extern PTMF D_01991684;
extern PTMF D_01991690;
extern PTMF D_0199169C;
extern PTMF D_019916A8;
extern PTMF RoomC7_CondTable;
extern PTMF D_019916CC;
extern PTMF Room84_CmdTable;
extern PTMF Room85_CmdTable;
extern PTMF Room87_CmdTable;
extern PTMF Room88_CmdTable;
extern PTMF Room8C_CmdTable;
extern PTMF D_0199172C;
extern PTMF D_01991738;
extern PTMF D_01991744;
extern PTMF D_01991750;
extern PTMF Room8D_CmdTable;
extern PTMF D_0199176C;
extern PTMF D_01991778;
extern PTMF Room8E_CmdTable;
extern PTMF D_0199179C;
extern PTMF Room8F_CmdTable;
extern PTMF D_019917BC;
extern PTMF D_019917C8;
extern PTMF D_019917D4;
extern PTMF Room8F_CondTable;
extern PTMF Room91_CmdTable;
extern PTMF D_019917FC;
extern PTMF D_01991808;
extern PTMF D_01991814;
extern PTMF Room92_CmdTable;
extern PTMF D_0199182C;
extern PTMF D_01991838;
extern PTMF D_01991844;
extern PTMF D_01991850;
extern PTMF D_0199185C;
extern PTMF D_01991868;
extern PTMF D_01991874;
extern PTMF D_01991880;
extern PTMF D_0199188C;
extern PTMF D_01991898;
extern PTMF D_019918A4;
extern PTMF D_019918B0;
extern PTMF D_019918BC;
extern PTMF Room97_CmdTable;
extern PTMF Room69_CmdTable;
extern PTMF Room6A_CmdTable;
extern PTMF D_019918FC;
extern PTMF Room6C_CondTable;
extern PTMF D_0199191C;
extern PTMF Room6D_CondTable;
extern PTMF D_0199193C;
extern PTMF Room6F_CmdTable;
extern PTMF Room6F_CondTable;
extern PTMF Room80_CmdTable;
extern PTMF RoomC1_CondTable;
extern PTMF RoomC2_CmdTable;
extern PTMF D_0199199C;
extern PTMF RoomC2_CondTable;
extern PTMF RoomC3_CmdTable;
extern PTMF D_019919CC;
extern PTMF D_019919D8;
extern PTMF RoomC3_CondTable;
extern PTMF RoomC5_CmdTable;
extern PTMF RoomC8_CmdTable;
extern PTMF Room98_CmdTable;
extern PTMF Room99_CmdTable;
extern PTMF Room9A_CmdTable;
extern PTMF Room9B_CmdTable;
extern PTMF Room93_CmdTable;
extern PTMF Room94_CmdTable;
extern PTMF Room95_CmdTable;
extern PTMF Room96_CmdTable;
extern PTMF Room37_CmdTable;
extern PTMF RoomD0_CmdTable;
extern PTMF D_01991ACC;
extern PTMF D_01991AD8;
extern PTMF RoomD0_CondTable;
extern PTMF RoomD1_CmdTable;
extern PTMF D_01991B0C;
extern PTMF RoomD1_CondTable;
extern PTMF RoomD2_CmdTable;
extern PTMF RoomD2_CondTable;
extern PTMF RoomD3_CmdTable;
extern PTMF RoomD3_CondTable;
extern PTMF RoomD4_CmdTable;
extern PTMF RoomD4_CondTable;
extern PTMF RoomD5_CmdTable;
extern PTMF D_01991B9C;
extern PTMF D_01991BA8;
extern PTMF RoomD5_CondTable;
extern PTMF RoomD6_CmdTable;
extern PTMF D_01991BDC;
extern PTMF RoomD6_CondTable;
extern PTMF RoomD7_CondTable;
extern PTMF D_01991C0C;
extern PTMF RoomD7_CmdTable;
extern PTMF D_01991C2C;
extern PTMF D_01991C38;
extern PTMF RoomD8_CondTable;
extern PTMF D_01991C5C;
extern PTMF RoomD8_CmdTable;
extern PTMF D_01991C7C;
extern PTMF RoomD9_CmdTable;
extern PTMF D_01991C9C;
extern PTMF D_01991CA8;
extern PTMF RoomD9_CondTable;
extern PTMF RoomE0_CmdTable;
extern PTMF D_01991CDC;
extern PTMF D_01991CE8;
extern PTMF D_01991CF4;
extern PTMF D_01991D00;
extern PTMF D_01991D0C;
extern PTMF RoomE0_CondTable;
extern PTMF RoomE1_CmdTable;
extern PTMF RoomE1_CondTable;
extern PTMF RoomE2_CmdTable;
extern PTMF RoomE2_CondTable;
extern PTMF RoomE3_CmdTable;
extern PTMF RoomE3_CondTable;
extern PTMF RoomE4_CmdTable;
extern PTMF D_01991D9C;
extern PTMF RoomE4_CondTable;
extern PTMF RoomE5_CmdTable;
extern PTMF D_01991DCC;
extern PTMF RoomE5_CondTable;
extern PTMF RoomE6_CmdTable;
extern PTMF D_01991DFC;
extern PTMF RoomE6_CondTable;
extern PTMF RoomE7_CmdTable;
extern PTMF RoomE7_CondTable;
extern PTMF RoomE8_CmdTable;
extern PTMF RoomE8_CondTable;
extern PTMF RoomE9_CmdTable;
extern PTMF D_01991E6C;
extern PTMF D_01991E78;
extern PTMF D_01991E84;
extern PTMF RoomE9_CondTable;

/* 0x00464860 */
void Sinit_Debilitas(void) {
    D_003AF2D0 = Debilitas_StartWander_ptmf;
    D_003AF2EC = Debilitas_StartTurnToFiona_ptmf;
    D_003AF308 = Debilitas_StartLunge_ptmf;
    D_003AF324 = Debilitas_StartGrab_ptmf;
}

/* 0x00464920 */
void Sinit_Renderer(void) {
    kPaletteGenerators = Palette_FlatLow_ptmf;
    D_0047E30C = Palette_FlatHigh_ptmf;
    D_0047E318 = Palette_Colour_ptmf;
    D_0047E324 = Palette_RandomGrey_ptmf;
    D_0047E330 = Palette_Grey_ptmf;
    D_0047E33C = Palette_Threshold_ptmf;
    D_0047E348 = Palette_Alpha11_ptmf;
}

/* 0x00464B80 */
void Sinit_Pursuer(void) {
    kPursuerSteps = Pursuer_StateStand_ptmf;
    D_003EC3FC = D_003EC150;
    D_003EC418 = Pursuer_StateWalkThenAnim_ptmf;
    D_003EC434 = D_003EC170;
    D_003EC450 = D_003EC180;
    D_003EC46C = D_003EC190;
    D_003EC488 = D_003EC1A0;
    D_003EC4A4 = D_003EC1B0;
    D_003EC4C0 = D_003EC1C0;
    D_003EC4DC = D_003EC1D0;
    D_003EC4F8 = D_003EC1E0;
    D_003EC514 = D_003EC1F0;
    D_003EC530 = D_003EC200;
    D_003EC54C = D_003EC210;
    D_003EC568 = D_003EC220;
    D_003EC584 = D_003EC230;
    D_003EC5A0 = D_003EC240;
    D_003EC5BC = D_003EC250;
    D_003EC5D8 = D_003EC260;
    D_003EC5F4 = Pursuer_AttackNextStep_ptmf2;
    D_003EC610 = Pursuer_StateFaceFiona_ptmf;
    D_003EC62C = Pursuer_StateWalkOn_ptmf;
    D_003EC648 = Pursuer_StateLookAround_ptmf;
    D_003EC664 = Pursuer_StateWalkGesture_ptmf;
    D_003EC680 = Pursuer_StateWalkGesture_ptmf2;
    D_003EC69C = Pursuer_StateWalkGesture_ptmf3;
    D_003EC6B8 = Pursuer_StateSidestepRoom_ptmf;
    D_003EC6D4 = Pursuer_StateSidestepRoom_ptmf2;
    D_003EC6F0 = D_003EC300;
    D_003EC70C = Pursuer_StateWalkThen404_ptmf;
    D_003EC728 = Pursuer_StateFlinch_ptmf;
    D_003EC744 = Pursuer_StateKnockedDown_ptmf;
    D_003EC760 = Pursuer_StateHurt_ptmf;
    D_003EC77C = Pursuer_StateHitAtDoor_ptmf;
    D_003EC798 = Pursuer_StateDoorAhead_ptmf;
    D_003EC7B4 = Pursuer_StateHewieBites_ptmf;
    D_003EC7D0 = Pursuer_StateSpecialAnim_ptmf;
    D_003EC7EC = D_003EC390;
    D_003EC808 = D_003EC3A0;
    D_003EC824 = D_003EC3B0;
    D_003EC840 = D_003EC3C0;
    D_003EC85C = D_003EC3D0;
    kPursuerMove = D_003EC878;
    kPursuerWaitMove = D_003EC888;
    kPursuerMoveA = D_003EC898;
    kPursuerStairsMove = D_003EC8A8;
    kPursuerIdleMove = D_003EC8B8;
    kPursuerMoveB = D_003EC8C8;
}

/* 0x00465470 */
void Sinit_SceneGameMembers(void) {
    D_01990700 = Room00_Cmd00_ptmf;
    D_0199070C = Room00_Cmd01_ptmf;
    Room00_CondTable = D_003EE730;
}

/* 0x004654F0 */
void Sinit_Room02(void) {
    Room02_CmdTable = Room02_Cmd00_ptmf;
    D_0199073C = Room02_Cmd01_ptmf;
    D_01990748 = Room02_Cmd02_ptmf;
    D_01990754 = Room02_Cmd03_ptmf;
    Room02_CondTable = Room02_Cond00_ptmf;
    D_0199076C = Room02_Cond01_ptmf;
}

/* 0x00465600 */
void Sinit_Room03(void) {
    Room03_CmdTable = Room03_Cmd00_ptmf;
    D_0199078C = Room03_Cmd01_ptmf;
}

/* 0x00465660 */
void Sinit_Room04(void) {
    Room04_CmdTable = Room04_Cmd00_ptmf;
    D_019907AC = Room04_Cmd01_ptmf;
    D_019907B8 = Room04_Cmd02_ptmf;
    D_019907C4 = Room04_Cmd03_ptmf;
}

/* 0x00465720 */
void Sinit_Room06(void) {
    Room06_CmdTable = Room06_Cmd00_ptmf;
}

/* 0x00465750 */
void Sinit_Room08(void) {
    Room08_CmdTable = Room08_Cmd00_ptmf;
    D_019907EC = Room08_Cmd01_ptmf;
    Room08_CondTable = Room08_Cond00_ptmf;
    D_0199080C = Room08_Cond01_ptmf;
}

/* 0x00465800 */
void Sinit_Room09(void) {
    Room09_CondTable = Room09_Cond00_ptmf;
}

/* 0x00465830 */
void Sinit_Room0A(void) {
    Room0A_CmdTable = Room0A_Cmd00_ptmf;
    D_0199083C = Room0A_Cmd01_ptmf;
}

/* 0x00465890 */
void Sinit_Room0B(void) {
    Room0B_CondTable = Room0B_Cond00_ptmf;
}

/* 0x004658C0 */
void Sinit_Room0C(void) {
    Room0C_CmdTable = Room0C_Cmd00_ptmf;
    D_0199086C = Room0C_Cmd01_ptmf;
    D_01990878 = Room0C_Cmd02_ptmf;
    D_01990884 = Room0C_Cmd03_ptmf;
}

/* 0x00465980 */
void Sinit_Room0F(void) {
    Room0F_CmdTable = Room0F_Cmd00_ptmf;
    D_0199089C = Room0F_Cmd01_ptmf;
    D_019908A8 = Room0F_Cmd02_ptmf;
    D_019908B4 = Room0F_Cmd03_ptmf;
    D_019908C0 = Room0F_Cmd04_ptmf;
}

/* 0x00465A70 */
void Sinit_Room10(void) {
    Room10_CondTable = Room10_Cond00_ptmf;
}

/* 0x00465AA0 */
void Sinit_Room12(void) {
    Room12_CmdTable = Room12_Cmd00_ptmf;
    Room12_CondTable = Room12_Cond00_ptmf;
}

/* 0x00465AF0 */
void Sinit_Room13(void) {
    Room13_CmdTable = Room13_Cmd00_ptmf;
}

/* 0x00465B20 */
void Sinit_Room14(void) {
    Room14_CmdTable = Room14_Cmd00_ptmf;
}

/* 0x00465B50 */
void Sinit_Room15(void) {
    Room15_CmdTable = Room15_Cmd00_ptmf;
    Room15_CondTable = Room15_Cond00_ptmf;
}

/* 0x00465BA0 */
void Sinit_Room18(void) {
    Room18_CmdTable = Room18_Cmd00_ptmf;
}

/* 0x00465BD0 */
void Sinit_Room19(void) {
    Room19_CondTable = Room19_Cond00_ptmf;
}

/* 0x00465C00 */
void Sinit_Room1A(void) {
    Room1A_CmdTable = Room1A_Cmd00_ptmf;
    D_0199096C = Room1A_Cmd01_ptmf;
}

/* 0x00465C60 */
void Sinit_Room1B(void) {
    Room1B_CmdTable = Room1B_Cmd00_ptmf;
}

/* 0x00465C90 */
void Sinit_Room1C(void) {
    Room1C_CmdTable = Room1C_Cmd00_ptmf;
    D_0199099C = Room1C_Cmd01_ptmf;
}

/* 0x00465CF0 */
void Sinit_Room1D(void) {
    Room1D_CmdTable = Room1D_Cmd00_ptmf;
    D_019909BC = Room1D_Cmd01_ptmf;
    Room1D_CondTable = Room1D_Cond00_ptmf;
}

/* 0x00465D70 */
void Sinit_Room1F(void) {
    Room1F_CmdTable = Room1F_Cmd00_ptmf;
}

/* 0x00465DA0 */
void Sinit_Room20(void) {
    Room20_CmdTable = Room20_Cmd00_ptmf;
    D_019909FC = Room20_Cmd01_ptmf;
    D_01990A08 = Room20_Cmd02_ptmf;
    D_01990A14 = Room20_Cmd03_ptmf;
    D_01990A20 = Room20_Cmd04_ptmf;
    D_01990A2C = Room20_Cmd05_ptmf;
    Room20_CondTable = Room20_Cond00_ptmf;
    D_01990A4C = Room20_Cond01_ptmf;
    D_01990A58 = Room20_Cond02_ptmf;
}

/* 0x00465F40 */
void Sinit_Room21(void) {
    Room21_CmdTable = Room21_Cmd00_ptmf;
    D_01990A7C = Room21_Cmd01_ptmf;
    D_01990A88 = Room21_Cmd02_ptmf;
    D_01990A94 = Room21_Cmd03_ptmf;
    D_01990AA0 = Room21_Cmd04_ptmf;
    D_01990AAC = Room21_Cmd05_ptmf;
    D_01990AB8 = Room21_Cmd06_ptmf;
    Room21_CondTable = Room21_Cond00_ptmf;
}

/* 0x004660B0 */
void Sinit_Room23(void) {
    Room23_CondTable = Room23_Cond00_ptmf;
    Room23_CmdTable = Room23_Cmd00_ptmf;
    D_01990AFC = Room23_Cmd01_ptmf;
}

/* 0x00466130 */
void Sinit_Room24(void) {
    Room24_CmdTable = Room24_KilnGlow_ptmf;
    D_01990B1C = Room24_Smoke_ptmf;
    D_01990B28 = Room24_ColourPulse_ptmf;
}

/* 0x004661C0 */
void Sinit_Room25(void) {
    Room25_CmdTable = Room25_Cmd00_ptmf;
    Room25_CondTable = Room25_Cond00_ptmf;
}

/* 0x00466210 */
void Sinit_Room26(void) {
    Room26_CondTable = Room26_Cond00_ptmf;
    Room26_CmdTable = Room26_Cmd00_ptmf;
    D_01990B7C = Room26_Cmd01_ptmf;
    D_01990B88 = Room26_Cmd02_ptmf;
}

/* 0x004662C0 */
void Sinit_Room28(void) {
    Room28_CondTable = Room28_Cond00_ptmf;
}

/* 0x004662F0 */
void Sinit_Room29(void) {
    Room29_CondTable = Room29_Cond00_ptmf;
    D_01990BBC = Room29_Cond01_ptmf;
}

/* 0x00466350 */
void Sinit_Room2A(void) {
    Room2A_CmdTable = Room2A_Cmd00_ptmf;
    D_01990BDC = Room2A_HandlerStep_ptmf;
    D_01990BE8 = Room2A_Cmd02_ptmf;
    D_01990BF4 = Room2A_Cmd03_ptmf;
}

/* 0x00466410 */
void Sinit_Room2B(void) {
    Room2B_CmdTable = Room2B_Cmd00_ptmf;
}

/* 0x00466440 */
void Sinit_Room2D(void) {
    Room2D_CmdTable = Room2D_Cmd00_ptmf;
    D_01990C1C = Room2D_Cmd01_ptmf;
    D_01990C28 = Room2D_Cmd02_ptmf;
    Room2D_CondTable = Room2D_Cond00_ptmf;
}

/* 0x004664F0 */
void Sinit_Room40(void) {
    Room40_CmdTable = Room40_Cmd00_ptmf;
}

/* 0x00466520 */
void Sinit_Room43(void) {
    Room43_CmdTable = Room43_Cmd00_ptmf;
}

/* 0x00466550 */
void Sinit_Room45(void) {
    Room45_CmdTable = Room45_Cmd00_ptmf;
}

/* 0x00466580 */
void Sinit_Room49(void) {
    Room49_CmdTable = Room49_Cmd00_ptmf;
    D_01990C8C = Room49_Cmd01_ptmf;
    D_01990C98 = Room49_Cmd02_ptmf;
}

/* 0x00466610 */
void Sinit_Room4B(void) {
    Room4B_CmdTable = Room4B_Cmd00_ptmf;
    D_01990CBC = Room4B_Cmd01_ptmf;
    Room4B_CondTable = Room4B_Cond00_ptmf;
}

/* 0x00466690 */
void Sinit_Room4C(void) {
    Room4C_CmdTable = Room4C_Cmd00_ptmf;
    D_01990CEC = Room4C_Cmd01_ptmf;
    D_01990CF8 = Room4C_Cmd02_ptmf;
}

/* 0x00466720 */
void Sinit_Room4E(void) {
    Room4E_CmdTable = Room4E_Cmd00_ptmf;
    D_01990D1C = Room4E_Cmd01_ptmf;
    D_01990D28 = Room4E_Cmd02_ptmf;
}

/* 0x004667B0 */
void Sinit_Creature(void) {
    D_01990D40 = Room4F_Cmd00_ptmf;
    D_01990D4C = Room4F_Cmd01_ptmf;
    D_01990D58 = Room4F_Cmd02_ptmf;
    D_01990D64 = Room4F_Cmd03_ptmf;
    Room4F_CondTable = Room4F_CreatureVanish_ptmf;
}

/* 0x00466890 */
void Sinit_Room50(void) {
    Room50_CmdTable = Room50_Cmd00_ptmf;
}

/* 0x004668C0 */
void Sinit_Room51(void) {
    Room51_CmdTable = Room51_Cmd00_ptmf;
    D_01990D9C = Room51_Cmd01_ptmf;
}

/* 0x00466920 */
void Sinit_Room52(void) {
    Room52_CmdTable = Room52_Cmd00_ptmf;
    Room52_CondTable = Room52_Cond00_ptmf;
}

/* 0x00466970 */
void Sinit_Room56(void) {
    Room56_CmdTable = Room56_Cmd00_ptmf;
}

/* 0x004669A0 */
void Sinit_Room59(void) {
    Room59_CmdTable = Room59_Cmd00_ptmf;
}

/* 0x004669D0 */
void Sinit_Room5A(void) {
    Room5A_CmdTable = Room5A_Cmd00_ptmf;
}

/* 0x00466A00 */
void Sinit_Room5C(void) {
    Room5C_CmdTable = Room5C_Cmd00_ptmf;
    Room5C_CondTable = Room5C_Cond00_ptmf;
}

/* 0x00466A50 */
void Sinit_Room5D(void) {
    Room5D_CmdTable = Room5D_Cmd00_ptmf;
    D_01990E2C = Room5D_Cmd01_ptmf;
}

/* 0x00466AB0 */
void Sinit_Room2F(void) {
    Room2F_CondTable = Room2F_Cond00_ptmf;
}

/* 0x00466AE0 */
void Sinit_Room30(void) {
    Room30_CondTable = Room30_Cond00_ptmf;
}

/* 0x00466B10 */
void Sinit_Debilitas3(void) {
    D_004135D0 = Debilitas3_StateNone_ptmf;
    D_004135EC = Debilitas3_StartTurnToFiona_ptmf;
    D_00413608 = Debilitas3_StartLunge_ptmf;
    D_00413624 = Debilitas3_StartGrab_ptmf;
}

/* 0x00466C30 */
void Sinit_Riccardo(void) {
    D_004148A0 = Riccardo_StartFlurry_ptmf;
    D_004148BC = Riccardo_StartLunge_ptmf;
}

/* 0x00466C90 */
void Sinit_Room46(void) {
    Room46_CmdTable = Room46_CharHook_ptmf;
    Room46_CondTable = Room46_PursuerBusy_ptmf;
}

/* 0x00466CE0 */
void Sinit_Room102(void) {
    Room102_CmdTable = Room102_Cmd00_ptmf;
}

/* 0x00466D10 */
void Sinit_Room103(void) {
    Room103_CmdTable = Room103_Cmd00_ptmf;
}

/* 0x00466D40 */
void Sinit_Room104(void) {
    Room104_CmdTable = Room104_Cmd00_ptmf;
}

/* 0x00466D70 */
void Sinit_Room105(void) {
    Room105_CmdTable = Room105_Cmd00_ptmf;
}

/* 0x00466DA0 */
void Sinit_Room106(void) {
    Room106_CmdTable = Room106_Cmd00_ptmf;
}

/* 0x00466DD0 */
void Sinit_Room107(void) {
    Room107_CondTable = Room107_Cond00_ptmf;
    Room107_CmdTable = Room107_Cmd00_ptmf;
    D_01990F0C = Room107_Cmd01_ptmf;
}

/* 0x00466E50 */
void Sinit_Room108(void) {
    Room108_CmdTable = Room108_Cmd00_ptmf;
}

/* 0x00466E80 */
void Sinit_Room109(void) {
    Room109_CmdTable = Room109_Cmd00_ptmf;
    D_01990F3C = Room109_Cmd01_ptmf;
}

/* 0x00466EE0 */
void Sinit_Room10A(void) {
    Room10A_CondTable = Room10A_Cond00_ptmf;
    Room10A_CmdTable = Room10A_Cmd00_ptmf;
}

/* 0x00466F30 */
void Sinit_Room10B(void) {
    Room10B_CmdTable = Room10B_Cmd00_ptmf;
    Room10B_CondTable = Room10B_Cond00_ptmf;
}

/* 0x00466F80 */
void Sinit_Debilitas2(void) {
    D_0041B670 = Room_EmptyHook_ptmf;
    D_0041B68C = D_0041B640;
    D_0041B6A8 = D_0041B650;
    D_0041B6C4 = D_0041B660;
}

/* 0x00467040 */
void Sinit_Room27(void) {
    Room27_CmdTable = Room27_Cmd00_ptmf;
}

/* 0x00467070 */
void Sinit_Room2E(void) {
    Room2E_CmdTable = Room2E_Cmd00_ptmf;
    D_01990FFC = Room2E_Cmd01_ptmf;
    D_01991008 = Room2E_Cmd02_ptmf;
    D_01991014 = Room2E_Cmd03_ptmf;
    D_01991020 = Room2E_Cmd04_ptmf;
}

/* 0x00467160 */
void Sinit_Room66(void) {
    Room66_CmdTable = Room66_CharHook_ptmf;
    D_0199103C = Room66_Effect_ptmf;
    D_01991048 = Room66_Sink_ptmf;
    D_01991054 = Room66_Fire_ptmf;
    D_01991060 = Room66_ColourPulse_ptmf;
    Room66_CondTable = Room66_Letters_ptmf;
    D_0199107C = Room66_CharPast_ptmf;
}

/* 0x004672A0 */
void Sinit_Room55(void) {
    Room55_CmdTable = Room55_Effect_ptmf;
}

/* 0x004672D0 */
void Sinit_Room63(void) {
    Room63_CmdTable = Room63_Cmd00_ptmf;
}

/* 0x00467300 */
void Sinit_Room62(void) {
    Room62_CmdTable = Room62_Cmd00_ptmf;
    D_019910BC = Room62_Cmd01_ptmf;
}

/* 0x00467360 */
void Sinit_Lorenzo(void) {
    D_00422690 = Lorenzo2_StartSink_ptmf;
    D_004226AC = Lorenzo2_StartStalkBelow_ptmf;
    D_004226C8 = Lorenzo2_StartGrab_ptmf;
}

/* 0x004673F0 */
void Sinit_Room48(void) {
    Room48_CmdTable = Room48_Cmd00_ptmf;
    D_0199114C = Room48_Cmd01_ptmf;
    D_01991158 = Room48_Cmd02_ptmf;
    D_01991164 = Room48_Cmd03_ptmf;
    D_01991170 = Room48_Cmd04_ptmf;
    D_0199117C = Room48_Cmd05_ptmf;
    Room48_CondTable = Room48_Cond00_ptmf;
}

/* 0x00467530 */
void Sinit_Room54(void) {
    Room54_CmdTable = Room54_GroupStep_ptmf;
    D_019911AC = Room54_DoorRegions_ptmf;
}

/* 0x00467590 */
void Sinit_Room60(void) {
    Room60_CmdTable = Room60_Cmd00_ptmf;
    D_019911CC = Room60_Cmd01_ptmf;
    D_019911D8 = Room60_Cmd02_ptmf;
    D_019911E4 = Room60_Cmd03_ptmf;
    D_019911F0 = Room60_Cmd04_ptmf;
    D_019911FC = Room60_Cmd05_ptmf;
}

/* 0x004676B0 */
void Sinit_Room61(void) {
    Room61_CmdTable = Room61_Cmd00_ptmf;
    D_0199155C = Room61_Cmd01_ptmf;
}

/* 0x00467710 */
void Sinit_Room31(void) {
    Room31_CmdTable = Room31_RoomEffect_ptmf;
    D_0199157C = Room31_Fan_ptmf;
    D_01991588 = Room31_WindowLight_ptmf;
}

/* 0x004677A0 */
void Sinit_Room32(void) {
    Room32_CmdTable = Room32_Cmd00_ptmf;
    D_019915AC = Room32_Cmd01_ptmf;
    D_019915B8 = Room32_Cmd02_ptmf;
    D_019915C4 = Room32_Cmd03_ptmf;
    D_019915D0 = Room32_Cmd04_ptmf;
    D_019915DC = Room32_Cmd05_ptmf;
}

/* 0x004678C0 */
void Sinit_Room86(void) {
    Room86_CmdTable = Room86_Cmd00_ptmf;
}

/* 0x004678F0 */
void Sinit_RoomC0(void) {
    RoomC0_CmdTable = RoomC0_Cmd00_ptmf;
    D_0199161C = RoomC0_Cmd01_ptmf;
    D_01991628 = RoomC0_Cmd02_ptmf;
    D_01991634 = RoomC0_Cmd03_ptmf;
    D_01991640 = RoomC0_Cmd04_ptmf;
    RoomC0_CondTable = RoomC0_Cond00_ptmf;
}

/* 0x00467A00 */
void Sinit_Debilitas3_2(void) {
    D_0042E540 = Kind27_StateNone_ptmf;
    D_0042E55C = Kind27_StartTurnToFiona_ptmf;
    D_0042E578 = Kind27_StartLunge_ptmf;
    D_0042E594 = Kind27_StartGrab_ptmf;
}

/* 0x00467AC0 */
void Sinit_RoomC7(void) {
    RoomC7_CmdTable = RoomC7_Cmd00_ptmf;
    D_0199166C = RoomC7_Cmd01_ptmf;
    D_01991678 = RoomC7_Cmd02_ptmf;
    D_01991684 = RoomC7_Cmd03_ptmf;
    D_01991690 = RoomC7_Cmd04_ptmf;
    D_0199169C = RoomC7_Cmd05_ptmf;
    D_019916A8 = RoomC7_Cmd06_ptmf;
    RoomC7_CondTable = RoomC7_Cond00_ptmf;
    D_019916CC = RoomC7_Cond01_ptmf;
}

/* 0x00467C60 */
void Sinit_Room84(void) {
    Room84_CmdTable = Room84_Cmd00_ptmf;
}

/* 0x00467C90 */
void Sinit_Room85(void) {
    Room85_CmdTable = Room85_Cmd00_ptmf;
}

/* 0x00467CC0 */
void Sinit_Room87(void) {
    Room87_CmdTable = Room87_Cmd00_ptmf;
}

/* 0x00467CF0 */
void Sinit_Room88(void) {
    Room88_CmdTable = Room88_Cmd00_ptmf;
}

/* 0x00467D20 */
void Sinit_Room8C(void) {
    Room8C_CmdTable = Room8C_Cmd00_ptmf;
    D_0199172C = Room8C_Cmd01_ptmf;
    D_01991738 = Room8C_Cmd02_ptmf;
    D_01991744 = Room8C_Cmd03_ptmf;
    D_01991750 = Room8C_Cmd04_ptmf;
}

/* 0x00467E10 */
void Sinit_Room8D(void) {
    Room8D_CmdTable = Room8D_Cmd00_ptmf;
    D_0199176C = Room8D_Cmd01_ptmf;
    D_01991778 = Room8D_Cmd02_ptmf;
}

/* 0x00467EA0 */
void Sinit_Room8E(void) {
    Room8E_CmdTable = Room8E_Cmd00_ptmf;
    D_0199179C = Room8E_Cmd01_ptmf;
}

/* 0x00467F00 */
void Sinit_Room8F(void) {
    Room8F_CmdTable = Room8F_Cmd00_ptmf;
    D_019917BC = Room8F_Cmd01_ptmf;
    D_019917C8 = Room8F_Cmd02_ptmf;
    D_019917D4 = Room8F_Cmd03_ptmf;
    Room8F_CondTable = Room8F_Cond00_ptmf;
}

/* 0x00467FE0 */
void Sinit_Room91(void) {
    Room91_CmdTable = Room91_Cmd00_ptmf;
    D_019917FC = Room91_Cmd01_ptmf;
    D_01991808 = Room91_Cmd02_ptmf;
    D_01991814 = Room91_Cmd03_ptmf;
}

/* 0x004680A0 */
void Sinit_Room92(void) {
    Room92_CmdTable = Room92_Cmd00_ptmf;
    D_0199182C = Room92_Cmd01_ptmf;
    D_01991838 = Room92_Cmd02_ptmf;
    D_01991844 = Room92_Cmd03_ptmf;
    D_01991850 = Room92_Cmd04_ptmf;
    D_0199185C = Room92_Cmd05_ptmf;
    D_01991868 = Room92_Cmd06_ptmf;
    D_01991874 = Room92_Cmd07_ptmf;
    D_01991880 = Room92_Cmd08_ptmf;
    D_0199188C = Room92_Cmd09_ptmf;
    D_01991898 = Room92_Cmd10_ptmf;
    D_019918A4 = Room92_Cmd11_ptmf;
    D_019918B0 = Room92_Cmd12_ptmf;
    D_019918BC = Room92_Cmd13_ptmf;
}

/* 0x00468340 */
void Sinit_Room97(void) {
    Room97_CmdTable = Room97_Cmd00_ptmf;
}

/* 0x00468370 */
void Sinit_Room69(void) {
    Room69_CmdTable = Room69_Cmd00_ptmf;
}

/* 0x004683A0 */
void Sinit_Room6A(void) {
    Room6A_CmdTable = Room6A_Cmd00_ptmf;
    D_019918FC = Room6A_Cmd01_ptmf;
}

/* 0x00468400 */
void Sinit_Room6C(void) {
    Room6C_CondTable = Room6C_Cond00_ptmf;
    D_0199191C = Room6C_Cond01_ptmf;
}

/* 0x00468460 */
void Sinit_Room6D(void) {
    Room6D_CondTable = Room6D_Cond00_ptmf;
    D_0199193C = Room6D_Cond01_ptmf;
}

/* 0x004684C0 */
void Sinit_Room6F(void) {
    Room6F_CmdTable = Room6F_Cmd00_ptmf;
    Room6F_CondTable = Room6F_Cond00_ptmf;
}

/* 0x00468510 */
void Sinit_Room80(void) {
    Room80_CmdTable = Room80_Cmd00_ptmf;
}

/* 0x00468540 */
void Sinit_RoomC1(void) {
    RoomC1_CondTable = RoomC1_Cond00_ptmf;
}

/* 0x00468570 */
void Sinit_RoomC2(void) {
    RoomC2_CmdTable = RoomC2_Cmd00_ptmf;
    D_0199199C = RoomC2_Cmd01_ptmf;
    RoomC2_CondTable = RoomC2_Cond00_ptmf;
}

/* 0x004685F0 */
void Sinit_RoomC3(void) {
    RoomC3_CmdTable = RoomC3_Cmd00_ptmf;
    D_019919CC = RoomC3_Cmd01_ptmf;
    D_019919D8 = RoomC3_Cmd02_ptmf;
    RoomC3_CondTable = RoomC3_Cond00_ptmf;
}

/* 0x004686A0 */
void Sinit_RoomC5(void) {
    RoomC5_CmdTable = RoomC5_Cmd00_ptmf;
}

/* 0x004686D0 */
void Sinit_RoomC8(void) {
    RoomC8_CmdTable = RoomC8_Cmd00_ptmf;
}

/* 0x00468700 */
void Sinit_Room98(void) {
    Room98_CmdTable = Room98_SlamShake_ptmf;
}

/* 0x00468730 */
void Sinit_Room99(void) {
    Room99_CmdTable = Room99_SlamShake_ptmf;
}

/* 0x00468760 */
void Sinit_Room9A(void) {
    Room9A_CmdTable = Room9A_Cmd00_ptmf;
}

/* 0x00468790 */
void Sinit_Room9B(void) {
    Room9B_CmdTable = Room9B_Cmd00_ptmf;
}

/* 0x004687C0 */
void Sinit_Room93(void) {
    Room93_CmdTable = Room93_SlamShake_ptmf;
}

/* 0x004687F0 */
void Sinit_Room94(void) {
    Room94_CmdTable = Room94_Cmd00_ptmf;
}

/* 0x00468820 */
void Sinit_Room95(void) {
    Room95_CmdTable = Room95_Cmd00_ptmf;
}

/* 0x00468850 */
void Sinit_Room96(void) {
    Room96_CmdTable = Room96_Cmd00_ptmf;
}

/* 0x00468880 */
void Sinit_Lorenzo_2(void) {
    D_00444CE0 = Kind39_StartSink_ptmf;
    D_00444CFC = Kind39_StartStalkBelow_ptmf;
    D_00444D18 = Kind39_StartGrab_ptmf;
}

/* 0x00468910 */
void Sinit_Room37(void) {
    Room37_CmdTable = Room37_Fan_ptmf;
}

/* 0x00468940 */
void Sinit_RoomD0(void) {
    RoomD0_CmdTable = RoomD0_ClockStop_ptmf;
    D_01991ACC = RoomD0_ClockSave_ptmf;
    D_01991AD8 = RoomD0_ClockDrawSaved_ptmf;
    RoomD0_CondTable = RoomD0_ProgressCall_ptmf;
}

/* 0x004689F0 */
void Sinit_RoomD1(void) {
    RoomD1_CmdTable = RoomD1_Cmd00_ptmf;
    D_01991B0C = RoomD1_Cmd01_ptmf;
    RoomD1_CondTable = RoomD1_Cond00_ptmf;
}

/* 0x00468A70 */
void Sinit_RoomD2(void) {
    RoomD2_CmdTable = RoomD2_Cmd00_ptmf;
    RoomD2_CondTable = RoomD2_Cond00_ptmf;
}

/* 0x00468AC0 */
void Sinit_RoomD3(void) {
    RoomD3_CmdTable = RoomD3_Cmd00_ptmf;
    RoomD3_CondTable = RoomD3_Cond00_ptmf;
}

/* 0x00468B10 */
void Sinit_RoomD4(void) {
    RoomD4_CmdTable = RoomD4_Cmd00_ptmf;
    RoomD4_CondTable = RoomD4_Cond00_ptmf;
}

/* 0x00468B60 */
void Sinit_RoomD5(void) {
    RoomD5_CmdTable = RoomD5_Cmd00_ptmf;
    D_01991B9C = RoomD5_Cmd01_ptmf;
    D_01991BA8 = RoomD5_Cmd02_ptmf;
    RoomD5_CondTable = RoomD5_Cond00_ptmf;
}

/* 0x00468C10 */
void Sinit_RoomD6(void) {
    RoomD6_CmdTable = RoomD6_Cmd00_ptmf;
    D_01991BDC = RoomD6_Cmd01_ptmf;
    RoomD6_CondTable = RoomD6_Cond00_ptmf;
}

/* 0x00468C90 */
void Sinit_RoomD7(void) {
    RoomD7_CondTable = D_00447B70;
    D_01991C0C = RoomD7_Cond01_ptmf;
    RoomD7_CmdTable = RoomD7_Cmd00_ptmf;
    D_01991C2C = RoomD7_Cmd01_ptmf;
    D_01991C38 = RoomD7_Cmd02_ptmf;
}

/* 0x00468D70 */
void Sinit_RoomD8(void) {
    RoomD8_CondTable = D_00447E20;
    D_01991C5C = RoomD8_Cond01_ptmf;
    RoomD8_CmdTable = RoomD8_Cmd00_ptmf;
    D_01991C7C = RoomD8_Cmd01_ptmf;
}

/* 0x00468E20 */
void Sinit_RoomD9(void) {
    RoomD9_CmdTable = RoomD9_Cmd00_ptmf;
    D_01991C9C = RoomD9_Cmd01_ptmf;
    D_01991CA8 = RoomD9_Cmd02_ptmf;
    RoomD9_CondTable = RoomD9_Cond00_ptmf;
}

/* 0x00468ED0 */
void Sinit_RoomE0(void) {
    RoomE0_CmdTable = RoomE0_ClockStart_ptmf;
    D_01991CDC = RoomE0_Fan_ptmf;
    D_01991CE8 = RoomE0_WindowLight_ptmf;
    D_01991CF4 = RoomE0_DoorLight_ptmf;
    D_01991D00 = RoomE0_ClockDraw_ptmf;
    D_01991D0C = RoomE0_ChooseExit_ptmf;
    RoomE0_CondTable = RoomE0_ProgressCall_ptmf;
}

/* 0x00469010 */
void Sinit_RoomE1(void) {
    RoomE1_CmdTable = RoomE1_Cmd00_ptmf;
    RoomE1_CondTable = RoomE1_Cond00_ptmf;
}

/* 0x00469060 */
void Sinit_RoomE2(void) {
    RoomE2_CmdTable = RoomE2_Cmd00_ptmf;
    RoomE2_CondTable = RoomE2_Cond00_ptmf;
}

/* 0x004690B0 */
void Sinit_RoomE3(void) {
    RoomE3_CmdTable = RoomE3_Cmd00_ptmf;
    RoomE3_CondTable = RoomE3_Cond00_ptmf;
}

/* 0x00469100 */
void Sinit_RoomE4(void) {
    RoomE4_CmdTable = RoomE4_Cmd00_ptmf;
    D_01991D9C = RoomE4_Cmd01_ptmf;
    RoomE4_CondTable = RoomE4_Cond00_ptmf;
}

/* 0x00469180 */
void Sinit_RoomE5(void) {
    RoomE5_CmdTable = RoomE5_Cmd00_ptmf;
    D_01991DCC = RoomE5_Cmd01_ptmf;
    RoomE5_CondTable = RoomE5_Cond00_ptmf;
}

/* 0x00469200 */
void Sinit_RoomE6(void) {
    RoomE6_CmdTable = RoomE6_Cmd00_ptmf;
    D_01991DFC = RoomE6_Cmd01_ptmf;
    RoomE6_CondTable = RoomE6_Cond00_ptmf;
}

/* 0x00469280 */
void Sinit_RoomE7(void) {
    RoomE7_CmdTable = RoomE7_Cmd00_ptmf;
    RoomE7_CondTable = RoomE7_Cond00_ptmf;
}

/* 0x004692D0 */
void Sinit_RoomE8(void) {
    RoomE8_CmdTable = RoomE8_Cmd00_ptmf;
    RoomE8_CondTable = RoomE8_Cond00_ptmf;
}

/* 0x00469320 */
void Sinit_RoomE9(void) {
    RoomE9_CmdTable = RoomE9_Cmd00_ptmf;
    D_01991E6C = RoomE9_Cmd01_ptmf;
    D_01991E78 = RoomE9_Cmd02_ptmf;
    D_01991E84 = RoomE9_Cmd03_ptmf;
    RoomE9_CondTable = RoomE9_Cond00_ptmf;
}

/* ---- hand-written ---- */

#include "game.h"

/* MW guard flags for function-level statics (set once). */
extern s8 D_0047B9A8, D_0047B9B0, D_0047BA10, D_0047BA18;

void func_00464480(void) {
    if (!D_0047B9A8) {
        D_0047B9A8 = 1;
    }
    if (!D_0047B9B0) {
        D_0047B9B0 = 1;
    }
}

/* A table of 16-bit values in .data (0x003AC932..0x003ACA1E, purpose unknown) set at startup. */
extern u8 D_003AC932[];

static void fill16(u32 addr, s32 n, u16 v) {
    u16 *p = (u16 *)(D_003AC932 + (addr - 0x003AC932));

    while (n-- > 0) {
        *p++ = v;
    }
}

void func_004644D0(void) {
    fill16(0x003AC932, 1, 0x106);
    fill16(0x003AC934, 4, 0x104);
    fill16(0x003AC960, 1, 0x142);
    fill16(0x003AC962, 15, 0xD0);
    fill16(0x003AC980, 10, 0x458);
    fill16(0x003AC994, 7, 0xD0);
    fill16(0x003AC9A2, 6, 0x651);
    fill16(0x003AC9AE, 20, 0x251);
    fill16(0x003AC9D6, 6, 0xD0);
    fill16(0x003AC9E2, 6, 0x471);
    fill16(0x003AC9EE, 20, 0x71);
    fill16(0x003ACA16, 4, 0xD0);
    if (!D_0047BA10) {
        D_0047BA10 = 1;
    }
    if (!D_0047BA18) {
        D_0047BA18 = 1;
    }
}

/* MSL runtime (C++ library, replaced on PC): iostream init objects and the atexit-style list
 * of global objects to destroy. */
extern void func_001030B0(void *, s32), func_00103620(void *, s32);                      /* their destructors */

static inline void Sinit_Iostreams(void *a, void *alink, void *b, void *blink) {
    func_00102D80(a);
    func_00100AB0(a, func_001030B0, alink);
    func_001032F0(b);
    func_00100AB0(b, func_00103620, blink);
}

extern u8 D_0047B210[], D_0047B214[], D_004879C8[], D_004879D8[], D_004879E8[];
extern u8 D_0047B26C[], D_0047B270[], D_01990E58[], D_01990E68[];
extern u8 D_0047B348[], D_0047B34C[], D_01991EA0[], D_01991EB0[];

extern Game gGame;
extern void *Game_vtable[];
extern const PTMF Game_Init_ptmf;    /* Game's first state */

/* gGame's constructor. */
void func_00464A70(void) {
    u8 *g = (u8 *)&gGame;

    Sinit_Iostreams(D_0047B210, D_004879C8, D_0047B214, D_004879D8);
    GameBase_ctor(&gGame);
    gGame.vtbl = Game_vtable;
    System_ctor((u8 *)&gGame.unk69AC0);
    Random_ctor((VObject *)(g + 0x400000), 0x1571);
    SceneTable_ctor(g + 0x400A00);
    Camera_ctor((VObject *)(g + 0x14D9B00));
    SmallPool_ctor(g + 0x14D9DD0);
    BigPool_ctor(g + 0x14DC530);
    Slots_ctor(gGame.unk14E8C90);
    Game_SetState(&gGame, &Game_Init_ptmf);
    func_00100AB0(&gGame, (void (*)(void *, s32))Game_dtor, D_004879E8);
}

void func_00466BD0(void) {
    Sinit_Iostreams(D_0047B26C, D_01990E58, D_0047B270, D_01990E68);
}

void func_00469400(void) {
    Sinit_Iostreams(D_0047B348, D_01991EA0, D_0047B34C, D_01991EB0);
}
