#!/usr/bin/env python3
"""Placeholder names for the rooms, from the pause screen's maps: the map page a room is on
(its title: "Belli Castle: 1F" -> castle-1f) and its place in that page's list (castle-1f-4).
A room on several pages (stairs) takes its first. Writes scripts/room-names.fs.

The names are placeholders until someone walks the game and names the rooms for what they are
(edit them in place: the tool won't be run again once they are).

usage: roomnames.py [repo root]   (needs baserom/SLUS_210.75 and the game data for the titles)"""
import os
import re
import struct
import subprocess
import sys

here = os.path.dirname(os.path.abspath(__file__))
root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, '..', '..')
elf = open(os.path.join(root, 'baserom', 'SLUS_210.75'), 'rb').read()
phoff, = struct.unpack_from('<I', elf, 0x1C)
phnum, = struct.unpack_from('<H', elf, 0x2C)
segs = []
for i in range(phnum):
    t, off, va, _, fs = struct.unpack_from('<5I', elf, phoff + i * 32)
    if t == 1:
        segs.append((va, off, fs))


def at(va):
    for s, off, fs in segs:
        if s <= va < s + fs:
            return off + va - s
    raise ValueError(hex(va))


def u32(va): return struct.unpack_from('<I', elf, at(va))[0]
def s32(va): return struct.unpack_from('<i', elf, at(va))[0]
def u16(va): return struct.unpack_from('<H', elf, at(va))[0]


MAP_ROOMS, MAP_TITLES = 0x420B20, 0x41F8B0   # kMapRooms, the pages' title messages (subscreen.c)

# the titles: sub-screen messages (0x4000 + id), read through the game itself
pages = []   # (map, page, title id, rooms)
for m in range(16):
    p = u32(MAP_ROOMS + 4 * m)
    if p == 0:
        break
    by_page = {}
    while s32(p) != -1:
        by_page.setdefault(s32(p + 4), []).append(s32(p))
        p += 0x18
    titles = u32(MAP_TITLES + 4 * m)
    for pg in sorted(by_page):
        pages.append((m, pg, u16(titles + 2 * pg), by_page[pg]))

hga = os.path.join(root, 'build', 'new-src-actors', 'hga')
code = (': t ( id -- ) message-layout 0 0 message-line type ." |" ; '
        + ' '.join('$%X t' % (0x4000 + t) for _, _, t, _ in pages) + ' cr')
out = subprocess.run([hga, '--hidden', '--frames', '1', '--eval', code], capture_output=True, text=True).stdout
line = [l for l in out.splitlines() if l.count('|') >= len(pages)][-1]
titles = [s.strip() for s in line.split('|')[:len(pages)]]


def slug(title):
    t = title.replace('Belli Castle: Old Mansion', 'Old Mansion').replace('Belli Castle: ', 'Castle ')
    t = t.replace('Castle Front Garden', 'Front Garden')
    return re.sub(r'[^a-z0-9]+', '-', t.lower()).strip('-')


named = {}
lines = []
for (m, pg, tid, rooms), title in zip(pages, titles):
    n = 0
    for r in rooms:
        if r in named:
            continue
        n += 1
        named[r] = '%s-%d' % (slug(title), n)
        lines.append((r, named[r], title))

with open(os.path.join(here, '..', 'scripts', 'room-names.fs'), 'w') as f:
    f.write('\\ room-names.fs - the rooms by name (generated by tools/roomnames.py). Placeholders: the\n'
            '\\ area of the pause screen\'s map a room is on and its place in that page\'s list. Rename them\n'
            '\\ for what they are as they are walked (and keep the comment with the area).\n'
            'IN: room-names\n\n')
    for r, name, title in sorted(lines):
        f.write('$%-4X constant %-24s \\ %s\n' % (r, name, title))
    f.write('\n\\ a room\'s name, for the console and traces ("unnamed-room": not on any map)\n'
            ': room-name ( room -- addr len )\n    case\n')
    for r, name, _ in sorted(lines):
        f.write('        $%X of  s" %s"  endof\n' % (r, name))
    f.write('        >r  s" unnamed-room"  r>\n    endcase ;\n')
print('%d rooms named' % len(lines))
