#!/usr/bin/env python3
"""The rooms' search spots and exit goals read from the executable into
scripts/stalker/spots.fs. A room's event class (src/game/rooms/room_XX.c) gives the stalkers
two tables: +0x38 (RoomXX_Table38_data) up to 8 triangles he searches in that room (-1 ends
them; Pursuer_AddSearchStops, Pursuer_SearchRouteIn), +0x3C (RoomXX_Table3C_data) by exit the
room he heads for past it (Npc_PlanToRoomObject; only rooms $02 and $20 have one).

usage: searchspots.py [repo root]"""
import os
import re
import struct
import sys

root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', '..')
elf = open(os.path.join(root, 'baserom', 'SLUS_210.75'), 'rb').read()
syms, addrs = {}, []
for line in open(os.path.join(root, 'config', 'symbol_addrs.txt')):
    m = re.match(r'\s*(\w+)\s*=\s*0x([0-9A-Fa-f]+);', line)
    if m:
        syms[m.group(1)] = int(m.group(2), 16)
        addrs.append(int(m.group(2), 16))
addrs.sort()
e_phoff, = struct.unpack_from('<I', elf, 0x1C)
e_phnum, = struct.unpack_from('<H', elf, 0x2C)
segs = [struct.unpack_from('<5I', elf, e_phoff + i * 32)[1:] for i in range(e_phnum)]
segs = [(vaddr, off, filesz) for off, vaddr, _, filesz in segs]


def s32(va):
    for vaddr, off, size in segs:
        if vaddr <= va and va + 4 <= vaddr + size:
            return struct.unpack_from('<i', elf, off + va - vaddr)[0]
    return None


def next_sym(va):
    return min((a for a in addrs if a > va), default=va + 32)


names = {}
for line in open(os.path.join(os.path.dirname(__file__), '..', 'scripts', 'room-names.fs')):
    m = re.match(r'\$([0-9A-Fa-f]+)\s+constant\s+(\S+)', line)
    if m:
        names[int(m.group(1), 16)] = m.group(2)


def table(va, stop_at_end):
    out, end = [], next_sym(va)
    while len(out) < 8 and va + 4 * len(out) < end:
        v = s32(va + 4 * len(out))
        if stop_at_end and v == -1:
            break
        out.append(v)
    return out


spots, goals = {}, {}
for sym, va in syms.items():
    m = re.match(r'Room([0-9A-F]+)_Table(38|3C)_data$', sym)
    if not m:
        continue
    room = int(m.group(1), 16)
    if m.group(2) == '38':
        spots[room] = table(va, True)
    else:
        goals[room] = table(va, False)


def name(r):
    return names.get(r, '$%X' % r)


out = ['\\ stalker/spots.fs - generated by tools/searchspots.py: each room\'s search spots (the',
       '\\ triangles a stalker searches there, RoomXX_Table38_data) and, by exit, the room he heads',
       '\\ for past it (RoomXX_Table3C_data).',
       'IN: stalker.spots', 'USING: room-names ;', '']
for r in sorted(spots):
    out.append('create spots-%X %s' % (r, ' '.join('%d ,' % t for t in spots[r])))
out += ['', ': search-spots ( room -- addr n )   \\ (none: 0 0)', '    case']
for r in sorted(spots):
    out.append('        %s of  spots-%X %d  endof' % (name(r), r, len(spots[r])))
out += ['        >r 0 0 r>', '    endcase ;', '']
for r in sorted(goals):
    out.append('create goals-%X %s' % (r, ' '.join('%d ,' % t for t in goals[r])))
out += [': exit-goal ( exit room -- room | -1 )', '    case']
for r in sorted(goals):
    out.append('        %s of  dup %d u< if  cells goals-%X + @  else  drop -1  then  endof' % (name(r), len(goals[r]), r))
out += ['        >r drop -1 r>', '    endcase ;', '']
open(os.path.join(os.path.dirname(__file__), '..', 'scripts', 'stalker', 'spots.fs'), 'w').write('\n'.join(out))
print(len(spots), 'rooms with spots,', len(goals), 'with goals')
