#!/usr/bin/env python3
"""A stalker's tables read from the executable into scripts/stalker/tables.fs (src/game/debilitas.c
Debilitas_Setup / Debilitas_AttackTable): what he does in each situation (34 tables - 17, then
the hard setting's 17: rows of a kind, an argument and a running percentage), his combos (4 move
numbers, -1 ends), his moves (0x24 each: animation, the striking bone and a second, reach, kind,
damage, threat, stumble chance, turning with it, its cry), his gestures (animation, a flag), his
chase table (frames and chances) and the chances of a lunge by how near she is.

usage: stalkertables.py [repo root]"""
import os
import struct
import sys

root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', '..')
elf = open(os.path.join(root, 'baserom', 'SLUS_210.75'), 'rb').read()
ph, = struct.unpack_from('<I', elf, 0x1C)
n, = struct.unpack_from('<H', elf, 0x2C)
segs = [struct.unpack_from('<5I', elf, ph + i * 32)[1:] for i in range(n)]


def rd(va, fmt):
    for off, vaddr, _, size in segs:
        if vaddr <= va < vaddr + size:
            return struct.unpack_from(fmt, elf, off + va - vaddr)
    raise ValueError(hex(va))


def f(x):
    return ('%ge' % x) if 'e' not in ('%g' % x) else '%g' % x


# Debilitas (Debilitas_AttackTable's list, its +0x171C moves, +0x1724 combos, +0x1720 gestures,
# +0x17F0 chase table, Pursuer_ThresholdEntry's D_003AF4B0)
TABLES = [0x3AF780, 0x3AF800, 0x3AF7C0, 0x3AF840, 0x3AF880, 0x3AF8A0, 0x3AF8C0, 0x3AF900, 0x3AF930,
          0x3AF978, 0x3AF990, 0x3AF9D0, 0x3AF9E0, 0x3AFA10, 0x3AFA70, 0x3AFA80, 0x3AFA40,
          0x3AFBA0, 0x3AFC40, 0x3AFBF0, 0x3AFC80, 0x3AFCB0, 0x3AFCF0, 0x3AFD10, 0x3AFD50, 0x3AFD80,
          0x3AFDC0, 0x3AFDD0, 0x3AFE00, 0x3AFE10, 0x3AFE50, 0x3AFED0, 0x3AFEE0, 0x3AFEA0]
MOVES, NMOVES = 0x3AF4D0, 14
COMBOS, NCOMBOS = 0x3AF730, 16
GESTURES, NGESTURES = 0x3AF6F0, 8
CHASE = 0x3AFB70
LUNGE = 0x3AF4B0

out = ['\\ stalker/tables.fs - generated by tools/stalkertables.py: Debilitas\'s tables from the',
       '\\ executable (src/game/debilitas.c). Rows: kind, argument, running percentage (0..100).',
       'IN: stalker.tables', 'USING: engine ;', '']
for i, t in enumerate(TABLES):
    rows = []
    while True:
        k, a, p = rd(t + 12 * len(rows), '<iif')
        rows.append('$%X , %d , %s f,' % (k, a, f(p)))
        if p >= 100 or len(rows) >= 12:
            break
    out.append('create table-%d  %s' % (i, '  '.join(rows)))
out.append('create tables  ' + ' '.join('table-%d ,' % i for i in range(len(TABLES))))
out.append(': table ( situation hard? -- addr )  if  17 +  then  cells tables + @ ;')
out.append('3 cells constant /row   \\ (kind, argument, percentage: a cell each)')
out.append('')
out.append('\\ his moves: animation, bone, second bone (-1 none), reach, kind (2 a blow, 4 a hard one,')
out.append('\\ 3 a seize, 6 a hold), damage, threat, stumble chance, turns with it, cry (-1 none),')
out.append('\\ unshaken (a shove doesn\'t make him flinch during it)')
out.append('11 cells constant /move')
rows = []
for m in range(NMOVES):
    b = MOVES + 0x24 * m
    anim, bone, bone2, reach = rd(b, '<iiif')
    kind, = rd(b + 0x10, '<B')
    dmg, = rd(b + 0x12, '<h')
    thr, stum = rd(b + 0x14, '<ff')
    turn, held = rd(b + 0x1C, '<BB')
    cry, = rd(b + 0x20, '<i')
    rows.append('    $%X , $%X , %d , %s f, %d , %d , %s f, %s f, %d , %s ,' % (anim, bone, bone2, f(reach), kind, dmg, f(thr), f(stum), turn, ('$%X' % cry) if cry >= 0 else '-1') + ' %d ,' % held)
out.append('create moves\n' + '\n'.join(rows))
out.append('create combos  ' + '  '.join(' '.join('%d ,' % x for x in rd(COMBOS + 4 * c, '<4b')) for c in range(NCOMBOS)))
out.append('create gestures  ' + '  '.join('$%X , %d ,' % rd(GESTURES + 8 * g, '<iI') for g in range(NGESTURES)))
out.append('')
out.append('\\ his chase table (+0x17F0): frames by offset 0..$20, chances at $24 $28 $2C')
out.append('create chase-frames  ' + ' '.join('%d ,' % rd(CHASE + 4 * i, '<i')[0] for i in range(9)))
out.append('create chase-chances  ' + ' '.join('%s f,' % f(rd(CHASE + 0x24 + 4 * i, '<f')[0]) for i in range(3)))
out.append('\\ a lunge\'s chance by how near she is (Pursuer_ThresholdEntry): within, chance')
out.append('create lunge-chances  ' + '  '.join('%s f, %d ,' % (f(a), b) for a, b in (rd(LUNGE + 8 * i, '<fi') for i in range(3))))
out.append('')
open(os.path.join(os.path.dirname(__file__), '..', 'scripts', 'stalker', 'tables.fs'), 'w').write('\n'.join(out))
print('written')
