#!/usr/bin/env python3
"""The story's words not written yet: a stub for each word the rooms' scripts use that
scripts/story/words.fs doesn't define above its marker line. Each takes its arguments (by the
stack comment of the old new-src's definition), says once that it isn't written yet, and gives
false / zero. Rewrites everything below the marker in scripts/story/words.fs.

A waiting word's stub still waits a frame (a script looping on it gives up its turn).

Run again whenever words are written: their stubs go.

usage: story_stubs.py   (from new-src-actors/)"""
import glob
import os
import re

here = os.path.dirname(os.path.abspath(__file__))
top = os.path.join(here, '..')
old = os.path.join(top, '..', 'new-src', 'scripts', 'events')
MARK = '\\ ==== not written yet (generated by tools/story_stubs.py: keep below this line) ===='


def code_tokens(text):
    out = []
    for line in text.split('\n'):
        line = re.sub(r'(^|\s)\\(\s.*)?$', ' ', line)   # line comments
        line = re.sub(r'\s\(\s[^)]*\)', ' ', ' ' + line)  # stack comments
        line = re.sub(r'(s|\.)"\s[^"]*"', ' ', line)       # strings
        out += line.split()
    return out


# what the scripts use
used = set()
for f in glob.glob(os.path.join(top, 'scripts', 'story', 'rooms', '*.fs')) + [os.path.join(top, 'scripts', 'story', 'shared.fs')]:
    used.update(code_tokens(open(f).read()))

# what is written
path = os.path.join(top, 'scripts', 'story', 'words.fs')
text = open(path).read()
head = text[:text.index(MARK)]
written = set(re.findall(r'^:\s+(\S+)', head, re.M)) | set(re.findall(r'(?:create|variable|constant|defer)\s+(\S+)', head))

# the old definitions' stack comments
sigs = {}
for name in ('core.fs', 'words.fs', 'play.fs', 'strings.fs'):
    for m in re.finditer(r'^:\s+(\S+)\s+(\([^)]*\))(\s*\(\s*F:[^)]*\))?', open(os.path.join(old, name)).read(), re.M):
        sigs.setdefault(m.group(1), (m.group(2), m.group(3) or ''))
    for m in re.finditer(r'^defer\s+(\S+)\s+(\([^)]*\))', open(os.path.join(old, name)).read(), re.M):
        sigs.setdefault(m.group(1), (m.group(2), ''))


def side(tokens):
    """cells, floats from a side of a stack comment"""
    cells, floats, fl = [], [], False
    for t in tokens:
        if t == 'F:':
            fl = True
        elif t not in ('(', ')', '|'):
            (floats if fl else cells).append(t)
    return cells, floats


def stub(name, sig):
    s = (sig[0] + ' ' + sig[1]).replace(')', ' ) ').replace('(', ' ( ')
    groups = re.findall(r'\(([^()]*)\)', s)
    ins_c, ins_f, outs_c, outs_f = [], [], [], []
    for g in groups:
        if '--' not in g:
            continue
        a, b = g.split('--', 1)
        c, fl = side(a.split())
        ins_c += c
        ins_f += fl
        c, fl = side(b.split())
        outs_c += [x for x in c if x not in ('|', '0')] if c else []
        outs_f += fl
    body = []
    var = [i for i, t in enumerate(ins_c) if t.endswith('..')]
    if var:
        v = var[0]
        after = ins_c[v + 1:]
        body += ['drop'] * (len(after) - 1) + ['0 ?do  drop  loop'] + ['drop'] * v
    else:
        body += ['drop'] * len(ins_c)
    body += ['fdrop'] * len(ins_f)
    if 'wait' in name:   # (a wait: still a frame's wait, so a script looping on it gives up its turn)
        body += ['wait-frame']
    if len(outs_c) == 1 and not outs_f:
        body += ['s" %s" stub-flag' % name]
    else:
        body += ['s" %s" stub-step' % name] + ['0'] * len(outs_c) + ['0e'] * len(outs_f)
    comment = sig[0] + (' ' + sig[1].strip() if sig[1] else '')
    return ': %s %s  %s ;' % (name, comment, '  '.join(body))


lines = [MARK]
missing = []
for name in sorted(used - written):
    if name in sigs:
        lines.append(stub(name, sigs[name]))
    else:
        missing.append(name)
open(path, 'w').write(head + '\n'.join(lines) + '\n')
print(len(lines) - 1, 'stubs; used but not event words (Forth, room words):', len(missing))
print(' '.join(m for m in missing if not re.match(r'^[a-z0-9-]+\.(cmd|cond|act|enter|phase|char)', m)))
