#!/usr/bin/env python3
"""Hewie's tables from the executable into scripts/partner/tables.fs: the weighted action lists
he picks from (Hewie_WhatNext, Hewie_WhenIdle: {action, a weight per trust level 0..7}, the
weights of a list summing to 100) and his chance tables (a percent per trust level).

usage: partnertables.py [repo root]"""
import os
import struct
import sys

root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', '..')
elf = open(os.path.join(root, 'baserom', 'SLUS_210.75'), 'rb').read()
e_phoff, = struct.unpack_from('<I', elf, 0x1C)
e_phnum, = struct.unpack_from('<H', elf, 0x2C)
segs = [struct.unpack_from('<5I', elf, e_phoff + i * 32)[1:] for i in range(e_phnum)]


def at(va, n):
    for off, vaddr, _, size in segs:
        if vaddr <= va and va + n <= vaddr + size:
            return elf[off + va - vaddr: off + va - vaddr + n]
    raise ValueError(hex(va))


def read_list(va, count=None):
    out, sums = [], [0] * 8
    while (count is None and min(sums) < 100) or (count is not None and len(out) < count):
        act, = struct.unpack('<i', at(va, 4))
        w = list(at(va + 4, 8))
        out.append((act, w))
        sums = [s + x for s, x in zip(sums, w)]
        va += 12
    return out


lines = ["\\ Generated by new-src/tools/partnertables.py from the executable: Hewie's action lists and",
         "\\ chance tables (src/game/hewie.c Hewie_WhatNext, Hewie_WhenIdle, by_chance).",
         'IN: partner.tables', '',
         '\\ a list: its length, then per entry the action and its weight for each trust level 0..7',
         '\\ (9 cells); a table: its number of lists, then the lists']
tables = [('calm-lists', 0x3B02C0, 7, 'D_003B02C0: calm, by her distance band'),
          ('calm-wait-lists', 0x3B0480, 7, 'D_003B0480: calm, waiting'),
          ('followed-lists', 0x3B05F0, 7, 'D_003B05F0: being followed'),
          ('followed-wait-lists', 0x3B06F0, 7, 'D_003B06F0: being followed, waiting'),
          ('tense-lists', 0x3B0850, 11, 'D_003B0850: the chase / a hostile creature'),
          ('tense-wait-lists', 0x3B0A90, 11, 'D_003B0A90: the chase, waiting'),
          ('tense-wait-hard-lists', 0x3B0E20, 11, 'D_003B0E20: the chase, waiting (hard)')]
for name, va, n, what in tables:
    ptrs = struct.unpack('<%dI' % n, at(va, 4 * n))
    names = []
    for i, p in enumerate(ptrs):
        entries = read_list(p)
        lname = '%s-%d' % (name, i)
        names.append(lname)
        body = '  '.join('$%02X , %s' % (a & 0xFFFFFFFF, ' '.join('%d ,' % x for x in w)) for a, w in entries)
        lines.append('create %s  %d ,  %s' % (lname, len(entries), body))
    lines.append('create %s  %d , %s   \\ %s' % (name, n, ' '.join("%s ," % x for x in names), what))
    lines.append('')
idle = read_list(0x3B11B0, 3)
lines.append('\\ D_003B11B0: when idle (Hewie_WhenIdle; one of them weighted 20 more by the game mode)')
lines.append('create idle-list  3 ,  %s' % '  '.join('$%02X , %s' % (a, ' '.join('%d ,' % x for x in w)) for a, w in idle))
lines.append('')
chances = [('growl-chance', 0x3B1240, 'D_003B1240: he growls at the pursuer'),
           ('hidden-out-chance', 0x3B1238, 'D_003B1238: hidden, he comes out at panic 4 / 5'),
           ('noise-chance', 0x3B11E8, 'D_003B11E8: hidden, he goes to a noise'),
           ('held-answer-chance', 0x3B1220, 'D_003B1220: he answers her call while she is held'),
           ('panic4-chance', 0x3B1228, 'D_003B1228: ... at panic 4'),
           ('panic5-chance', 0x3B1230, 'D_003B1230: ... at panic 5'),
           ('go-for-holder-chance', 0x3B11E0, 'D_003B11E0: he goes for whoever holds her')]
lines.append('\\ chance tables: a signed percent per trust level 0..7')
for name, va, what in chances:
    vals = struct.unpack('<8b', at(va, 8))
    lines.append('create %s  %s   \\ %s' % (name, ' '.join('%d ,' % v for v in vals), what))
lines.append('')
times = [('obey-time', 0x3B1350, 'kHewieLevelNormal: how long he obeys (+0xF359C)'),
         ('obey-time-hard', 0x3B1370, 'kHewieLevelHard: ... on the hard difficulty'),
         ('wait-time', 0x3B1390, 'D_003B1390: how long he waits once disobedient'),
         ('wait-time-hard', 0x3B13B0, 'D_003B13B0: ... on the hard difficulty'),
         ('idle-wait', 0x3B13D0, 'D_003B13D0: the wait of action 0x2E')]
lines.append('\\ frame counts per trust level 0..7')
for name, va, what in times:
    vals = struct.unpack('<8i', at(va, 32))
    lines.append('create %s  %s   \\ %s' % (name, ' '.join('%d ,' % v for v in vals), what))
lines.append('')
offs = struct.unpack('<8f', at(0x3B12A0, 32))
lines.append("\\ kHewieMeetOffsets: where Fiona stands to meet him, by kind (x z, his frame; floats)")
lines.append('create meet-offsets  %s' % ' '.join('%se f,' % repr(v) for v in offs))
out = os.path.join(root, 'new-src', 'scripts', 'partner', 'tables.fs')
open(out, 'w').write('\n'.join(lines) + '\n')
print(out)
