#!/usr/bin/env python3
"""The rooms' string tables (RoomXX_ObjectNames: what event commands name by number - scenes,
movies, room objects) read from the executable into scripts/events/strings.fs as
`room-string ( i -- addr len )` for the room the scripts are in.

usage: roomstrings.py [repo root]"""
import os
import re
import struct
import sys

root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', '..')
elf = open(os.path.join(root, 'baserom', 'SLUS_210.75'), 'rb').read()
syms = {}
addrs = []
for line in open(os.path.join(root, 'config', 'symbol_addrs.txt')):
    m = re.match(r'\s*(\w+)\s*=\s*0x([0-9A-Fa-f]+);', line)
    if m:
        syms[m.group(1)] = int(m.group(2), 16)
        addrs.append(int(m.group(2), 16))
addrs.sort()

e_phoff, = struct.unpack_from('<I', elf, 0x1C)
e_phnum, = struct.unpack_from('<H', elf, 0x2C)
segs = []
for i in range(e_phnum):
    _, off, vaddr, _, filesz = struct.unpack_from('<5I', elf, e_phoff + i * 32)
    segs.append((vaddr, off, filesz))


def at(va, n):
    for vaddr, off, size in segs:
        if vaddr <= va and va + n <= vaddr + size:
            return elf[off + va - vaddr: off + va - vaddr + n]
    return None


def cstring(va):
    out = b''
    while len(out) < 64:
        c = at(va + len(out), 1)
        if c is None:
            return None
        if c == b'\0':
            break
        out += c
    if not out or any(b < 0x20 or b > 0x7E for b in out):
        return None
    return out.decode()


def table(va):
    nxt = next((a for a in addrs if a > va), va + 0x100)
    out = []
    while va + 4 * len(out) < nxt:
        p = at(va + 4 * len(out), 4)
        s = cstring(struct.unpack('<I', p)[0]) if p else None
        if s is None:
            break
        out.append(s)
    return out


rooms = {}
for name, va in syms.items():
    m = re.match(r'Room([0-9A-F]{2})_ObjectNames$', name)
    if m:
        rooms[int(m.group(1), 16)] = table(va)

lines = ['\\ Generated by new-src/tools/roomstrings.py from the executable: the rooms\' string tables',
         '\\ (RoomXX_ObjectNames: what event commands name by number - scenes, movies, room objects)',
         '\\ and the background music\'s tracks.',
         'IN: events.strings',
         'USING: game-state ;',
         '',
         ': room-string ( i -- addr len )   \\ string i of the room the scripts are in ("" none)',
         '    event-state ev.room sl@ case']
for room in sorted(rooms):
    if not rooms[room]:
        continue
    lines.append('    $%02X of  case' % room)
    for i, s in enumerate(rooms[room]):
        lines.append('        %d of  s" %s" endof' % (i, s.replace('"', '')))
        if '"' in s:
            print('warning: quote in', s, file=sys.stderr)
    lines.append('        >r s" " r>  endcase  endof')
lines.append('    >r s" " r>  endcase ;')
# the background music's tracks (pstr_ADX00_AD_01_ADX: a name and a loop flag, 8 bytes each)
va = syms['pstr_ADX00_AD_01_ADX']
tracks = []
while len(tracks) < 0x100:
    p = at(va + len(tracks) * 8, 5)
    name = cstring(struct.unpack('<I', p[:4])[0]) if p else None
    if name is None:
        break
    tracks.append((name, p[4]))
lines += ['', '\\ the background music\'s tracks (pstr_ADX00_AD_01_ADX): the file and whether it loops',
          ': bgm-track ( n -- addr len loop? )',
          '    case']
for i, (name, loop) in enumerate(tracks):
    lines.append('        $%02X of  s" %s" %s  endof' % (i, name, 'true' if loop else 'false'))
lines.append('        >r s" " false r>  endcase ;')
# the stage music's tables per stage set (SceneGame_MusicDirector's sTables: the chase table, then
# per track and channel the volumes, bends and pans, then the four tracks' sequence volumes)
scene = open(os.path.join(root, 'src', 'game', 'scene_game.c')).read()
rows = re.findall(r'\{(D_\w+), (D_\w+), (D_\w+), (D_\w+), (str_\w+), (D_\w+)\}', scene)


def addr(name):
    return int(name[2:], 16) if name.startswith('D_') else syms[name]


lines += ['', '\\ the stage music\'s tables (SceneGame_MusicDirector): per stage set, the 4 x 16 channels\'',
          '\\ volumes, bends and pans, and the 4 tracks\' sequence volumes']
for k, row in enumerate(rows):
    for label, name, n in (('vols', row[1], 64), ('bends', row[2], 64), ('pans', row[3], 64), ('seq-vols', row[4], 4)):
        b = at(addr(name), n)
        lines.append('create stage%d-%s  %s' % (k, label, ' '.join('$%02X c,' % x for x in b)))
lines += [': stage-table ( stage which -- addr )   \\ which: 0 volumes, 1 bends, 2 pans, 3 sequence volumes',
          '    swap case']
for k in range(len(rows)):
    lines.append('        %d of  case  0 of stage%d-vols endof  1 of stage%d-bends endof  2 of stage%d-pans endof'
                 '  >r stage%d-seq-vols r>  endcase  endof' % (k, k, k, k, k))
lines.append('        >r drop stage0-vols r>  endcase ;')
# the stage music's files per stage set (MusicStageN_Load's sFiles: the bank's header, the four
# sequences - panic, calm A and B, chase - and the bank's samples)
music = open(os.path.join(root, 'src', 'game', 'music.c')).read()
sets = re.findall(r'sFiles\[6\] = \{([^}]*)\}', music)
lines += ['', '\\ the stage music\'s files (MusicStageN_Load): 0 the bank (.HD), 1..4 the sequences (panic,',
          '\\ calm A and B, chase), 5 the bank\'s samples (.BD)',
          ': stage-file ( stage i -- addr len )',
          '    swap case']
for k, names in enumerate(sets):
    files = [cstring(addr(n.strip())) for n in names.split(',')]
    lines.append('        %d of  case  %s  >r s" " r>  endcase  endof'
                 % (k, '  '.join('%d of s" %s" endof' % (i, f) for i, f in enumerate(files))))
lines.append('        >r drop s" " r>  endcase ;')
out = os.path.join(root, 'new-src', 'scripts', 'events', 'strings.fs')
open(out, 'w').write('\n'.join(lines) + '\n')
print(out, len(rooms), 'rooms')
