#!/usr/bin/env python3
"""The rooms' string tables (RoomXX_ObjectNames: what event commands name by number - scenes,
movies, room objects) read from the executable into scripts/events/strings.fs as
`room-string ( i -- addr len )` for the room the scripts are in.

usage: roomstrings.py [repo root]"""
import os
import re
import struct
import sys

root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', '..')
elf = open(os.path.join(root, 'baserom', 'SLUS_210.75'), 'rb').read()
syms = {}
addrs = []
for line in open(os.path.join(root, 'config', 'symbol_addrs.txt')):
    m = re.match(r'\s*(\w+)\s*=\s*0x([0-9A-Fa-f]+);', line)
    if m:
        syms[m.group(1)] = int(m.group(2), 16)
        addrs.append(int(m.group(2), 16))
addrs.sort()

e_phoff, = struct.unpack_from('<I', elf, 0x1C)
e_phnum, = struct.unpack_from('<H', elf, 0x2C)
segs = []
for i in range(e_phnum):
    _, off, vaddr, _, filesz = struct.unpack_from('<5I', elf, e_phoff + i * 32)
    segs.append((vaddr, off, filesz))


def at(va, n):
    for vaddr, off, size in segs:
        if vaddr <= va and va + n <= vaddr + size:
            return elf[off + va - vaddr: off + va - vaddr + n]
    return None


def cstring(va):
    out = b''
    while len(out) < 64:
        c = at(va + len(out), 1)
        if c is None:
            return None
        if c == b'\0':
            break
        out += c
    if not out or any(b < 0x20 or b > 0x7E for b in out):
        return None
    return out.decode()


def table(va):
    nxt = next((a for a in addrs if a > va), va + 0x100)
    out = []
    while va + 4 * len(out) < nxt:
        p = at(va + 4 * len(out), 4)
        s = cstring(struct.unpack('<I', p)[0]) if p else None
        if s is None:
            break
        out.append(s)
    return out


rooms = {}
for name, va in syms.items():
    m = re.match(r'Room([0-9A-F]{2})_ObjectNames$', name)
    if m:
        rooms[int(m.group(1), 16)] = table(va)

lines = ['\\ Generated by new-src/tools/roomstrings.py from the executable: the rooms\' string tables',
         '\\ (RoomXX_ObjectNames: what event commands name by number - scenes, movies, room objects)',
         '\\ and the background music\'s tracks.',
         'IN: events.strings',
         'USING: game-state ;',
         '',
         ': room-string ( i -- addr len )   \\ string i of the room the scripts are in ("" none)',
         '    event-state ev.room sl@ case']
for room in sorted(rooms):
    if not rooms[room]:
        continue
    lines.append('    $%02X of  case' % room)
    for i, s in enumerate(rooms[room]):
        lines.append('        %d of  s" %s" endof' % (i, s.replace('"', '')))
        if '"' in s:
            print('warning: quote in', s, file=sys.stderr)
    lines.append('        >r s" " r>  endcase  endof')
lines.append('    >r s" " r>  endcase ;')
# the background music's tracks (pstr_ADX00_AD_01_ADX: a name and a loop flag, 8 bytes each)
va = syms['pstr_ADX00_AD_01_ADX']
tracks = []
while len(tracks) < 0x100:
    p = at(va + len(tracks) * 8, 5)
    name = cstring(struct.unpack('<I', p[:4])[0]) if p else None
    if name is None:
        break
    tracks.append((name, p[4]))
lines += ['', '\\ the background music\'s tracks (pstr_ADX00_AD_01_ADX): the file and whether it loops',
          ': bgm-track ( n -- addr len loop? )',
          '    case']
for i, (name, loop) in enumerate(tracks):
    lines.append('        $%02X of  s" %s" %s  endof' % (i, name, 'true' if loop else 'false'))
lines.append('        >r s" " false r>  endcase ;')
out = os.path.join(root, 'new-src', 'scripts', 'events', 'strings.fs')
open(out, 'w').write('\n'.join(lines) + '\n')
print(out, len(rooms), 'rooms')
