\ stalker/spots.fs - generated by tools/searchspots.py: each room's search spots (the
\ triangles a stalker searches there, RoomXX_Table38_data) and, by exit, the room he heads
\ for past it (RoomXX_Table3C_data).
IN: stalker.spots
USING: room-names ;

create spots-0 328 , 338 , 260 ,
create spots-1 442 , 370 ,
create spots-2 72 , 615 , 306 , 277 , 30 , 765 ,
create spots-3 209 , 80 , 258 , 130 ,
create spots-4 165 , 191 , 272 ,
create spots-7 531 , 662 , 191 ,
create spots-8 289 , 331 , 285 ,
create spots-9 54 , 265 , 106 ,
create spots-A 179 , 128 , 195 ,
create spots-E 550 , 629 , 846 , 27 , 193 ,
create spots-F 443 , 412 ,
create spots-10 448 , 155 , 277 ,
create spots-11 42 , 345 , 294 ,
create spots-12 481 , 351 , 161 ,
create spots-13 111 , 522 , 483 , 508 , 283 ,
create spots-14 21 , 314 , 359 ,
create spots-15 162 , 127 , 221 ,
create spots-16 173 , 237 ,
create spots-18 179 , 321 , 174 , 49 ,
create spots-19 461 , 509 , 71 , 22 ,
create spots-1A 204 , 182 , 49 ,
create spots-1B 170 , 207 ,
create spots-1C 115 , 179 , 283 ,
create spots-1D 51 , 35 , 262 ,
create spots-1E 149 , 282 ,
create spots-1F 31 , 86 , 338 ,
create spots-20 177 , 735 , 778 , 258 , 391 ,
create spots-21 197 , 136 , 181 , 161 ,
create spots-22 192 , 262 ,
create spots-23 52 , 45 ,
create spots-24 111 , 238 ,
create spots-25 10 , 324 , 409 , 322 ,
create spots-26 86 , 180 , 11 ,
create spots-28 14 , 32 , 414 ,
create spots-29 114 , 129 , 146 ,
create spots-2A 112 , 523 , 554 , 359 , 786 , 635 ,
create spots-2B 64 , 136 , 267 , 220 ,
create spots-2D 269 , 123 , 296 , 321 ,
create spots-2F 14 , 32 , 414 ,
create spots-30 14 , 32 , 493 ,
create spots-32 197 , 136 , 181 , 161 ,
create spots-40 432 , 337 , 248 , 404 ,
create spots-41 26 , 84 , 101 , 327 ,
create spots-42 100 , 79 , 107 , 108 ,
create spots-43 340 , 304 , 436 , 68 , 474 , 99 , 113 ,
create spots-44 224 , 168 , 140 , 26 , 227 ,
create spots-45 24 ,
create spots-46 30 , 252 , 276 , 260 , 206 ,
create spots-47 49 , 44 , 183 ,
create spots-48 97 , 69 , 437 , 264 , 340 ,
create spots-49 90 , 116 , 8 ,
create spots-4A 59 , 239 ,
create spots-4B 217 , 420 , 62 , 85 , 53 , 428 , 333 , 551 ,
create spots-4C 53 , 49 ,
create spots-4D 204 , 83 ,
create spots-4E 70 , 24 , 157 ,
create spots-4F 334 , 181 , 302 , 146 ,
create spots-50 111 , 17 , 95 ,
create spots-51 113 , 66 , 95 ,
create spots-52 57 , 51 , 11 , 189 , 88 , 73 , 209 ,
create spots-53 116 , 83 , 17 ,
create spots-54 200 , 44 , 54 , 236 ,
create spots-55 405 , 524 , 751 , 380 ,
create spots-56 155 , 117 ,
create spots-57 69 , 139 ,
create spots-58 291 , 15 , 426 , 207 ,
create spots-59 13 , 121 , 51 ,
create spots-5A 272 , 84 , 7 , 165 , 327 , 346 ,
create spots-5B 19 , 136 , 119 ,
create spots-5C 215 , 195 , 170 , 177 , 188 ,
create spots-5D 42 , 263 , 293 , 71 ,
create spots-5E 217 , 210 ,
create spots-5F 270 , 86 , 295 ,
create spots-60 487 , 936 , 1575 , 1571 , 1579 ,
create spots-61 385 , 121 , 202 , 295 ,
create spots-62 77 , 62 , 20 , 61 , 128 ,
create spots-63 287 , 47 , 150 ,
create spots-64 0 ,
create spots-65 0 ,
create spots-66 499 , 321 , 297 , 93 , 88 ,
create spots-67 271 , 282 , 358 , 137 , 115 , 63 , 241 ,
create spots-69 38 , 5 , 77 ,
create spots-6A 243 , 91 , 202 , 229 ,
create spots-6B 79 , 146 ,
create spots-6C 393 , 71 , 305 , 371 , 272 ,
create spots-6D 227 , 54 , 257 , 35 , 10 ,
create spots-6E 138 , 130 , 140 , 79 ,
create spots-6F 32 , 9 , 104 ,
create spots-70 7 , 72 , 185 ,
create spots-81 32 , 408 , 157 , 293 , 319 ,
create spots-82 154 , 419 , 195 ,
create spots-83 104 , 150 ,
create spots-84 55 , 66 ,
create spots-85 46 ,
create spots-86 208 , 50 ,
create spots-88 424 , 527 , 194 , 703 , 293 ,
create spots-8A 92 , 339 , 474 , 241 , 526 ,
create spots-8C 278 , 315 , 50 ,
create spots-8D 201 , 48 , 217 ,
create spots-8F 24 , 66 , 394 ,
create spots-91 493 , 514 , 7 ,
create spots-97 208 , 50 ,
create spots-98 796 , 439 ,
create spots-99 796 , 439 ,
create spots-9A 796 , 439 ,
create spots-9B 135 , 64 ,
create spots-C1 233 , 53 , 109 ,
create spots-C2 
create spots-C3 
create spots-C4 
create spots-C5 
create spots-C6 541 , 474 , 355 ,
create spots-C7 
create spots-C8 
create spots-D0 271 , 282 , 358 , 137 , 115 , 63 , 241 ,
create spots-D1 145 , 218 , 277 , 127 ,
create spots-D2 201 , 123 , 173 ,
create spots-D3 121 , 495 , 173 , 156 , 66 ,
create spots-D4 201 , 123 , 173 ,
create spots-D5 249 , 97 , 20 , 308 , 195 ,
create spots-D6 128 , 283 , 72 ,
create spots-D7 11 , 49 , 95 ,
create spots-D8 64 , 177 , 183 , 107 , 205 , 25 , 118 ,
create spots-D9 37 , 73 ,
create spots-E0 197 , 136 , 181 , 161 ,
create spots-E1 448 , 155 , 277 ,
create spots-E2 42 , 345 , 294 ,
create spots-E3 481 , 351 , 161 ,
create spots-E4 443 , 412 ,
create spots-E5 21 , 314 , 359 ,
create spots-E6 162 , 127 , 221 ,
create spots-E7 179 , 321 , 174 , 49 ,
create spots-E8 550 , 629 , 846 , 27 , 193 ,
create spots-E9 328 , 338 , 260 ,
create spots-100 19 , 84 , 104 ,
create spots-101 201 , 123 , 173 ,
create spots-102 309 , 1 , 359 ,
create spots-103 128 , 283 , 72 ,
create spots-104 282 ,
create spots-105 235 , 231 ,
create spots-106 145 , 218 , 277 , 127 ,
create spots-107 11 , 49 , 95 ,
create spots-108 121 , 495 , 173 , 156 , 66 ,
create spots-109 249 , 97 , 20 , 308 , 195 ,
create spots-10A 64 , 177 , 183 , 107 , 205 , 25 , 118 ,
create spots-10B 37 , 73 ,

: search-spots ( room -- addr n )   \ (none: 0 0)
    case
        front-garden-1 of  spots-0 3  endof
        castle-1f-1 of  spots-1 2  endof
        castle-1f-2 of  spots-2 6  endof
        castle-1f-11 of  spots-3 4  endof
        castle-1f-12 of  spots-4 3  endof
        castle-b1-4 of  spots-7 3  endof
        castle-1f-13 of  spots-8 3  endof
        castle-1f-3 of  spots-9 3  endof
        castle-2f-1 of  spots-A 3  endof
        castle-1f-14 of  spots-E 5  endof
        castle-1f-4 of  spots-F 2  endof
        castle-1f-5 of  spots-10 3  endof
        castle-1f-6 of  spots-11 3  endof
        castle-b1-1 of  spots-12 3  endof
        front-garden-2 of  spots-13 5  endof
        castle-b1-2 of  spots-14 3  endof
        castle-1f-7 of  spots-15 3  endof
        castle-b1-3 of  spots-16 2  endof
        castle-1f-8 of  spots-18 4  endof
        castle-1f-15 of  spots-19 4  endof
        castle-1f-16 of  spots-1A 3  endof
        castle-1f-17 of  spots-1B 2  endof
        castle-1f-18 of  spots-1C 3  endof
        castle-b1-7 of  spots-1D 3  endof
        castle-1f-19 of  spots-1E 2  endof
        castle-2f-11 of  spots-1F 3  endof
        castle-2f-2 of  spots-20 5  endof
        castle-2f-3 of  spots-21 4  endof
        castle-2f-6 of  spots-22 2  endof
        castle-2f-7 of  spots-23 2  endof
        castle-2f-8 of  spots-24 2  endof
        castle-1f-9 of  spots-25 4  endof
        castle-2f-12 of  spots-26 3  endof
        castle-2f-13 of  spots-28 3  endof
        castle-1f-10 of  spots-29 3  endof
        front-garden-3 of  spots-2A 6  endof
        front-garden-4 of  spots-2B 4  endof
        front-garden-5 of  spots-2D 4  endof
        castle-2f-14 of  spots-2F 3  endof
        castle-2f-15 of  spots-30 3  endof
        castle-2f-5 of  spots-32 4  endof
        old-mansion-1f-2 of  spots-40 4  endof
        old-mansion-1f-3 of  spots-41 4  endof
        old-mansion-1f-4 of  spots-42 4  endof
        old-mansion-1f-5 of  spots-43 7  endof
        old-mansion-b1-1 of  spots-44 5  endof
        old-mansion-2f-1 of  spots-45 1  endof
        old-mansion-1f-6 of  spots-46 5  endof
        old-mansion-1f-7 of  spots-47 3  endof
        old-mansion-1f-8 of  spots-48 5  endof
        old-mansion-1f-9 of  spots-49 3  endof
        old-mansion-2f-2 of  spots-4A 2  endof
        old-mansion-b1-2 of  spots-4B 8  endof
        old-mansion-b1-3 of  spots-4C 2  endof
        old-mansion-1f-10 of  spots-4D 2  endof
        old-mansion-1f-11 of  spots-4E 3  endof
        old-mansion-1f-12 of  spots-4F 4  endof
        old-mansion-b1-4 of  spots-50 3  endof
        old-mansion-b1-5 of  spots-51 3  endof
        old-mansion-1f-13 of  spots-52 7  endof
        old-mansion-1f-14 of  spots-53 3  endof
        old-mansion-1f-15 of  spots-54 4  endof
        old-mansion-1f-16 of  spots-55 4  endof
        old-mansion-2f-3 of  spots-56 2  endof
        old-mansion-2f-4 of  spots-57 2  endof
        old-mansion-2f-5 of  spots-58 4  endof
        old-mansion-2f-6 of  spots-59 3  endof
        off-map-5a of  spots-5A 6  endof
        old-mansion-2f-7 of  spots-5B 3  endof
        old-mansion-2f-8 of  spots-5C 5  endof
        old-mansion-1f-17 of  spots-5D 4  endof
        old-mansion-2f-9 of  spots-5E 2  endof
        old-mansion-2f-10 of  spots-5F 3  endof
        old-mansion-3f-1 of  spots-60 5  endof
        old-mansion-b1-7 of  spots-61 4  endof
        old-mansion-2f-11 of  spots-62 5  endof
        old-mansion-3f-2 of  spots-63 3  endof
        off-map-64 of  spots-64 1  endof
        off-map-65 of  spots-65 1  endof
        old-mansion-b1-6 of  spots-66 5  endof
        chaos-forest-1 of  spots-67 7  endof
        old-mansion-2f-12 of  spots-69 3  endof
        old-mansion-2f-13 of  spots-6A 4  endof
        old-mansion-1f-19 of  spots-6B 2  endof
        old-mansion-1f-20 of  spots-6C 5  endof
        old-mansion-1f-21 of  spots-6D 5  endof
        old-mansion-1f-22 of  spots-6E 4  endof
        old-mansion-1f-23 of  spots-6F 3  endof
        old-mansion-1f-24 of  spots-70 3  endof
        house-of-truth-1f-1 of  spots-81 5  endof
        house-of-truth-2f-1 of  spots-82 3  endof
        house-of-truth-2f-2 of  spots-83 2  endof
        house-of-truth-b1-1 of  spots-84 2  endof
        house-of-truth-b1-2 of  spots-85 1  endof
        house-of-truth-b1-3 of  spots-86 2  endof
        house-of-truth-1f-2 of  spots-88 5  endof
        house-of-truth-1f-3 of  spots-8A 5  endof
        house-of-truth-1f-4 of  spots-8C 3  endof
        house-of-truth-1f-5 of  spots-8D 3  endof
        house-of-truth-1f-7 of  spots-8F 3  endof
        house-of-truth-1f-8 of  spots-91 3  endof
        house-of-truth-b1-9 of  spots-97 2  endof
        house-of-truth-b1-10 of  spots-98 2  endof
        house-of-truth-b1-11 of  spots-99 2  endof
        house-of-truth-b1-12 of  spots-9A 2  endof
        house-of-truth-1f-10 of  spots-9B 2  endof
        water-tower-1f-1 of  spots-C1 3  endof
        water-tower-2f-1 of  spots-C2 0  endof
        water-tower-4f-1 of  spots-C3 0  endof
        off-map-c4 of  spots-C4 0  endof
        water-tower-7f-1 of  spots-C5 0  endof
        water-tower-7f-2 of  spots-C6 3  endof
        water-tower-8f-1 of  spots-C7 0  endof
        lake-pathway-1 of  spots-C8 0  endof
        off-map-d0 of  spots-D0 7  endof
        off-map-d1 of  spots-D1 4  endof
        off-map-d2 of  spots-D2 3  endof
        off-map-d3 of  spots-D3 5  endof
        off-map-d4 of  spots-D4 3  endof
        off-map-d5 of  spots-D5 5  endof
        off-map-d6 of  spots-D6 3  endof
        off-map-d7 of  spots-D7 3  endof
        off-map-d8 of  spots-D8 7  endof
        off-map-d9 of  spots-D9 2  endof
        off-map-e0 of  spots-E0 4  endof
        off-map-e1 of  spots-E1 3  endof
        off-map-e2 of  spots-E2 3  endof
        off-map-e3 of  spots-E3 3  endof
        off-map-e4 of  spots-E4 2  endof
        off-map-e5 of  spots-E5 3  endof
        off-map-e6 of  spots-E6 3  endof
        off-map-e7 of  spots-E7 4  endof
        off-map-e8 of  spots-E8 5  endof
        off-map-e9 of  spots-E9 3  endof
        chaos-forest-2 of  spots-100 3  endof
        chaos-forest-3 of  spots-101 3  endof
        chaos-forest-4 of  spots-102 3  endof
        chaos-forest-5 of  spots-103 3  endof
        chaos-forest-6 of  spots-104 1  endof
        chaos-forest-7 of  spots-105 2  endof
        chaos-forest-8 of  spots-106 4  endof
        chaos-forest-9 of  spots-107 3  endof
        chaos-forest-10 of  spots-108 5  endof
        chaos-forest-11 of  spots-109 5  endof
        chaos-forest-12 of  spots-10A 7  endof
        chaos-forest-13 of  spots-10B 2  endof
        >r 0 0 r>
    endcase ;

create goals-2 30 , 41 , 41 , 41 , -1 , -1 , -1 , -1 ,
create goals-20 16 , 16 , 16 , 34 , 16 , -1 , -1 , -1 ,
: exit-goal ( exit room -- room | -1 )
    case
        castle-1f-2 of  dup 8 u< if  cells goals-2 + @  else  drop -1  then  endof
        castle-2f-2 of  dup 8 u< if  cells goals-20 + @  else  drop -1  then  endof
        >r drop -1 r>
    endcase ;
