\ stalker/tables.fs - generated by tools/stalkertables.py: Debilitas's tables from the
\ executable (src/game/debilitas.c). Rows: kind, argument, running percentage (0..100).
IN: stalker.tables
USING: engine ;

create table-0  $14 , -1 , 25e f,  $13 , 6 , 50e f,  $17 , 1 , 70e f,  $17 , 3 , 90e f,  $1003 , -1 , 100e f,
create table-1  $17 , 1 , 10e f,  $17 , 3 , 20e f,  $17 , 7 , 70e f,  $17 , 5 , 80e f,  $1B , -1 , 100e f,
create table-2  $14 , -1 , 50e f,  $13 , 6 , 60e f,  $17 , 1 , 70e f,  $1003 , -1 , 90e f,  $17 , 3 , 100e f,
create table-3  $17 , 5 , 10e f,  $17 , 1 , 30e f,  $17 , 7 , 60e f,  $1B , -1 , 90e f,  $17 , 3 , 100e f,
create table-4  $14 , -1 , 50e f,  $13 , 3 , 100e f,
create table-5  $1002 , -1 , 75e f,  $13 , 14 , 100e f,
create table-6  $13 , 6 , 25e f,  $17 , 3 , 45e f,  $1003 , -1 , 65e f,  $13 , 0 , 75e f,  $17 , 1 , 100e f,
create table-7  $13 , 3 , 75e f,  $17 , 3 , 85e f,  $17 , 7 , 100e f,
create table-8  $13 , 3 , 25e f,  $13 , 0 , 45e f,  $14 , -1 , 70e f,  $13 , 5 , 80e f,  $17 , 0 , 90e f,  $1 , -1 , 100e f,
create table-9  $13 , 5 , 100e f,
create table-10  $19 , 5 , 10e f,  $19 , 1 , 35e f,  $19 , 3 , 60e f,  $1A , -1 , 85e f,  $17 , 0 , 100e f,
create table-11  $13 , 3 , 100e f,
create table-12  $18 , 7 , 50e f,  $18 , 5 , 60e f,  $1A , -1 , 80e f,  $18 , 1 , 100e f,
create table-13  $18 , 3 , 50e f,  $18 , 1 , 75e f,  $18 , 5 , 100e f,
create table-14  $1 , -1 , 100e f,
create table-15  $17 , 1 , 100e f,
create table-16  $9 , -1 , 50e f,  $17 , 1 , 70e f,  $17 , 3 , 90e f,  $17 , 5 , 100e f,
create table-17  $14 , -1 , 20e f,  $13 , 2 , 45e f,  $1001 , -1 , 55e f,  $13 , 10 , 75e f,  $13 , 0 , 85e f,  $13 , 6 , 100e f,
create table-18  $14 , -1 , 25e f,  $13 , 15 , 45e f,  $1001 , -1 , 65e f,  $13 , 10 , 90e f,  $17 , 1 , 100e f,
create table-19  $14 , -1 , 20e f,  $13 , 7 , 40e f,  $13 , 15 , 60e f,  $13 , 13 , 70e f,  $1001 , -1 , 90e f,  $15 , -1 , 100e f,
create table-20  $17 , 3 , 25e f,  $17 , 1 , 50e f,  $17 , 0 , 75e f,  $17 , 5 , 100e f,
create table-21  $15 , -1 , 25e f,  $13 , 3 , 50e f,  $13 , 7 , 70e f,  $13 , 2 , 90e f,  $13 , 9 , 100e f,
create table-22  $13 , 8 , 75e f,  $1002 , -1 , 100e f,
create table-23  $13 , 10 , 20e f,  $13 , 6 , 30e f,  $13 , 13 , 50e f,  $13 , 1 , 75e f,  $13 , 2 , 100e f,
create table-24  $13 , 7 , 25e f,  $13 , 12 , 50e f,  $13 , 9 , 100e f,
create table-25  $14 , -1 , 20e f,  $13 , 12 , 45e f,  $13 , 5 , 55e f,  $13 , 7 , 75e f,  $1001 , -1 , 100e f,
create table-26  $13 , 5 , 100e f,
create table-27  $19 , 3 , 25e f,  $13 , 16 , 50e f,  $19 , 1 , 75e f,  $1001 , -1 , 100e f,
create table-28  $13 , 7 , 100e f,
create table-29  $1A , -1 , 10e f,  $18 , 1 , 35e f,  $18 , 3 , 60e f,  $18 , 7 , 85e f,  $13 , 3 , 100e f,
create table-30  $13 , 1 , 10e f,  $13 , 2 , 25e f,  $13 , 3 , 50e f,  $18 , 3 , 70e f,  $18 , 1 , 80e f,  $18 , 0 , 100e f,
create table-31  $1 , -1 , 100e f,
create table-32  $17 , 1 , 100e f,
create table-33  $9 , -1 , 50e f,  $17 , 1 , 70e f,  $17 , 3 , 90e f,  $17 , 5 , 100e f,
create tables  table-0 , table-1 , table-2 , table-3 , table-4 , table-5 , table-6 , table-7 , table-8 , table-9 , table-10 , table-11 , table-12 , table-13 , table-14 , table-15 , table-16 , table-17 , table-18 , table-19 , table-20 , table-21 , table-22 , table-23 , table-24 , table-25 , table-26 , table-27 , table-28 , table-29 , table-30 , table-31 , table-32 , table-33 ,
: table ( situation hard? -- addr )  if  17 +  then  cells tables + @ ;
3 cells constant /row   \ (kind, argument, percentage: a cell each)

\ his moves: animation, bone, second bone (-1 none), reach, kind (2 a blow, 4 a hard one,
\ 3 a seize, 6 a hold), damage, threat, stumble chance, turns with it, cry (-1 none)
10 cells constant /move
create moves
    $E00 , $12 , 20 , 5e f, 2 , 15 , 10e f, 0e f, 1 , $B ,
    $E01 , $1C , 30 , 5e f, 2 , 30 , 15e f, 0e f, 1 , $B ,
    $E02 , $12 , 20 , 5e f, 4 , 30 , 25e f, 50e f, 1 , $C ,
    $E03 , $9 , 7 , 5e f, 4 , 15 , 15e f, 50e f, 1 , $C ,
    $205 , $17 , -1 , 5e f, 4 , 50 , 50e f, 100e f, 1 , $C ,
    $2300 , $2 , -1 , 20e f, 6 , 0 , 15e f, 0e f, 0 , -1 ,
    $2301 , $2 , -1 , 25e f, 6 , 0 , 20e f, 0e f, 0 , -1 ,
    $2302 , $1 , -1 , 20e f, 6 , 0 , 15e f, 0e f, 0 , -1 ,
    $1306 , $1 , -1 , 0e f, 6 , 0 , 0e f, 0e f, 0 , -1 ,
    $1305 , $1 , -1 , 0e f, 6 , 0 , 0e f, 0e f, 0 , -1 ,
    $1A00 , $1 , -1 , 0e f, 6 , 0 , 0e f, 0e f, 0 , -1 ,
    $E04 , $1E , 28 , 5e f, 3 , 50 , 30e f, 0e f, 0 , $D ,
    $E05 , $1E , 20 , 5e f, 3 , 50 , 30e f, 0e f, 0 , $D ,
    $1702 , $9 , 7 , 5e f, 4 , 15 , 20e f, 30e f, 0 , -1 ,
create combos  0 , -1 , -1 , -1 ,  1 , -1 , -1 , -1 ,  2 , -1 , -1 , -1 ,  3 , -1 , -1 , -1 ,  5 , -1 , -1 , -1 ,  6 , -1 , -1 , -1 ,  7 , -1 , -1 , -1 ,  11 , -1 , -1 , -1 ,  12 , -1 , -1 , -1 ,  0 , 1 , 2 , -1 ,  1 , 1 , 0 , -1 ,  1 , 0 , 1 , 2 ,  1 , 3 , 11 , -1 ,  0 , 3 , -1 , -1 ,  8 , 9 , -1 , -1 ,  0 , 1 , -1 , -1 ,
create gestures  $1 , 1 ,  $1302 , 1 ,  $1306 , 0 ,  $1303 , 1 ,  $1304 , 0 ,  $1305 , 1 ,  $1300 , 0 ,  $1307 , 0 ,

\ his chase table (+0x17F0): frames by offset 0..$20, chances at $24 $28 $2C
create chase-frames  90 , 60 , 90 , 60 , 90 , 60 , 90 , 60 , 90 ,
create chase-chances  50e f, 75e f, 75e f,
\ a lunge's chance by how near she is (Pursuer_ThresholdEntry): within, chance
create lunge-chances  15e f, 100 ,  30e f, 40 ,  60e f, 20 ,
