\ story/words.fs - the words the rooms' event scripts are written in (docs/subsystems/story.md):
\ one per command and condition of the original bytecode (the old new-src's events/words.fs has
\ the reference meanings; docs/event_opcodes.md the opcodes). The scripts run as their room's
\ actor: what they change of the room is its fields; what they ask of others goes as messages;
\ what they read of others are facts (bodies, the progress, the nav mesh) or what they were told.
\
\ Written so far: flags and variables, the script context and its waits, actions, characters
\ in areas and on triangles, exits, the camera, doors, the nav mesh's groups, sounds. The rest
\ is at the end (generated by tools/story_stubs.py): each says once that it isn't written yet
\ and does nothing (a condition: false).
IN: story.words
USING: engine game-state actors messages common keys doors room-names flag-names story-names story.state story.strings effects ;

\ ---- the registered scripts (data: each room's phases and actions, the shared ones) ----
$110 constant #rooms
create room-scripts    #rooms 7 * cells allot     room-scripts #rooms 7 * cells 0 fill
create action-scripts  #rooms $80 * cells allot   action-scripts #rooms $80 * cells 0 fill
create shared-scripts  $80 cells allot            shared-scripts $80 cells 0 fill
\ phases: 0 entering, 1 / 2 each frame (before / after the commands), 3 each frame's end, 4
\ leaving, 5 left (the next room in), 6 a character entering
: room-script ( room phase -- addr )  swap 7 * + cells room-scripts + ;
: action-script ( room id -- addr )  swap $80 * + cells action-scripts + ;
: room-script! ( xt room phase -- )  room-script ! ;
: action-script! ( xt room id -- )  action-script ! ;
: builtin-script! ( xt id -- )  $80 - cells shared-scripts + ! ;
: script-for ( act -- xt | 0 )   \ (an action of this room, or a shared one from 0x80)
    dup $80 < if  this-room @ swap action-script @  else  $80 - $7F and cells shared-scripts + @  then ;

\ ---- not written yet: said once a word, then nothing ----
create missing 16 1024 * allot  variable #missing
: place ( addr len dest -- )  2dup c!  1+ swap move ;   \ (a counted string)
: cstring ( addr -- addr' len )  dup 1+ swap c@ ;
: missing? ( addr len -- flag )
    #missing @ 0 ?do  2dup missing i 32 * + cstring compare 0= if  2drop true unloop exit  then  loop  2drop false ;
: stub-step ( addr len -- )
    2dup missing? if  2drop exit  then
    #missing @ 512 < if  2dup 31 min missing #missing @ 32 * + place  1 #missing +!  then
    ." story: " type ."  - not written yet" cr ;
: stub-flag ( addr len -- flag )  stub-step false ;
: .missing ( -- )  #missing @ 0 ?do  missing i 32 * + cstring type space  loop  cr ;

\ ---- small things ----
: bit ( n addr -- mask addr' )  over 5 rshift 4 * +  swap 31 and 1 swap lshift swap ;
: bit? ( n addr -- flag )  bit l@ and 0<> ;
: bit-on ( n addr -- )  bit dup l@ rot or swap l! ;
: bit-off ( n addr -- )  bit dup l@ rot invert and swap l! ;
: deg ( F: a -- d )  180e f* pi f/ ;
: b0 ( -- ) ;   : b1 ( -- ) ;   : b2 ( -- ) ;   : b3 ( -- ) ;   : b4 ( -- ) ;   \ (the converter's byte markers)

\ ---- the script running now ----
: in-slot? ( -- flag )  ctx-slot @ 0< 0= ;
: self-char ( -- cs )  ctx-who @ ;
: self-frames ( -- addr )  in-slot? if  ctx-slot @ cells slot-frames +  else  phase-frames  then ;
: wait-frame ( -- )  in-slot? if  yield  then ;
: wait-until ( xt -- )   \ (a phase script can't wait: it looks once)
    in-slot? 0= if  drop exit  then  begin  dup execute 0= while  yield  repeat  drop ;

\ ---- the characters, by the scripts' slots (0 Fiona, 1 Hewie; the others with the stalkers) ----
: fiona-id ( -- id )  s" fiona" actor-named ;
: hewie-id ( -- id )  s" hewie" actor-named ;
: char-actor ( cs -- id | -1 )
    case
        0 of  fiona-id  endof
        1 of  hewie-id  endof
        >r -1 r>
    endcase  dup body? 0= if  drop -1  then ;
\ a script id to a slot: 0 Fiona, 1 Hewie, 0xFF the script's own (-1: nobody)
: char-slot ( id -- cs | -1 )
    dup $FF = if  drop self-char exit  then
    dup 0 2 within if  exit  then  drop -1 ;
: char-here ( cs -- flag )   \ in the game and in this room
    dup 0< if  drop false exit  then  char-actor dup 0< if  drop false exit  then  body-room this-room @ = ;
: in-room? ( cs -- flag )  char-here ;
: char-at ( cs -- v )  char-actor body-at ;
: char-was ( cs -- v )  12 * char-was + ;
: char-in-area ( cs area -- flag )  swap char-at vec@ area-in? ;
\ crossing an area since the last frame: 1 into it, -1 out of it, 0 neither
: char-cross ( cs area -- n )
    over cells char-seen + @ 0= if  2drop 0 exit  then
    >r dup char-was vec@ char-at vec@ r> area-cross ;
\ (each frame's end: where they are, for the next frame's crossings)
: remember-chars ( -- )
    #chars 0 do
        i char-here if  i char-was i char-at vec-copy  -1 i cells char-seen + !
        else  0 i cells char-seen + !  then
    loop ;
: who>cs ( who -- cs | -1 )   \ (a character argument: 0xFF self)
    dup $FF = if  drop self-char  else  char-slot  then ;

\ ---- 0x00 .. : flags, variables, bits, the counter, chance ----
: story-flag? ( n -- flag )  progress pr.story bit? ;
: story-flag-set ( n -- )  progress pr.story bit-on ;
: story-flag-clear ( n -- )  progress pr.story bit-off ;
: state-flag? ( n -- flag )  progress pr.state bit? ;
: state-flag-set ( n -- )  progress pr.state bit-on ;
: state-flag-clear ( n -- )  progress pr.state bit-off ;
: resident-flag? ( n -- flag )  progress pr.resident bit? ;
: resident-flag-set ( n -- )  progress pr.resident bit-on ;
: pvar? ( n v -- flag )  swap progress pr.vars + c@ = ;
: pvar-set ( n v -- )  swap progress pr.vars + c! ;
: pvar-inc ( n -- )  progress pr.vars + dup c@ 1+ swap c! ;
: pvars-equal? ( a b -- flag )  progress pr.vars + c@ swap progress pr.vars + c@ = ;
: var ( var -- addr )  #vars 1- and cells vars + ;
: var-set ( var v -- )  swap var ! ;
: var? ( var v -- flag )  swap var @ = ;
: var-inc ( var -- )  var 1 swap +! ;
: var-dec ( var -- )  var -1 swap +! ;
: ebit? ( n -- flag )  1 swap 31 and lshift ebits @ and 0<> ;
: ebit-set ( n -- )  1 swap 31 and lshift ebits @ or ebits ! ;
: ebit-clear ( n -- )  1 swap 31 and lshift invert ebits @ and ebits ! ;
: counter-set ( n -- )  counter ! ;
: counter-inc ( -- )  1 counter +! ;
: counter? ( n -- flag )  counter @ = ;
: wait-counter ( n -- )   \ (an action script waits for it)
    in-slot? 0= if  drop exit  then  begin  counter @ over <> while  yield  repeat  drop ;
: result? ( v -- flag )  result @ = ;
: chance? ( pct -- flag )
    dup 100 >= if  drop true exit  then  dup 1 < if  drop false exit  then  100 random > ;
: game-mode? ( mode -- flag )  the-danger @ = ;
: panic-stage? ( stage -- flag )   \ (0xFF: panicking, 4 or 5)
    dup $FF = if  drop the-panic @ 4 6 within  else  the-panic @ =  then ;
: panic-stage ( stage -- )  s" panic" actor-named send panic-stage! ;
: hewie-controlled? ( -- flag )  false ;   \ (the Hewie-controlled sections: H4)

\ ---- waiting (an action script's turn ends, each frame) ----
: yield ( -- )  wait-frame ;
: frames? ( n -- flag )  self-frames @ $FFFF and = ;
: self-frames-reset ( -- )  0 self-frames ! ;
: self-wait-frames ( n -- )
    in-slot? 0= if  drop exit  then  begin  self-frames @ over < while  yield  repeat  drop ;
: self-wait-16 ( -- )  16 self-wait-frames ;

\ ---- actions: the action scripts in their slots (Event_StartAction, Events_GiveScript) ----
: scene-id? ( id -- flag )  $FF and $F0 $FB within ;
: slot-of ( id -- k )  $FF and $F0 - 6 + ;     \ (a scene's slot: 6..16)
: slot-task ( k -- addr )  cells slot-tasks + ;
: free-slot ( k -- )
    dup slot-task @ ?dup if  forth:kill  then
    0 over slot-task !  -1 over cells slot-who + !  -1 over cells slot-ids + !  0 swap cells slot-frames + ! ;
: free-slots ( -- )  #slots 0 do  i free-slot  loop ;
: fill-slot ( xt who id k -- )
    >r  r@ cells slot-ids + !  r@ cells slot-who + !  0 r@ cells slot-frames + !
    r@ slot-task @ ?dup if  forth:kill  then
    spawn-held r> slot-task ! ;
: start-action ( id act -- )   \ a scene script: its own slot, no character
    script-for ?dup 0= if  drop exit  then  swap  -1 swap  dup slot-of  fill-slot ;
: give-script ( cs act -- )   \ a character's: slot cs + 1, as itself
    script-for ?dup 0= if  drop exit  then  swap  dup  over 1+  fill-slot ;
: tell-scripted ( cs on -- )   \ (the character told: a script of the room has it, or lets go)
    swap char-actor dup 0< if  2drop exit  then  send scripted ;
: release ( cs -- )   \ (its script is over: free again)
    dup cells char-scripted + @ 0= if  drop exit  then
    0 over cells char-scripted + !  0 tell-scripted ;
: char-action ( cs act -- )
    over cells char-scripted + @ 0= if  over -1 tell-scripted  then
    -1 2 pick cells char-scripted + !  give-script ;
: start-for ( mode who act force -- )
    leaving @ if  2drop 2drop exit  then
    >r rot drop                                     ( who act )  ( R: force )
    over scene-id? if
        over slot-of slot-task @ 0=  r> or  if  start-action  else  2drop  then  exit
    then
    swap char-slot dup 0< if  2drop r> drop exit  then    ( act cs )
    swap  r> if  char-action exit  then
    over cells char-scripted + @ 0= if  char-action  else  2drop  then ;
: action ( mode who act -- )  false start-for ;
: action-force ( mode who act -- )  true start-for ;
: end-for ( who -- )
    dup scene-id? if  slot-of free-slot exit  then
    char-slot dup 0< if  drop exit  then
    dup release  1+ free-slot ;
: action-end ( who -- )  end-for ;
\ the script's character idle again (with none: the script ends) - its turn ends
: self-idle-or-end ( -- )
    in-slot? 0= if  exit  then
    self-char dup 0< 0= if
        dup release
        msg-owner @ = if  -1 msg-owner !  then
    else  drop  then
    ctx-slot @ free-slot ;   \ (the task is gone: nothing after this runs)
: goto ( xt -- )  in-slot? if  0 self-frames !  restart  else  execute  then ;
: goto-action ( id -- )  script-for ?dup if  goto  then ;
: call-action ( id -- )  script-for ?dup if  execute  then ;

\ ---- characters: where they are ----
: self-is? ( id -- flag )
    dup $FE = if  drop false exit  then   \ (the active stalker: H3)
    ctx-id @ = ;
: char-here? ( id -- flag )  char-slot char-here ;
: char-busy? ( who -- flag )   \ (a scene's slot running, or a character in a scripted action)
    dup scene-id? if  slot-of slot-task @ 0<> exit  then
    char-slot dup 0< if  drop false exit  then  cells char-scripted + @ 0<> ;
: char-in-area? ( who area -- flag )
    swap char-slot dup char-here 0= if  2drop false exit  then  swap char-in-area ;
: char-entered-area? ( who area -- flag )
    swap char-slot dup char-here 0= if  2drop false exit  then  swap char-cross 1 = ;
: char-left-area? ( who area -- flag )
    swap char-slot dup char-here 0= if  2drop false exit  then  swap char-cross -1 = ;
: char-on-tri? ( who tri -- flag )
    swap char-slot dup char-here 0= if  2drop false exit  then  char-actor body-tri = ;
: char-in-room? ( who room -- flag )
    swap char-slot dup 0< if  2drop false exit  then  char-actor dup 0< if  2drop false exit  then  body-room = ;
\ faces heading dir x 2 degrees (a signed byte), within `within` degrees
: char-heading? ( who dir within -- flag )
    rot char-slot dup char-here 0= if  drop 2drop false exit  then
    char-actor body-yaw angle-wrap deg  swap $FF and dup $80 and if  $100 -  then  2* s>f f-  fabs
    fdup 180e f> if  360e fswap f-  then  s>f f<= ;

\ ---- exits (cmd_exit, Progress_ExitOpen / ExitPassable) ----
: exit-door ( exit -- door | -1 )  this-room @ swap room-exit-door ;
: door-state ( door -- w )  4 * progress pr.doors + l@ ;
: exit-open ( exit -- flag )   \ a doorway, or a door not locked with its open bit
    exit-door dup 0< if  drop false exit  then
    dup door-flags 1 and if  drop true exit  then
    door-state dup 8 and if  drop false exit  then  2 and 0<> ;
: exit-passable ( exit -- flag )  exit-door dup 0< if  drop false exit  then  door-state $10 and 0= ;
\ take exit `exit` after this frame (bit 7: whatever its door; else if it is open to whoever is
\ controlled - Fiona, free of scripts)
: exit-check ( exit -- )
    dup $80 and if  $7F and dup exit-taken !  going !  -1 leaving !  exit  then
    dup exit-door dup 0< 0= if  door-locked? if  drop exit  then  else  drop  then
    dup exit-passable 0= if  drop exit  then
    0 cells char-scripted + @ if  drop exit  then
    dup exit-taken !  going ! ;
: exit-prepare ( exit -- )  drop ;   \ (the next room loaded ahead: rooms come in at once here)
: exit-usable? ( exit -- flag )   \ Fiona free (no script, moving on her own or 0xA), in the exit's
    0 cells char-scripted + @ if  drop false exit  then          \ area, its door open and not held
    fiona-mode @ dup 0<> swap $A <> and if  drop false exit  then
    0 char-here 0= if  drop false exit  then
    0 over exit-area char-in-area 0= if  drop false exit  then
    dup exit-open 0= if  drop false exit  then
    exit-door door-held? 0= ;
: exit-taken? ( exit -- flag )  exit-taken @ = ;
: exit-door-open? ( exit -- flag )  exit-open ;
\ a character put on the exit's outside spot, facing in (Rooms_ExitPointOut)
: char-to-exit ( who exit -- )
    swap who>cs char-actor dup 0< if  2drop exit  then  send to-exit ;

\ ---- the camera (Progress_CameraSetup / CameraFollow) ----
: camera-id ( -- id )  s" camera" actor-named ;
: char-cam! ( cs set path -- )   \ (a character not in this room gets none; Fiona always)
    rot dup 0< if  drop 2drop exit  then
    dup 0= over char-here or 0= if  nip nip -1 -1 rot  then
    char-actor dup 0< if  drop 2drop exit  then  -rot camera-id send camera-setup ;
: char-camera ( id set path -- )  rot char-slot -rot char-cam! ;
: camera-follow ( id -- )
    dup $FF = if  drop $FF camera-char !  -1 camera-id send follow exit  then
    char-slot dup 0< if  drop exit  then
    dup camera-char !  char-actor camera-id send follow ;
\ the characters in this room inside the area of exit `exit`
: area-camera ( exit set path -- )
    rot exit-area -rot
    #chars 0 do
        i char-here if  i 3 pick char-in-area if  i 2 pick 2 pick char-cam!  then  then
    loop  2drop drop ;
\ each character whose crossing of area `area` is `rel` (1 into it, -1 out of it, 0 neither)
: chars-area-camera ( area set path rel -- )
    #chars 0 do
        i char-here if
            i 4 pick char-cross over = if  i 3 pick 3 pick char-cam!  then
        then
    loop  2drop 2drop ;
: camera-restart ( -- )  camera-id send camera-restart ;

\ ---- doors ----
: door-bits ( a set b -- )  drop 2drop ;   \ (which parts of the room's door models are drawn: not drawn yet)
: doors-id ( -- id )  s" doors" actor-named ;
: door-lock ( door -- )  doors-id send lock ;
: door-unlock ( door -- )  doors-id send unlock ;
: door-not-closed-off? ( door -- flag )
    dup 0 door-count within 0= if  drop true exit  then  progress pr.closed-off bit? 0= ;

\ ---- the nav mesh's flag groups (the room's: its scripts open and close ways) ----
: nav-group ( set group bits -- )  rot 1 = -rot nav-group! ;
: nav-tri-flags ( set tri bits -- )  rot 1 = -rot nav-tri-flags! ;

\ ---- sounds and noises ----
variable snd-vol  variable snd-pitch
: sound ( id bank vol pitch F: x y z -- )   \ (cmd_sound: the bank's top bits say where - 2 plainly, 1 at the camera)
    snd-pitch !  snd-vol !  dup 6 rshift swap $3F and swap                 ( id bank where )
    dup 2 = if  drop fdrop fdrop fdrop bank-sound exit  then
    drop  snd-vol @ snd-pitch @ sound-at ;
: char-sound ( who id bank -- )   \ (Actor_PlaySound: at the character)
    rot who>cs dup char-here 0= if  drop 2drop exit  then
    char-at vec@  0 0 sound-at ;
: acoustics-id ( -- id )  s" acoustics" actor-named ;
: noise ( loud tri -- )  this-room @ swap -1 world-noise acoustics-id send noise ;
: room-sounds ( -- )  0 $1B0C00 sound-stop-voices  6 sound-load ;   \ (Progress_LoadRoomSounds)

\ ---- placing characters (the story puts them: a message to each) ----
: place-char ( cs F: x y z yaw -- )
    char-actor dup 0< if  drop fdrop fdrop fdrop fdrop exit  then
    >r  f>cell >r  f>cell >r  f>cell >r  f>cell  r> r> r> r>  send place ;
fvariable at-y  fvariable keep-yaw
: char-to-tri ( who tri -- )   \ (on the triangle's middle, its heading kept)
    swap who>cs dup char-actor dup 0< if  drop 2drop exit  then
    body-yaw keep-yaw f!  swap tri-center  keep-yaw f@  place-char ;
: char-to-tri-facing ( who tri face -- )
    rot who>cs dup 0< if  2drop drop exit  then
    rot tri-center  swap s>f deg>rad  place-char ;
fvariable at-x  fvariable at-z
: char-to-xz ( who tri face F: x z -- )   \ (at the triangle's height: its middle's)
    at-z f!  at-x f!
    rot who>cs dup 0< if  drop 2drop exit  then                ( tri face cs )
    rot tri-center fdrop at-y f! fdrop
    at-x f@ at-y f@ at-z f@  swap s>f deg>rad  place-char ;
: char-to-xyz ( who face F: x y z -- )
    swap who>cs dup 0< if  2drop fdrop fdrop fdrop exit  then  swap s>f deg>rad  place-char ;

\ ---- the room's look (its fog and colours: a room effect's parameters, RoomEffects_Send) ----
create effect-bytes 64 allot  variable #effect-bytes
: effect-string ( fx text.. n -- )
    dup 64 min #effect-bytes !
    0 ?do  i #effect-bytes @ < if  effect-bytes #effect-bytes @ i - 1- + c!  else  drop  then  loop
    effect-bytes #effect-bytes @ look-set ;

\ ==== S2: messages, examining, items, zones ====

\ an item or room as the scripts see it (Events_ScriptRoom)
: script-item ( id -- id' )  items-40-as-70 story-flag? over $40 - 2 u< and if  drop $70  then ;

\ ---- the message window (the window actor shows it; its closing comes back as text-closed) ----
: window-id ( -- id )  s" window" actor-named ;
: message ( msg -- )   \ (bit 0x4000: the second language table - not this one's)
    $4000 invert and  dup msg !  self-char msg-owner !  window-id send show-text ;
: wait-message ( -- )   \ (an action script waits while it is open)
    in-slot? 0= if  exit  then  begin  msg @ 0< 0= while  yield  repeat ;
: message-close ( msg -- )
    dup $FFFF = over msg @ = or if  window-id send close-text  -1 msg !  -1 prepared-msg !  -1 prepared-page !  else  drop  then ;
: message-prepare ( msg -- )  dup $FFFF = if  drop -1  then  prepared-msg !  -1 prepared-page ! ;   \ (a scene's subtitles: 0x62 12 turns its pages)
: answer? ( v -- flag )  msg @ 0< swap answer @ = and ;
: message-param-room ( n -- )  0 swap script-item message-param! ;   \ (parameter 0: that system message)

\ ---- what she does with the pad (the scripts' 0x21: her command; 0x15: a button) ----
: control-action? ( v -- flag )  fiona-cmd @ = ;   \ (her gesture this frame: 0 up .. 4 left)
: pad? ( button how -- flag )   \ (how: 1 held, 2 just pressed; button bit 7 - her shake - not kept yet)
    swap $7F and swap  2 and if  button-pressed?  else  button-down?  then ;

\ ---- facing (cond_deg: how far a character turns from its heading to face a point) ----
fvariable fx  fvariable fz
: faces-off ( cs -- ) ( F: x z -- deg )
    fz f! fx f!  char-actor dup body-pos fswap fdrop                ( id ) ( F: cx cz )
    fz f@ fswap f-  fswap fx f@ fswap f-  fswap fatan2             ( id ) ( F: heading )
    body-yaw f- angle-wrap deg fabs ;
: char-faces-xz? ( who x z within -- flag )
    >r  s>f s>f fswap  char-slot dup char-here 0= if  drop fdrop fdrop r> drop false exit  then
    faces-off  r> s>f f<= ;
: char-faces-area? ( who area within -- flag )   \ (inside the area, facing its middle)
    rot char-slot dup char-here 0= if  drop 2drop false exit  then          ( area within cs )
    rot 2dup char-in-area 0= if  2drop drop false exit  then                ( within cs area )
    area-middle drop  fswap fdrop  faces-off  s>f f<= ;
: char-action? ( who v -- flag )   \ (its move mode: +0xF8)
    swap char-slot case
        0 of  fiona-mode @ =  endof
        1 of  hewie-move-mode @ =  endof
        >r drop false r>
    endcase ;

\ ---- zones: cylinders the scripts set each frame (+0xBF0; all off as phase 1 starts) ----
: zone# ( z -- addr )  /zone * zones + ;
: zones-off ( -- )  zones #zones /zone * 0 fill ;
: zone ( z r h kind F: x y z -- )   \ (0x7C: on, kind; centre, radius, height - either way up)
    3 pick #zones u< 0= if  2drop 2drop fdrop fdrop fdrop exit  then
    3 pick zone# >r  r@ 4 + l!  s>f r@ 24 + sf!  s>f r@ 20 + sf!  drop
    r@ 16 + sf!  r@ 12 + sf!  r@ 8 + sf!  1 r> l! ;
: zone-rect ( z id F: x0 z0 x1 z1 -- )   \ (0x8D: for the scene effects)
    over #zones u< 0= if  2drop fdrop fdrop fdrop fdrop exit  then
    swap 5 cells * zone-rects + >r  r@ !
    r@ 4 cells + sf!  r@ 3 cells + sf!  r@ 2 cells + sf!  r> cell+ sf! ;
\ Zone_TestCylinder: a point with radius r and height h against zone z: 1 they overlap in height,
\ 4 it is within it in height, 2 they overlap across, 8 its centre is inside across
fvariable zr  fvariable zh  fvariable zx  fvariable zy  fvariable zz  fvariable zdy
: zone-test ( z -- bits ) ( F: x y z r h -- )
    zh f! zr f! zz f! zy f! zx f!
    zone# dup l@ 0= if  drop 0 exit  then  >r
    zy f@ zh f@ 2e f/ f+  r@ 12 + sf@ r@ 24 + sf@ 2e f/ f+  f- fabs zdy f!
    0
    zdy f@  r@ 24 + sf@ fabs zh f@ fabs f+ 2e f/  f<= if  1 or  then
    zdy f@  r@ 24 + sf@ fabs zh f@ fabs f- 2e f/  f<= if  4 or  then
    r@ 16 + sf@ zz f@ f- fdup f*  r@ 8 + sf@ zx f@ f- fdup f* f+       ( bits ) ( F: d2 )
    fdup  r@ 20 + sf@ zr f@ f+ fdup f* f<= if  2 or  then
    r> 20 + sf@ fdup f* f<= if  8 or  then ;
: char-zone-bits? ( who zone bits -- flag )   \ (its radius and height against the zone: all of bits)
    rot char-slot dup char-here 0= if  drop 2drop false exit  then
    dup char-at vec@  char-actor body-dims  swap zone-test over and = ;
: char-zone-bits-before? ( who zone bits -- flag )   \ (as it was at the last frame's end)
    rot char-slot dup char-here 0= if  drop 2drop false exit  then
    dup char-was vec@  char-actor body-dims  swap zone-test over and = ;
\ whose attack point (Fiona's kick, Hewie's bite: their PointOfInterest) is in the zone - with
\ the kicks (Fiona F4) and his bites (H3): until then nobody's
: char-in-zone? ( who zone -- flag )  2drop false ;

\ ---- the action prepared (cmd_scene_change, 0x0A): kept for this frame; scene 5 is an action
\ script for Fiona, taken with the action button; the others change the scene (S4) ----
: prepare ( scene arg kind -- )  prep-kind !  prep-arg !  prep-scene ! ;
: scene-change ( scene arg kind -- )
    prep-scene @ 5 =  scene-locked state-flag? or  0 cells char-scripted + @ or if  2drop drop exit  then
    the-panic @ 4 >=                                            ( scene arg kind late? )
    over case
        0 of  0= the-danger @ 2 <> and  endof   \ (chased: the pending ending instead - S4)
        1 of  drop true  endof   7 of  drop true  endof
        3 of  0=  endof                              \ (with Hewie's partner state: S4)
        >r 0= r>
    endcase
    0= if  2drop drop exit  then
    2 pick 5 = 0 cells char-scripted + @ and if  2drop drop exit  then
    prepare ;
: scene-request? ( v -- flag )  prep-scene @ = ;

\ ---- items (the progress' inventory: counts, and the files - key things, documents) ----
: item# ( id -- addr | 0 )  dup 0 $100 within if  progress pr.items +  else  drop 0  then ;
: items-of ( id -- n )  item# dup if  c@  then ;
: items+ ( id n -- )   \ (up to 99)
    swap item# dup 0= if  2drop exit  then  dup c@ rot + 0 max 99 min swap c! ;
: file-add ( id -- flag )   \ SubScreen_AddFile: true if added (false: already there, or full)
    $FFFF and  128 0 do
        progress pr.files i 2* + dup w@                     ( id addr v )
        dup 3 pick = if  2drop drop false unloop exit  then
        0= if  w! true unloop exit  then  drop
    loop  drop false ;
: item-give ( item -- )   \ (with the pickup sound; bit 0x8000: the hard mode's - not given here)
    dup $8000 and if  drop exit  then  file-add if  $C 5 bank-sound  then ;
: item-add ( item -- )  file-add drop ;
: item-count? ( item n -- flag )  swap script-item items-of swap < 0= ;
: item-give-count ( item n -- )   \ (0x83: counted - the progress' items counted - and given)
    progress pr.items-counted dup l@ 1+ swap l!  swap script-item swap items+ ;
: item-use ( item -- )  dup items-of 0> if  -1 items+  else  drop  then ;

\ ==== S3: the characters' moves (+0xF4: each carries out its own; +0xE1 its done) ====
: cs>who ( id -- cs )   \ (an actor to its slot: -1 none)
    dup fiona-id = if  drop 0 exit  then  dup hewie-id = if  drop 1 exit  then  drop -1 ;
: char-flag ( cs addr -- flag )  swap cells + @ ;
\ CHAR_ACT: a move given (its done cleared until it says so); the move in mv-* (scratch)
variable mv-kind  variable mv-a  variable mv-b  create mv-at 12 allot  fvariable mv-yaw
: send-move ( cs -- )
    dup char-actor dup 0< if  2drop exit  then  >r
    0 over cells move-done-of + !  0 swap cells anim-ended-of + !
    mv-kind @ mv-a @ mv-b @  mv-at sf@ f>cell  mv-at 4 + sf@ f>cell  mv-at 8 + sf@ f>cell  mv-yaw f@ f>cell
    r> send scripted-move ;
: self-move ( kind a b F: x y z yaw -- )   \ (the script's own character)
    mv-yaw f!  mv-at vec!  mv-b !  mv-a !  mv-kind !
    self-char dup char-here if  send-move  else  drop  then ;
: opt16 ( v -- v' )  dup $FFFF = if  drop -1  then ;
fvariable tfx  fvariable tfz
: tri-floor ( tri F: x z -- x y z )   \ (on the triangle: its middle's height)
    tfz f!  tfx f!  tri-center fdrop at-y f! fdrop  tfx f@ at-y f@ tfz f@ ;
: self-yaw ( F: -- yaw )  self-char char-actor dup 0< if  drop 0e  else  body-yaw  then ;
fvariable hx  fvariable hz
: heading-from-self ( F: x z -- yaw )
    hz f!  hx f!  self-char char-actor dup 0< if  drop 0e exit  then
    body-pos fswap fdrop  hz f@ fswap f-  fswap hx f@ fswap f-  fswap fatan2 angle-wrap ;
fvariable mx  fvariable mz
: self-move-to ( tri face tri2 move F: x z -- )   \ 0x0C: to (x, z) on tri, then face
    mz f!  mx f!  >r opt16 swap s>f deg>rad angle-wrap mv-yaw f!  r> -rot   ( move tri tri2 )
    over mx f@ mz f@ tri-floor  mv-yaw f@  self-move ;
: self-move-tri ( tri tri2 move -- )   \ 0x0E: along a path to tri (6 / 11 / 17)
    rot dup tri-center  self-yaw  swap >r swap opt16 r> -rot  self-move ;
: self-idle ( -- )  2 0 -1  0e 0e 0e 0e  self-move ;   \ 0x0F
: self-anim ( anim -- )  7 swap -1  0e 0e 0e 0e  self-move ;   \ 0x07
: self-anim-blend ( anim b -- )  8 -rot  0e 0e 0e 0e  self-move ;   \ 0x81
: self-anim-9 ( anim b -- )  9 -rot  0e 0e 0e 0e  self-move ;   \ 0xA4
: self-move-16 ( v -- )  16 0 rot  0e 0e 0e 0e  self-move ;   \ 0xC7: her idle, v
: self-turn-angle ( face -- )   \ 0x4B
    s>f deg>rad angle-wrap mv-yaw f!  15 0 -1  0e 0e 0e mv-yaw f@  self-move ;
: self-turn-to-xz ( F: x z -- )   \ 0x8E
    heading-from-self mv-yaw f!  15 0 -1  0e 0e 0e mv-yaw f@  self-move ;
: self-turn-to ( id -- )   \ 0x42: to a character (move 14)
    char-slot char-actor dup 0< if  drop exit  then
    body-pos fswap fdrop  heading-from-self mv-yaw f!  14 0 -1  0e 0e 0e mv-yaw f@  self-move ;
: self-look-at ( id -- )   \ 0x2B: look at a character (0xFF: stop)
    dup $FF = if  drop -1  else  char-slot char-actor  then  12 swap -1  0e 0e 0e 0e  self-move ;
: self-look-at-point ( F: x y z -- )  13 0 -1  0e  self-move ;   \ 0xAB
: self-move-slot ( slot move -- )   \ 0x10: toward a character (14 turn to it, 12 look at it)
    dup 14 = if  drop self-turn-to exit  then  dup 12 = if  drop self-look-at exit  then
    2drop s" self-move-slot" stub-step ;
: self-walk-anim ( tri anim blend face F: x z -- )   \ 0xAA: walking the way with an animation
    s>f deg>rad angle-wrap mv-yaw f!  rot tri-floor  mv-yaw f@  17 -rot  self-move ;
\ the waits (0x0D: until its move is done; 0x08: until its animation has come round)
: self-wait-done ( -- )
    in-slot? 0= if  exit  then  self-char dup char-here 0= if  drop exit  then
    begin  dup move-done-of char-flag 0= while  yield  repeat  drop ;
: self-wait-anim ( -- )
    in-slot? 0= if  exit  then  self-char dup char-here 0= if  drop exit  then
    begin  yield  dup anim-ended-of char-flag until
    -1 swap cells move-done-of + ! ;
: wait-char-anim ( id -- )   \ 0x9E
    char-slot dup char-here 0= if  drop wait-frame exit  then
    begin  wait-frame  dup anim-ended-of char-flag  until  drop ;
: char-anim-hold ( id anim blend speed -- )   \ 0x9D: playing it, held (the speed: later)
    drop  rot char-slot char-actor dup 0< if  drop 2drop exit  then  send hold-anim ;
: char-visible ( who on -- )   \ 0x1F: shown or hidden, if in this room
    swap who>cs dup char-here 0= if  2drop exit  then  char-actor send show ;

\ ==== S4: fades, movies, cutscenes, music ====

\ ---- the screen fade (the screen actor's; it tells the room when it is over) ----
: screen-id ( -- id )  s" screen" actor-named ;
: music-id ( -- id )  s" music" actor-named ;
\ 0x5C: over `frames` frames; kind & 0xF: 0 / 1 in, else out. (Bits 0xC0 / 0x30 fade the music
\ with it in the original: not yet.)
: fade ( frames kind -- )  over 0> fading !  $F and screen-id send fade ;
: fade-finish ( -- )  0 fading !  screen-id send fade-finish ;   \ 0x5D
: fade-over ( -- )  fade-finish ;                                \ 0x5E
: wait-fade ( -- )   \ 0x5F (a phase script looks once)
    in-slot? 0= if  exit  then  begin  fading @ while  yield  repeat ;

\ ---- the movie (one at a time: the engine's) ----
\ its state, as the scripts' result: -1 none, 1 running, 2 paused
: movie-state ( -- n )  movie-status 1 <> if  -1  else  movie-paused? if  2  else  1  then  then ;
\ the class picks how the picture is laid over the screen: Sofdec's compo modes - 1 by a luminance
\ key, 3 by the frame's own alpha, 6 three-level, else opaque
: class>compo ( class -- compo )  case  1 of $31 endof  3 of $21 endof  6 of $41 endof  $11 swap  endcase ;
: movie-play ( name class -- )   \ 0x60: the room's string `name`, paused until its volume is set (0xCF)
    movie-kind !  0 result !
    this-room @ room-string movie-open drop  1 movie-pause
    movie-kind @ class>compo $10 $20 movie-compose ;
: movie-volume ( F: v -- )  movie-volume!  0 movie-pause ;      \ 0xCF (and it runs)
: movie-param ( a b -- )  -1 -rot movie-compose ;               \ 0x6E (the luminance key)
: movie-loop ( -- )  s" movie-loop" stub-step ;                 \ 0x52 (no looping movie in the engine yet)
: movie-playing? ( -- flag )  movie-state 0< 0= ;                \ cond 0x57
: movie-restart ( -- )   \ (waits while it runs; paused - ready: result 1; none: -1)
    begin  movie-state 1 = in-slot? and while  yield  repeat
    movie-state 0< if  -1  else  1  then  result ! ;

\ ---- the cutscene (the C director: its cast is the characters' models, cast-as) ----
: cutscene-start ( name -- )   \ 0x61: the room's scene named by string `name`; the characters told
    this-room @ room-string cutscene-load drop  -1 broadcast scene ;
: cutscene-over ( -- )  camera-restart  cutscene-end  movie-opaque state-flag-clear  0 broadcast scene ;
\ 0x62: 0 the movie's state into the result; 1 stop the movie; 2 restart it; 3 the director a step;
\ 4 that, and its shot played; 5 / 6 / 7 the cues (the next one; off; the movie's frame - its
\ signal 11 toggles movie-opaque); 8 the scene over (the camera back); 9 / 10 pause / resume the
\ movie; 11 a black screen over half (not drawn yet); 12 the prepared message's page turned as
\ often as the director says (its subtitles)
: cutscene-control ( op -- )
    case
        0 of  movie-state result !  endof
        1 of  movie-close  0 result !  endof
        2 of  movie-restart  endof
        3 of  cutscene-run  endof
        4 of  cutscene-run
              cutscene-status 5 <>  cutscene-in-shot? and if  cutscene-update  then  endof
        5 of  cutscene-frame cue-prev !  cutscene-frame 1+ cutscene-frame!  cutscene-frame cue !  endof
        6 of  -1 cue-prev !  -1 cue !  cutscene-go  cutscene-run  endof
        7 of  cue @ cue-prev !  movie-frame cue !  cue @ cutscene-frame!
              $B cutscene-signals 1 and if
                  movie-opaque state-flag? if  movie-opaque state-flag-clear  else  movie-opaque state-flag-set  then
              then  endof
        8 of  cutscene-over  endof
        9 of  movie-state 1 = if  1 movie-pause  then  endof
        $A of  movie-state 2 = if  0 movie-pause  then  endof
        $B of  endof
        $C of  8 cutscene-signals 0 ?do  1 prepared-page +!  loop  endof
    endcase ;
: cutscene-mode? ( mode -- flag )  cutscene-status = ;                 \ cond 0x20
: cutscene-cue-reached? ( cue -- flag )  cutscene-frame swap < 0= ;    \ cond 0x38
: cutscene-event? ( k -- flag )  cutscene-signals 0> ;                 \ cond 0x3A
: cutscene-passed? ( k at -- flag )   \ cond 0x3B: its counter for k passed `at` this step
    over cutscene-signals dup 0> 0= if  drop 2drop false exit  then     ( k at n )
    rot cutscene-signal-total                                          ( at n m )
    rot 2dup < if  2drop drop false exit  then                         ( n m at )
    >r swap - r> < ;
: cutscene-near-end? ( -- flag )  cutscene-near? ;                     \ cond 0x40
: cutscene-shot? ( shot -- flag )  cutscene-frame cutscene-shot-at = ; \ cond 0x4A

\ ---- music (the music actor's) ----
: bgm ( track pause F: vol -- )   \ 0x7E: $FF pause - the stream resumed
    dup $FF = if  2drop fdrop  music-id send bgm-resume exit  then
    f>cell music-id send bgm-want ;
: music ( op a b -- )  music-id send music-op ;          \ 0x6A
: music-stage ( stage -- )  music-id send music-stage ;   \ 0x6B
: music-stage-end ( -- )  -1 music-stage ;                \ 0x6C

\ ---- motion events (a character's motion's event keys, as it last told: bit $20 its mark) ----
: char-at-motion-event? ( id -- flag )   \ cond 0x56
    char-slot dup char-here 0= if  drop false exit  then  events-of char-flag $20 and 0<> ;
: self-at-motion-event? ( -- flag )   \ cond 0x48: no move going, at the mark - its move done
    self-char dup char-here 0= if  drop false exit  then
    dup move-done-of char-flag 0= if  drop false exit  then
    dup events-of char-flag $20 and 0= if  drop false exit  then
    -1 swap cells move-done-of + !  true ;

\ ---- drawing the scene's part (the room's, at its frame's end): the movie on layer 0, the
\ prepared message's page - the subtitles - on layer 4 ----
4 constant subtitle-layer
variable mx  variable my  variable mw  variable mh
: movie-area ( -- )   \ the 4:3 picture in the window
    screen-size  over 3 * 4 / over min  dup mh !  4 * 3 / mw !
    mh @ - 2/ my !  mw @ - 2/ mx ! ;
\ the classes that show it (src/game/movie.c): 1 keyed by its brightness, 2 opaque but only while
\ movie-opaque, 3 by its own alpha, 5 opaque - over the picture at 4:3; 6 a 256 x 64 strip at
\ (64, 176) of 512 x 448; 0 and 4 not drawn here
: draw-movie ( -- )
    0 ui-clear
    movie-status 1 <> if  exit  then
    movie-kind @ dup 0= swap 4 = or if  exit  then
    movie-kind @ 2 = movie-opaque state-flag? 0= and if  exit  then
    movie-area
    movie-kind @ 6 = if
        0  mx @ mw @ 64 * 512 / +  my @ mh @ 176 * 448 / +  mw @ 384 * 512 /  mh @ 96 * 448 /  ui-movie  exit
    then
    movie-kind @ dup 1 <> swap 3 <> and if  0  0 0 screen-size  $000000FF ui-rect  then   \ (the opaque ones)
    0  mx @ my @ mw @ mh @ ui-movie ;
variable sw  variable sh  variable lh
: draw-subtitles ( -- )
    subtitle-layer ui-clear
    msg @ 0< 0=  prepared-msg @ 0<  or  prepared-page @ 0< or if  exit  then
    prepared-msg @ message-layout prepared-page @ > 0= if  exit  then
    screen-size sh ! sw !  2 pen-scale  char-size nip 5 * 4 / lh !
    prepared-page @ message-lines 0 ?do
        subtitle-layer  prepared-page @ i message-line  sw @ 8 /  sh @ 7 * 8 / 8 +  i lh @ * +  $FFFFFFFF 2 ui-text
    loop ;
: draw-scene ( -- )  draw-movie  draw-subtitles ;
: scene-gone ( -- )   \ (the room left: its movie and scene with it)
    movie-status 1 = if  movie-close  then
    cutscene-active? if  cutscene-over  then
    0 ui-clear  subtitle-layer ui-clear ;

\ ==== S5a: the room's things - its placed objects, its doors' parts, lights, the look ====

\ ---- placed objects, by the room's string naming them (EventCmd_PlacedObject, the scripts' 0x50) ----
: object ( obj op arg -- )  >r >r  this-room @ room-string  r> r> placed-op ;
: object-show ( obj on -- )  0 swap object ;               \ 50 00: shown or hidden
: object-anim ( obj anim -- )  1 swap object ;              \ 50 01: its animation once
: object-anim-loop ( obj anim -- )  2 swap object ;         \ 50 02: looped
: object-anim-reset ( obj -- )  3 0 object ;                \ 50 03: back to its start

\ ---- the doors' models by part: bit a + 1 + b of every door's group mask (Doors_SetBits) - a
\ door's batches in group g are drawn while bit g is on (0 always) ----
: door-bits ( a set b -- )  rot 1+ +  swap door-group! ;

\ ---- the room's lights (0x90): op 0 light back to the room's own; 1 its intensity, 2 its
\ shadows' reach, times k ----
: light ( op light F: k -- )
    swap  dup 0= if  drop light-own fdrop exit  then  light-scale ;
\ 0x66: a lit doorway this frame - its quad keeps the characters' shadows off where the wall
\ already shades the light (Lights_AddDoorway: the shadow volumes' blockers). The shadows here
\ are shadow maps, which the walls shade themselves: nothing to add.
: lights-doorway ( F: x0 y0 z0 x1 y1 z1 x2 y2 z2 x3 y3 z3 -- )  12 0 do  fdrop  loop ;

\ ---- the look's effects (RoomEffects slots $1C..$1E: the depth range, the fog, the screen blend) ----
: depth-range ( F: a b c d -- )   \ 0x65: slot $1C anew with the four values
    effect-bytes 12 + sf!  effect-bytes 8 + sf!  effect-bytes 4 + sf!  effect-bytes sf!
    $1C effect-bytes 16 look-set ;
: depth-range-off ( -- )  $1C 0 0 look-set ;              \ 0x64
: fog ( a b on F: near far -- )   \ 0x9C: slot $1D - colours a, b (their words as they are), near, far
    if  effect-bytes 4 + l!  effect-bytes l!  effect-bytes 12 + sf!  effect-bytes 8 + sf!
        $1D effect-bytes 16 look-set
    else  2drop fdrop fdrop  $1D 0 0 look-set  then ;
: screen-blend ( a b on -- )   \ 0x9B: slot $1E - colour a, mode b
    if  effect-bytes 4 + c!  effect-bytes l!  $1E effect-bytes 5 look-set
    else  2drop  $1E 0 0 look-set  then ;

\ ==== S5b: the room's effects (an actor each, in the room's 32 slots: effects.fs) ====
: fx-id ( slot -- addr )  cells fx-ids + ;
: fx-place ( slot -- addr )  3 * floats fx-at + ;
: effect-remove ( fx -- )   \ 0x80
    dup #effects u< 0= if  drop exit  then
    fx-id dup @ dup alive? if  kill  else  drop  then  -1 swap ! ;
: effects-off ( -- )  #effects 0 do  i effect-remove  loop ;
: effects-none ( -- )  #effects 0 do  -1 i fx-id !  loop ;
fvariable ex  fvariable ey  fvariable ez
: effect-in ( fx command kind beh -- ) ( F: x y z -- )   \ (room_effect_new: the slot's old one gone)
    ez f! ey f! ex f!
    3 pick #effects u< 0= if  2drop 2drop exit  then
    3 pick effect-remove
    ex f@ ey f@ ez f@ effect  over fx-id !
    fx-place >r  ex f@ r@ f!  ey f@ r@ float+ f!  ez f@ r> 2 floats + f! ;
: flicker-sprite ( fx F: x y z -- )  0 0 flickering effect-in ;            \ 0x7F
: effect-86 ( fx kind F: x y z -- )  0 swap flaming effect-in ;            \ 0x86
: flicker-sprite-var ( fx x y z -- )   \ 0xB1: the slot and position in variables (positions / 1000)
    >r >r >r  var @  r> var @ s>f 1000e f/  r> var @ s>f 1000e f/  r> var @ s>f 1000e f/
    flicker-sprite ;
: zone-at-effect ( z fx r h kind -- )   \ 0x7D: zone z around the effect's place
    3 pick #effects u< 0= if  2drop 2drop drop exit  then
    3 pick fx-id @ alive? 0= if  2drop 2drop drop exit  then
    >r >r >r  fx-place dup f@  dup float+ f@  2 floats + f@  r> r> r>  zone ;
: char-effect-moving ( who fx -- )   \ 0x87: 1 if the character is where it was last frame, else 2
    dup #effects u< 0= if  2drop exit  then
    swap who>cs dup char-here 0= if  2drop exit  then
    dup char-at swap char-was vec-dist fdup f* 0.5e f< if  1  else  2  then
    swap fx-id @ dup alive? if  send effect-command  else  2drop  then ;
\ D6: the renderer's second packet arena flipped (Renderer_Set304DE0): the PS2's memory - nothing here
: effects-arena-flip ( -- ) ;

\ ==== not written yet (generated by tools/story_stubs.py: keep below this line) ====
: adx? ( what -- flag )  drop  s" adx?" stub-flag ;
: avoid-prompt ( v -- )  drop  s" avoid-prompt" stub-step ;
: butterflies ( fx args b b b b b b -- )  drop  drop  drop  drop  drop  drop  drop  drop  s" butterflies" stub-step ;
: camera-mode? ( v -- flag )  drop  s" camera-mode?" stub-flag ;
: camera-setup-changed? ( -- flag )  s" camera-setup-changed?" stub-flag ;
: camera-shake ( F: v -- )  fdrop  s" camera-shake" stub-step ;
: camera-value ( which F: v -- )  drop  fdrop  s" camera-value" stub-step ;
: char-C4? ( who v -- flag )  drop  drop  s" char-C4?" stub-flag ;
: char-activate ( id -- )  drop  s" char-activate" stub-step ;
: char-dead? ( who -- flag )  drop  s" char-dead?" stub-flag ;
: char-done ( id -- )  drop  s" char-done" stub-step ;
: char-file-load ( id file -- )  drop  drop  s" char-file-load" stub-step ;
: char-file-use ( id -- )  drop  s" char-file-use" stub-step ;
: char-find-tri ( who -- )  drop  s" char-find-tri" stub-step ;
: char-full-health ( who -- )  drop  s" char-full-health" stub-step ;
: char-full-health? ( who -- flag )  drop  s" char-full-health?" stub-flag ;
: char-group-bit4? ( id group -- flag )  drop  drop  s" char-group-bit4?" stub-flag ;
: char-hand-over ( from to -- )  drop  drop  s" char-hand-over" stub-step ;
: char-heading-for? ( who exit -- flag )  drop  drop  s" char-heading-for?" stub-flag ;
: char-heal ( id n -- )  drop  drop  s" char-heal" stub-step ;
: char-in ( slot -- )  drop  s" char-in" stub-step ;
: char-in-nav-group? ( who group -- flag )  drop  drop  s" char-in-nav-group?" stub-flag ;
: char-layer ( who layer -- )  drop  drop  s" char-layer" stub-step ;
: char-load ( id slot exit -- )  drop  drop  drop  s" char-load" stub-step ;
: char-load-2 ( id slot -- )  drop  drop  s" char-load-2" stub-step ;
: char-loaded? ( slot id -- flag )  drop  drop  s" char-loaded?" stub-flag ;
: char-model-op ( op id v -- )  drop  drop  drop  s" char-model-op" stub-step ;
: char-no-shadow ( who on -- )  drop  drop  s" char-no-shadow" stub-step ;
: char-not-at-door? ( who door -- flag )  drop  drop  s" char-not-at-door?" stub-flag ;
: char-on-nav-flags? ( who flags -- flag )  drop  drop  s" char-on-nav-flags?" stub-flag ;
: char-remove ( slot how -- )  drop  drop  s" char-remove" stub-step ;
: char-set-C4 ( who v -- )  drop  drop  s" char-set-C4" stub-step ;
: char-silent ( who on -- )  drop  drop  s" char-silent" stub-step ;
: char-tint ( who rgba on -- )  drop  drop  drop  s" char-tint" stub-step ;
: char-touching-facing? ( a b m0 m1 within -- flag )  drop  drop  drop  drop  drop  s" char-touching-facing?" stub-flag ;
: char-tri-free? ( who -- flag )  drop  s" char-tri-free?" stub-flag ;
: char-unload ( slot -- )  drop  s" char-unload" stub-step ;
: char-unseen? ( id -- flag )  drop  s" char-unseen?" stub-flag ;
: char-wait-motion ( who bits -- )  drop  drop  wait-frame  s" char-wait-motion" stub-step ;
: chars-within? ( a b d -- flag )  drop  drop  drop  s" chars-within?" stub-flag ;
: creature-action? ( v -- flag )  drop  s" creature-action?" stub-flag ;
: creature-count ( a b -- )  drop  drop  s" creature-count" stub-step ;
: creature-place ( room a tri flags kind which g F: f -- )  drop  drop  drop  drop  drop  drop  drop  fdrop  s" creature-place" stub-step ;
: creatures-clear ( which -- )  drop  s" creatures-clear" stub-step ;
: deal-things ( -- )  s" deal-things" stub-step ;
: door-close-off-lock ( door -- )  drop  s" door-close-off-lock" stub-step ;
: door-copy ( door from -- )  drop  drop  s" door-copy" stub-step ;
: door-flag-82 ( door on -- )  drop  drop  s" door-flag-82" stub-step ;
: door-lock-for ( id door state -- )  drop  drop  drop  s" door-lock-for" stub-step ;
: door-locked? ( door -- flag )  drop  s" door-locked?" stub-flag ;
: door-open-clear ( door -- )  drop  s" door-open-clear" stub-step ;
: door-open-set ( door -- )  drop  s" door-open-set" stub-step ;
: door-reopen-unlock ( door -- )  drop  s" door-reopen-unlock" stub-step ;
: doors-room-in ( -- )  s" doors-room-in" stub-step ;
: dust ( kind r g b own F: x y z -- )  drop  drop  drop  drop  drop  fdrop  fdrop  fdrop  s" dust" stub-step ;
: event-704-reached? ( v -- flag )  drop  s" event-704-reached?" stub-flag ;
: event-camera ( on F: a b c d -- )  drop  fdrop  fdrop  fdrop  fdrop  s" event-camera" stub-step ;
: exits-rebuild ( -- )  s" exits-rebuild" stub-step ;
: fade-past-40? ( -- flag )  s" fade-past-40?" stub-flag ;
: fading? ( -- flag )  s" fading?" stub-flag ;
: fiona-action? ( v -- flag )  drop  s" fiona-action?" stub-flag ;
: fiona-calm ( n -- )  drop  s" fiona-calm" stub-step ;
: fiona-calm-reset ( -- )  s" fiona-calm-reset" stub-step ;
: fiona-caught? ( -- flag )  s" fiona-caught?" stub-flag ;
: fiona-costume ( costume -- )  drop  s" fiona-costume" stub-step ;
: fiona-fear ( F: v -- )  fdrop  s" fiona-fear" stub-step ;
: fiona-free? ( -- flag )  s" fiona-free?" stub-flag ;
: fiona-hewie-react ( -- )  s" fiona-hewie-react" stub-step ;
: fiona-recover ( -- )  s" fiona-recover" stub-step ;
: fiona-recovery-lower ( n -- )  drop  s" fiona-recovery-lower" stub-step ;
: fiona-started? ( v -- flag )  drop  s" fiona-started?" stub-flag ;
: fiona-target ( id frames -- )  drop  drop  s" fiona-target" stub-step ;
: fiona-thrown ( id recover -- )  drop  drop  s" fiona-thrown" stub-step ;
: game-over-flag ( v -- )  drop  s" game-over-flag" stub-step ;
: hewie-action ( a b -- )  drop  drop  s" hewie-action" stub-step ;
: hewie-action? ( v -- flag )  drop  s" hewie-action?" stub-flag ;
: hewie-anim ( a anim -- )  drop  drop  s" hewie-anim" stub-step ;
: hewie-anim-root ( anim blend -- )  drop  drop  s" hewie-anim-root" stub-step ;
: hewie-anim-set ( anim -- )  drop  s" hewie-anim-set" stub-step ;
: hewie-bark ( -- )  s" hewie-bark" stub-step ;
: hewie-can-command? ( -- flag )  s" hewie-can-command?" stub-flag ;
: hewie-go-to ( tri b F: x z y -- )  drop  drop  fdrop  fdrop  fdrop  s" hewie-go-to" stub-step ;
: hewie-go-to-zone ( zone run -- )  drop  drop  s" hewie-go-to-zone" stub-step ;
: hewie-look-char ( id F: dy -- )  drop  fdrop  s" hewie-look-char" stub-step ;
: hewie-look-zone ( zone F: dy -- )  drop  fdrop  s" hewie-look-zone" stub-step ;
: hewie-mode ( mode -- )  drop  s" hewie-mode" stub-step ;
: hewie-model ( kind -- )  drop  s" hewie-model" stub-step ;
: hewie-near-command? ( -- flag )  s" hewie-near-command?" stub-flag ;
: hewie-reachable? ( -- flag )  s" hewie-reachable?" stub-flag ;
: hewie-side ( side -- )  drop  s" hewie-side" stub-step ;
: hewie-side? ( side -- flag )  drop  s" hewie-side?" stub-flag ;
: hewie-stay-300 ( -- )  s" hewie-stay-300" stub-step ;
: hewie-stays? ( -- flag )  s" hewie-stays?" stub-flag ;
: hewie-to-room ( room how at -- )  drop  drop  drop  s" hewie-to-room" stub-step ;
: hewie-trust ( n -- )  drop  s" hewie-trust" stub-step ;
: hewie-trust-level? ( v -- flag )  drop  s" hewie-trust-level?" stub-flag ;
: hewie-wait-5 ( on -- )  drop  wait-frame  s" hewie-wait-5" stub-step ;
: item-3F-under-10? ( -- flag )  s" item-3F-under-10?" stub-flag ;
: item-cooldown ( item less -- )  drop  drop  s" item-cooldown" stub-step ;
: item-tab ( op item -- )  drop  drop  s" item-tab" stub-step ;
: loader-done? ( -- flag )  s" loader-done?" stub-flag ;
: map-page ( page -- )  drop  s" map-page" stub-step ;
: message-closed? ( -- flag )  s" message-closed?" stub-flag ;
: noise-level ( v -- )  drop  s" noise-level" stub-step ;
: noise-slot-D? ( -- flag )  s" noise-slot-D?" stub-flag ;
: obstacle-keep-spot ( i -- )  drop  s" obstacle-keep-spot" stub-step ;
: obstacle-model-back ( i n -- )  drop  drop  s" obstacle-model-back" stub-step ;
: obstacle-on? ( i tri -- flag )  drop  drop  s" obstacle-on?" stub-flag ;
: obstacle-place ( i n kind a b -- )  drop  drop  drop  drop  drop  s" obstacle-place" stub-step ;
: obstacle-place-saved ( i n kind -- )  drop  drop  drop  s" obstacle-place-saved" stub-step ;
: obstacle-save ( i -- )  drop  s" obstacle-save" stub-step ;
: obstacle-save-at ( i a b -- )  drop  drop  drop  s" obstacle-save-at" stub-step ;
: obstacle-stop ( i -- )  drop  s" obstacle-stop" stub-step ;
: panic-98? ( -- flag )  s" panic-98?" stub-flag ;
: panic-grow ( v -- )  drop  s" panic-grow" stub-step ;
: panic-level ( level -- )  drop  s" panic-level" stub-step ;
: partner-load ( id -- )  drop  s" partner-load" stub-step ;
: point-on-camera? ( x y z -- flag )  drop  drop  drop  s" point-on-camera?" stub-flag ;
: reward-item ( -- )  s" reward-item" stub-step ;
: room-doors-state ( who room b -- )  drop  drop  drop  s" room-doors-state" stub-step ;
: room-frames-set ( n -- )  drop  s" room-frames-set" stub-step ;
: room-preload ( room -- )  drop  s" room-preload" stub-step ;
: rumble ( on strength frames -- )  drop  drop  drop  s" rumble" stub-step ;
: scene-effect-71000 ( var a F: v0 v1 v2 v3 v4 v5 v6 v7 -- )  drop  drop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  s" scene-effect-71000" stub-step ;
: scene-effect-8C ( zone n b F: x y z t -- )  drop  drop  drop  fdrop  fdrop  fdrop  fdrop  s" scene-effect-8C" stub-step ;
: scene-ending ( id -- )  drop  s" scene-ending" stub-step ;
: self-done? ( -- flag )  s" self-done?" stub-flag ;
: self-door-knock ( door how -- )  drop  drop  s" self-door-knock" stub-step ;
: self-doorway-fade ( on -- )  drop  s" self-doorway-fade" stub-step ;
: self-face-zone ( zone -- )  drop  s" self-face-zone" stub-step ;
: self-near-creature? ( -- flag )  s" self-near-creature?" stub-flag ;
: self-noclip ( on -- )  drop  s" self-noclip" stub-step ;
: self-scripted ( on -- )  drop  s" self-scripted" stub-step ;
: self-through-door ( door -- )  drop  s" self-through-door" stub-step ;
: self-through-exit ( exit -- )  drop  s" self-through-exit" stub-step ;
: self-touching? ( id -- flag )  drop  s" self-touching?" stub-flag ;
: sound-bank-loaded? ( bank -- flag )  drop  s" sound-bank-loaded?" stub-flag ;
: sound-set ( set -- )  drop  s" sound-set" stub-step ;
: sound-stop ( id bank -- )  drop  drop  s" sound-stop" stub-step ;
: sound-volume ( ch vol -- )  drop  drop  s" sound-volume" stub-step ;
: sound-volume-scale ( F: v -- )  fdrop  s" sound-volume-scale" stub-step ;
: specks ( a b c0 c1 c2 c3 F: x y z -- )  drop  drop  drop  drop  drop  drop  fdrop  fdrop  fdrop  s" specks" stub-step ;
: splash ( a b c d0 d1 d2 d3 F: x y z -- )  drop  drop  drop  drop  drop  drop  drop  fdrop  fdrop  fdrop  s" splash" stub-step ;
: sprites-additive ( mode -- )  drop  s" sprites-additive" stub-step ;
: stalker-active? ( -- flag )  s" stalker-active?" stub-flag ;
: stalker-alert? ( v -- flag )  drop  s" stalker-alert?" stub-flag ;
: stalker-free? ( -- flag )  s" stalker-free?" stub-flag ;
: stalker-gift ( -- )  s" stalker-gift" stub-step ;
: stalker-item-cooldown ( -- )  s" stalker-item-cooldown" stub-step ;
: stalker-kind-here? ( kind -- flag )  drop  s" stalker-kind-here?" stub-flag ;
: stalker-kind? ( kind -- flag )  drop  s" stalker-kind?" stub-flag ;
: stalker-knock-down ( id -- )  drop  s" stalker-knock-down" stub-step ;
: stalker-mode ( id mode -- )  drop  drop  s" stalker-mode" stub-step ;
: stalker-rage ( id on -- )  drop  drop  s" stalker-rage" stub-step ;
: stalker-search-delay ( id frames -- )  drop  drop  s" stalker-search-delay" stub-step ;
: stalker-stance-2? ( -- flag )  s" stalker-stance-2?" stub-flag ;
: stalker-to-room ( id room at how -- )  drop  drop  drop  drop  s" stalker-to-room" stub-step ;
: story-flag-set-var ( var -- )  drop  s" story-flag-set-var" stub-step ;
: story-flag-var? ( var -- flag )  drop  s" story-flag-var?" stub-flag ;
: subscreen-bit ( n -- )  drop  s" subscreen-bit" stub-step ;
: subscreen-bit? ( n -- flag )  drop  s" subscreen-bit?" stub-flag ;
: subscreen-open ( mode -- )  drop  s" subscreen-open" stub-step ;
: summon-take ( a -- )  drop  s" summon-take" stub-step ;
: things-clear ( -- )  s" things-clear" stub-step ;
: threat-add ( v -- )  drop  s" threat-add" stub-step ;
: threat-raise ( v -- )  drop  s" threat-raise" stub-step ;
