\ story/words.fs - the words the rooms' event scripts are written in (docs/subsystems/story.md):
\ one per command and condition of the original bytecode (the old new-src's events/words.fs has
\ the reference meanings; docs/event_opcodes.md the opcodes). The scripts run as their room's
\ actor: what they change of the room is its fields; what they ask of others goes as messages;
\ what they read of others are facts (bodies, the progress, the nav mesh) or what they were told.
\
\ Written so far: flags and variables, the script context and its waits, actions, characters
\ in areas and on triangles, exits, the camera, doors, the nav mesh's groups, sounds. The rest
\ is at the end (generated by tools/story_stubs.py): each says once that it isn't written yet
\ and does nothing (a condition: false).
IN: story.words
USING: engine game-state actors messages common doors room-names story.state ;

\ ---- the registered scripts (data: each room's phases and actions, the shared ones) ----
$110 constant #rooms
create room-scripts    #rooms 7 * cells allot     room-scripts #rooms 7 * cells 0 fill
create action-scripts  #rooms $80 * cells allot   action-scripts #rooms $80 * cells 0 fill
create shared-scripts  $80 cells allot            shared-scripts $80 cells 0 fill
\ phases: 0 entering, 1 / 2 each frame (before / after the commands), 3 each frame's end, 4
\ leaving, 5 left (the next room in), 6 a character entering
: room-script ( room phase -- addr )  swap 7 * + cells room-scripts + ;
: action-script ( room id -- addr )  swap $80 * + cells action-scripts + ;
: room-script! ( xt room phase -- )  room-script ! ;
: action-script! ( xt room id -- )  action-script ! ;
: builtin-script! ( xt id -- )  $80 - cells shared-scripts + ! ;
: script-for ( act -- xt | 0 )   \ (an action of this room, or a shared one from 0x80)
    dup $80 < if  this-room @ swap action-script @  else  $80 - $7F and cells shared-scripts + @  then ;

\ ---- not written yet: said once a word, then nothing ----
create missing 16 1024 * allot  variable #missing
: place ( addr len dest -- )  2dup c!  1+ swap move ;   \ (a counted string)
: cstring ( addr -- addr' len )  dup 1+ swap c@ ;
: missing? ( addr len -- flag )
    #missing @ 0 ?do  2dup missing i 32 * + cstring compare 0= if  2drop true unloop exit  then  loop  2drop false ;
: stub-step ( addr len -- )
    2dup missing? if  2drop exit  then
    #missing @ 512 < if  2dup 31 min missing #missing @ 32 * + place  1 #missing +!  then
    ." story: " type ."  - not written yet" cr ;
: stub-flag ( addr len -- flag )  stub-step false ;
: .missing ( -- )  #missing @ 0 ?do  missing i 32 * + cstring type space  loop  cr ;

\ ---- small things ----
: bit ( n addr -- mask addr' )  over 5 rshift 4 * +  swap 31 and 1 swap lshift swap ;
: bit? ( n addr -- flag )  bit l@ and 0<> ;
: bit-on ( n addr -- )  bit dup l@ rot or swap l! ;
: bit-off ( n addr -- )  bit dup l@ rot invert and swap l! ;
: deg ( F: a -- d )  180e f* pi f/ ;
: b0 ( -- ) ;   : b1 ( -- ) ;   : b2 ( -- ) ;   : b3 ( -- ) ;   : b4 ( -- ) ;   \ (the converter's byte markers)

\ ---- the script running now ----
: in-slot? ( -- flag )  ctx-slot @ 0< 0= ;
: self-char ( -- cs )  ctx-who @ ;
: self-frames ( -- addr )  in-slot? if  ctx-slot @ cells slot-frames +  else  phase-frames  then ;
: wait-frame ( -- )  in-slot? if  yield  then ;
: wait-until ( xt -- )   \ (a phase script can't wait: it looks once)
    in-slot? 0= if  drop exit  then  begin  dup execute 0= while  yield  repeat  drop ;

\ ---- the characters, by the scripts' slots (0 Fiona, 1 Hewie; the others with the stalkers) ----
: fiona-id ( -- id )  s" fiona" actor-named ;
: hewie-id ( -- id )  s" hewie" actor-named ;
: char-actor ( cs -- id | -1 )
    case
        0 of  fiona-id  endof
        1 of  hewie-id  endof
        >r -1 r>
    endcase  dup body? 0= if  drop -1  then ;
\ a script id to a slot: 0 Fiona, 1 Hewie, 0xFF the script's own (-1: nobody)
: char-slot ( id -- cs | -1 )
    dup $FF = if  drop self-char exit  then
    dup 0 2 within if  exit  then  drop -1 ;
: char-here ( cs -- flag )   \ in the game and in this room
    dup 0< if  drop false exit  then  char-actor dup 0< if  drop false exit  then  body-room this-room @ = ;
: in-room? ( cs -- flag )  char-here ;
: char-at ( cs -- v )  char-actor body-at ;
: char-was ( cs -- v )  12 * char-was + ;
: char-in-area ( cs area -- flag )  swap char-at vec@ area-in? ;
\ crossing an area since the last frame: 1 into it, -1 out of it, 0 neither
: char-cross ( cs area -- n )
    over cells char-seen + @ 0= if  2drop 0 exit  then
    >r dup char-was vec@ char-at vec@ r> area-cross ;
\ (each frame's end: where they are, for the next frame's crossings)
: remember-chars ( -- )
    #chars 0 do
        i char-here if  i char-was i char-at vec-copy  -1 i cells char-seen + !
        else  0 i cells char-seen + !  then
    loop ;
: who>cs ( who -- cs | -1 )   \ (a character argument: 0xFF self)
    dup $FF = if  drop self-char  else  char-slot  then ;

\ ---- 0x00 .. : flags, variables, bits, the counter, chance ----
: story-flag? ( n -- flag )  progress pr.story bit? ;
: story-flag-set ( n -- )  progress pr.story bit-on ;
: story-flag-clear ( n -- )  progress pr.story bit-off ;
: state-flag? ( n -- flag )  progress pr.state bit? ;
: state-flag-set ( n -- )  progress pr.state bit-on ;
: state-flag-clear ( n -- )  progress pr.state bit-off ;
: resident-flag? ( n -- flag )  progress pr.resident bit? ;
: resident-flag-set ( n -- )  progress pr.resident bit-on ;
: pvar? ( n v -- flag )  swap progress pr.vars + c@ = ;
: pvar-set ( n v -- )  swap progress pr.vars + c! ;
: pvar-inc ( n -- )  progress pr.vars + dup c@ 1+ swap c! ;
: pvars-equal? ( a b -- flag )  progress pr.vars + c@ swap progress pr.vars + c@ = ;
: var ( var -- addr )  #vars 1- and cells vars + ;
: var-set ( var v -- )  swap var ! ;
: var? ( var v -- flag )  swap var @ = ;
: var-inc ( var -- )  var 1 swap +! ;
: var-dec ( var -- )  var -1 swap +! ;
: ebit? ( n -- flag )  1 swap 31 and lshift ebits @ and 0<> ;
: ebit-set ( n -- )  1 swap 31 and lshift ebits @ or ebits ! ;
: ebit-clear ( n -- )  1 swap 31 and lshift invert ebits @ and ebits ! ;
: counter-set ( n -- )  counter ! ;
: counter-inc ( -- )  1 counter +! ;
: counter? ( n -- flag )  counter @ = ;
: wait-counter ( n -- )   \ (an action script waits for it)
    in-slot? 0= if  drop exit  then  begin  counter @ over <> while  yield  repeat  drop ;
: result? ( v -- flag )  result @ = ;
: chance? ( pct -- flag )
    dup 100 >= if  drop true exit  then  dup 1 < if  drop false exit  then  100 random > ;
: game-mode? ( mode -- flag )  the-danger @ = ;
: panic-stage? ( stage -- flag )   \ (0xFF: panicking, 4 or 5)
    dup $FF = if  drop the-panic @ 4 6 within  else  the-panic @ =  then ;
: panic-stage ( stage -- )  s" panic" actor-named send panic-stage! ;
: hewie-controlled? ( -- flag )  false ;   \ (the Hewie-controlled sections: H4)

\ ---- waiting (an action script's turn ends, each frame) ----
: yield ( -- )  wait-frame ;
: frames? ( n -- flag )  self-frames @ $FFFF and = ;
: self-frames-reset ( -- )  0 self-frames ! ;
: self-wait-frames ( n -- )
    in-slot? 0= if  drop exit  then  begin  self-frames @ over < while  yield  repeat  drop ;
: self-wait-16 ( -- )  16 self-wait-frames ;

\ ---- actions: the action scripts in their slots (Event_StartAction, Events_GiveScript) ----
: scene-id? ( id -- flag )  $FF and $F0 $FB within ;
: slot-of ( id -- k )  $FF and $F0 - 6 + ;     \ (a scene's slot: 6..16)
: slot-task ( k -- addr )  cells slot-tasks + ;
: free-slot ( k -- )
    dup slot-task @ ?dup if  forth:kill  then
    0 over slot-task !  -1 over cells slot-who + !  -1 over cells slot-ids + !  0 swap cells slot-frames + ! ;
: free-slots ( -- )  #slots 0 do  i free-slot  loop ;
: fill-slot ( xt who id k -- )
    >r  r@ cells slot-ids + !  r@ cells slot-who + !  0 r@ cells slot-frames + !
    r@ slot-task @ ?dup if  forth:kill  then
    spawn-held r> slot-task ! ;
: start-action ( id act -- )   \ a scene script: its own slot, no character
    script-for ?dup 0= if  drop exit  then  swap  -1 swap  dup slot-of  fill-slot ;
: give-script ( cs act -- )   \ a character's: slot cs + 1, as itself
    script-for ?dup 0= if  drop exit  then  swap  dup  over 1+  fill-slot ;
: char-action ( cs act -- )  -1 2 pick cells char-scripted + !  give-script ;
: start-for ( mode who act force -- )
    leaving @ if  2drop 2drop exit  then
    >r rot drop                                     ( who act )  ( R: force )
    over scene-id? if
        over slot-of slot-task @ 0=  r> or  if  start-action  else  2drop  then  exit
    then
    swap char-slot dup 0< if  2drop r> drop exit  then    ( act cs )
    swap  r> if  char-action exit  then
    over cells char-scripted + @ 0= if  char-action  else  2drop  then ;
: action ( mode who act -- )  false start-for ;
: action-force ( mode who act -- )  true start-for ;
: end-for ( who -- )
    dup scene-id? if  slot-of free-slot exit  then
    char-slot dup 0< if  drop exit  then
    0 over cells char-scripted + !  1+ free-slot ;
: action-end ( who -- )  end-for ;
\ the script's character idle again (with none: the script ends) - its turn ends
: self-idle-or-end ( -- )
    in-slot? 0= if  exit  then
    self-char dup 0< 0= if
        0 over cells char-scripted + !
        msg-owner @ = if  -1 msg-owner !  then
    else  drop  then
    ctx-slot @ free-slot ;   \ (the task is gone: nothing after this runs)
: goto ( xt -- )  in-slot? if  0 self-frames !  restart  else  execute  then ;
: goto-action ( id -- )  script-for ?dup if  goto  then ;
: call-action ( id -- )  script-for ?dup if  execute  then ;

\ ---- characters: where they are ----
: self-is? ( id -- flag )
    dup $FE = if  drop false exit  then   \ (the active stalker: H3)
    ctx-id @ = ;
: char-here? ( id -- flag )  char-slot char-here ;
: char-busy? ( who -- flag )   \ (a scene's slot running, or a character in a scripted action)
    dup scene-id? if  slot-of slot-task @ 0<> exit  then
    char-slot dup 0< if  drop false exit  then  cells char-scripted + @ 0<> ;
: char-in-area? ( who area -- flag )
    swap char-slot dup char-here 0= if  2drop false exit  then  swap char-in-area ;
: char-entered-area? ( who area -- flag )
    swap char-slot dup char-here 0= if  2drop false exit  then  swap char-cross 1 = ;
: char-left-area? ( who area -- flag )
    swap char-slot dup char-here 0= if  2drop false exit  then  swap char-cross -1 = ;
: char-on-tri? ( who tri -- flag )
    swap char-slot dup char-here 0= if  2drop false exit  then  char-actor body-tri = ;
: char-in-room? ( who room -- flag )
    swap char-slot dup 0< if  2drop false exit  then  char-actor dup 0< if  2drop false exit  then  body-room = ;
\ faces heading dir x 2 degrees (a signed byte), within `within` degrees
: char-heading? ( who dir within -- flag )
    rot char-slot dup char-here 0= if  drop 2drop false exit  then
    char-actor body-yaw angle-wrap deg  swap $FF and dup $80 and if  $100 -  then  2* s>f f-  fabs
    fdup 180e f> if  360e fswap f-  then  s>f f<= ;

\ ---- exits (cmd_exit, Progress_ExitOpen / ExitPassable) ----
: exit-door ( exit -- door | -1 )  this-room @ swap room-exit-door ;
: door-state ( door -- w )  4 * progress pr.doors + l@ ;
: exit-open ( exit -- flag )   \ a doorway, or a door not locked with its open bit
    exit-door dup 0< if  drop false exit  then
    dup door-flags 1 and if  drop true exit  then
    door-state dup 8 and if  drop false exit  then  2 and 0<> ;
: exit-passable ( exit -- flag )  exit-door dup 0< if  drop false exit  then  door-state $10 and 0= ;
\ take exit `exit` after this frame (bit 7: whatever its door; else if it is open to whoever is
\ controlled - Fiona, free of scripts)
: exit-check ( exit -- )
    dup $80 and if  $7F and dup exit-taken !  going !  -1 leaving !  exit  then
    dup exit-door dup 0< 0= if  door-locked? if  drop exit  then  else  drop  then
    dup exit-passable 0= if  drop exit  then
    0 cells char-scripted + @ if  drop exit  then
    dup exit-taken !  going ! ;
: exit-prepare ( exit -- )  drop ;   \ (the next room loaded ahead: rooms come in at once here)
: exit-usable? ( exit -- flag )   \ Fiona free (no script, moving on her own or 0xA), in the exit's
    0 cells char-scripted + @ if  drop false exit  then          \ area, its door open and not held
    fiona-mode @ dup 0<> swap $A <> and if  drop false exit  then
    0 char-here 0= if  drop false exit  then
    0 over exit-area char-in-area 0= if  drop false exit  then
    dup exit-open 0= if  drop false exit  then
    exit-door door-held? 0= ;
: exit-taken? ( exit -- flag )  exit-taken @ = ;
: exit-door-open? ( exit -- flag )  exit-open ;
\ a character put on the exit's outside spot, facing in (Rooms_ExitPointOut)
: char-to-exit ( who exit -- )
    swap who>cs char-actor dup 0< if  2drop exit  then  send to-exit ;

\ ---- the camera (Progress_CameraSetup / CameraFollow) ----
: camera-id ( -- id )  s" camera" actor-named ;
: char-cam! ( cs set path -- )   \ (a character not in this room gets none; Fiona always)
    rot dup 0< if  drop 2drop exit  then
    dup 0= over char-here or 0= if  nip nip -1 -1 rot  then
    char-actor dup 0< if  drop 2drop exit  then  -rot camera-id send camera-setup ;
: char-camera ( id set path -- )  rot char-slot -rot char-cam! ;
: camera-follow ( id -- )
    dup $FF = if  drop $FF camera-char !  -1 camera-id send follow exit  then
    char-slot dup 0< if  drop exit  then
    dup camera-char !  char-actor camera-id send follow ;
\ the characters in this room inside the area of exit `exit`
: area-camera ( exit set path -- )
    rot exit-area -rot
    #chars 0 do
        i char-here if  i 3 pick char-in-area if  i 2 pick 2 pick char-cam!  then  then
    loop  2drop drop ;
\ each character whose crossing of area `area` is `rel` (1 into it, -1 out of it, 0 neither)
: chars-area-camera ( area set path rel -- )
    #chars 0 do
        i char-here if
            i 4 pick char-cross over = if  i 3 pick 3 pick char-cam!  then
        then
    loop  2drop 2drop ;
: camera-restart ( -- )  camera-id send camera-restart ;

\ ---- doors ----
: door-bits ( a set b -- )  drop 2drop ;   \ (which parts of the room's door models are drawn: not drawn yet)
: doors-id ( -- id )  s" doors" actor-named ;
: door-lock ( door -- )  doors-id send lock ;
: door-unlock ( door -- )  doors-id send unlock ;
: door-not-closed-off? ( door -- flag )
    dup 0 door-count within 0= if  drop true exit  then  progress pr.closed-off bit? 0= ;

\ ---- the nav mesh's flag groups (the room's: its scripts open and close ways) ----
: nav-group ( set group bits -- )  rot 1 = -rot nav-group! ;
: nav-tri-flags ( set tri bits -- )  rot 1 = -rot nav-tri-flags! ;

\ ---- sounds and noises ----
variable snd-vol  variable snd-pitch
: sound ( id bank vol pitch F: x y z -- )   \ (cmd_sound: the bank's top bits say where - 2 plainly, 1 at the camera)
    snd-pitch !  snd-vol !  dup 6 rshift swap $3F and swap                 ( id bank where )
    dup 2 = if  drop fdrop fdrop fdrop bank-sound exit  then
    drop  snd-vol @ snd-pitch @ sound-at ;
: char-sound ( who id bank -- )   \ (Actor_PlaySound: at the character)
    rot who>cs dup char-here 0= if  drop 2drop exit  then
    char-at vec@  0 0 sound-at ;
: acoustics-id ( -- id )  s" acoustics" actor-named ;
: noise ( loud tri -- )  this-room @ swap -1 world-noise acoustics-id send noise ;
: room-sounds ( -- )  0 $1B0C00 sound-stop-voices  6 sound-load ;   \ (Progress_LoadRoomSounds)

\ ==== not written yet (generated by tools/story_stubs.py: keep below this line) ====
: adx? ( what -- flag )  drop  s" adx?" stub-flag ;
: answer? ( v -- flag )  drop  s" answer?" stub-flag ;
: avoid-prompt ( v -- )  drop  s" avoid-prompt" stub-step ;
: bgm ( track pause F: vol -- )  drop  drop  fdrop  s" bgm" stub-step ;
: butterflies ( fx args b b b b b b -- )  drop  drop  drop  drop  drop  drop  drop  drop  s" butterflies" stub-step ;
: camera-mode? ( v -- flag )  drop  s" camera-mode?" stub-flag ;
: camera-setup-changed? ( -- flag )  s" camera-setup-changed?" stub-flag ;
: camera-shake ( F: v -- )  fdrop  s" camera-shake" stub-step ;
: camera-value ( which F: v -- )  drop  fdrop  s" camera-value" stub-step ;
: char-C4? ( who v -- flag )  drop  drop  s" char-C4?" stub-flag ;
: char-action? ( who v -- flag )  drop  drop  s" char-action?" stub-flag ;
: char-activate ( id -- )  drop  s" char-activate" stub-step ;
: char-anim-hold ( id anim blend speed -- )  drop  drop  drop  drop  s" char-anim-hold" stub-step ;
: char-at-motion-event? ( id -- flag )  drop  s" char-at-motion-event?" stub-flag ;
: char-dead? ( who -- flag )  drop  s" char-dead?" stub-flag ;
: char-done ( id -- )  drop  s" char-done" stub-step ;
: char-effect-moving ( who fx -- )  drop  drop  s" char-effect-moving" stub-step ;
: char-faces-area? ( who area within -- flag )  drop  drop  drop  s" char-faces-area?" stub-flag ;
: char-faces-xz? ( who x z within -- flag )  drop  drop  drop  drop  s" char-faces-xz?" stub-flag ;
: char-file-load ( id file -- )  drop  drop  s" char-file-load" stub-step ;
: char-file-use ( id -- )  drop  s" char-file-use" stub-step ;
: char-find-tri ( who -- )  drop  s" char-find-tri" stub-step ;
: char-full-health ( who -- )  drop  s" char-full-health" stub-step ;
: char-full-health? ( who -- flag )  drop  s" char-full-health?" stub-flag ;
: char-group-bit4? ( id group -- flag )  drop  drop  s" char-group-bit4?" stub-flag ;
: char-hand-over ( from to -- )  drop  drop  s" char-hand-over" stub-step ;
: char-heading-for? ( who exit -- flag )  drop  drop  s" char-heading-for?" stub-flag ;
: char-heal ( id n -- )  drop  drop  s" char-heal" stub-step ;
: char-in ( slot -- )  drop  s" char-in" stub-step ;
: char-in-nav-group? ( who group -- flag )  drop  drop  s" char-in-nav-group?" stub-flag ;
: char-in-zone? ( who zone -- flag )  drop  drop  s" char-in-zone?" stub-flag ;
: char-layer ( who layer -- )  drop  drop  s" char-layer" stub-step ;
: char-load ( id slot exit -- )  drop  drop  drop  s" char-load" stub-step ;
: char-load-2 ( id slot -- )  drop  drop  s" char-load-2" stub-step ;
: char-loaded? ( slot id -- flag )  drop  drop  s" char-loaded?" stub-flag ;
: char-model-op ( op id v -- )  drop  drop  drop  s" char-model-op" stub-step ;
: char-no-shadow ( who on -- )  drop  drop  s" char-no-shadow" stub-step ;
: char-not-at-door? ( who door -- flag )  drop  drop  s" char-not-at-door?" stub-flag ;
: char-on-nav-flags? ( who flags -- flag )  drop  drop  s" char-on-nav-flags?" stub-flag ;
: char-remove ( slot how -- )  drop  drop  s" char-remove" stub-step ;
: char-set-C4 ( who v -- )  drop  drop  s" char-set-C4" stub-step ;
: char-silent ( who on -- )  drop  drop  s" char-silent" stub-step ;
: char-tint ( who rgba on -- )  drop  drop  drop  s" char-tint" stub-step ;
: char-to-tri ( who tri -- )  drop  drop  s" char-to-tri" stub-step ;
: char-to-tri-facing ( who tri face -- )  drop  drop  drop  s" char-to-tri-facing" stub-step ;
: char-to-xyz ( who face F: x y z -- )  drop  drop  fdrop  fdrop  fdrop  s" char-to-xyz" stub-step ;
: char-to-xz ( who tri face F: x z -- )  drop  drop  drop  fdrop  fdrop  s" char-to-xz" stub-step ;
: char-touching-facing? ( a b m0 m1 within -- flag )  drop  drop  drop  drop  drop  s" char-touching-facing?" stub-flag ;
: char-tri-free? ( who -- flag )  drop  s" char-tri-free?" stub-flag ;
: char-unload ( slot -- )  drop  s" char-unload" stub-step ;
: char-unseen? ( id -- flag )  drop  s" char-unseen?" stub-flag ;
: char-visible ( who on -- )  drop  drop  s" char-visible" stub-step ;
: char-wait-motion ( who bits -- )  drop  drop  wait-frame  s" char-wait-motion" stub-step ;
: char-zone-bits-before? ( who zone bits -- flag )  drop  drop  drop  s" char-zone-bits-before?" stub-flag ;
: char-zone-bits? ( who zone bits -- flag )  drop  drop  drop  s" char-zone-bits?" stub-flag ;
: chars-within? ( a b d -- flag )  drop  drop  drop  s" chars-within?" stub-flag ;
: control-action? ( v -- flag )  drop  s" control-action?" stub-flag ;
: creature-action? ( v -- flag )  drop  s" creature-action?" stub-flag ;
: creature-count ( a b -- )  drop  drop  s" creature-count" stub-step ;
: creature-place ( room a tri flags kind which g F: f -- )  drop  drop  drop  drop  drop  drop  drop  fdrop  s" creature-place" stub-step ;
: creatures-clear ( which -- )  drop  s" creatures-clear" stub-step ;
: cutscene-control ( op -- )  drop  s" cutscene-control" stub-step ;
: cutscene-cue-reached? ( cue -- flag )  drop  s" cutscene-cue-reached?" stub-flag ;
: cutscene-mode? ( mode -- flag )  drop  s" cutscene-mode?" stub-flag ;
: cutscene-near-end? ( -- flag )  s" cutscene-near-end?" stub-flag ;
: cutscene-passed? ( k at -- flag )  drop  drop  s" cutscene-passed?" stub-flag ;
: cutscene-shot? ( shot -- flag )  drop  s" cutscene-shot?" stub-flag ;
: cutscene-start ( name -- )  drop  s" cutscene-start" stub-step ;
: deal-things ( -- )  s" deal-things" stub-step ;
: depth-range ( F: a b c d -- )  fdrop  fdrop  fdrop  fdrop  s" depth-range" stub-step ;
: depth-range-off ( -- )  s" depth-range-off" stub-step ;
: door-close-off-lock ( door -- )  drop  s" door-close-off-lock" stub-step ;
: door-copy ( door from -- )  drop  drop  s" door-copy" stub-step ;
: door-flag-82 ( door on -- )  drop  drop  s" door-flag-82" stub-step ;
: door-lock-for ( id door state -- )  drop  drop  drop  s" door-lock-for" stub-step ;
: door-locked? ( door -- flag )  drop  s" door-locked?" stub-flag ;
: door-open-clear ( door -- )  drop  s" door-open-clear" stub-step ;
: door-open-set ( door -- )  drop  s" door-open-set" stub-step ;
: door-reopen-unlock ( door -- )  drop  s" door-reopen-unlock" stub-step ;
: doors-room-in ( -- )  s" doors-room-in" stub-step ;
: dust ( kind r g b own F: x y z -- )  drop  drop  drop  drop  drop  fdrop  fdrop  fdrop  s" dust" stub-step ;
: effect-86 ( fx kind F: x y z -- )  drop  drop  fdrop  fdrop  fdrop  s" effect-86" stub-step ;
: effect-remove ( fx -- )  drop  s" effect-remove" stub-step ;
: effect-string ( fx text.. n -- )  0 ?do  drop  loop  drop  s" effect-string" stub-step ;
: effects-arena-flip ( -- )  s" effects-arena-flip" stub-step ;
: event-704-reached? ( v -- flag )  drop  s" event-704-reached?" stub-flag ;
: event-camera ( on F: a b c d -- )  drop  fdrop  fdrop  fdrop  fdrop  s" event-camera" stub-step ;
: exits-rebuild ( -- )  s" exits-rebuild" stub-step ;
: fade ( frames kind -- )  drop  drop  s" fade" stub-step ;
: fade-finish ( -- )  s" fade-finish" stub-step ;
: fade-over ( -- )  s" fade-over" stub-step ;
: fade-past-40? ( -- flag )  s" fade-past-40?" stub-flag ;
: fading? ( -- flag )  s" fading?" stub-flag ;
: fiona-action? ( v -- flag )  drop  s" fiona-action?" stub-flag ;
: fiona-calm ( n -- )  drop  s" fiona-calm" stub-step ;
: fiona-calm-reset ( -- )  s" fiona-calm-reset" stub-step ;
: fiona-caught? ( -- flag )  s" fiona-caught?" stub-flag ;
: fiona-costume ( costume -- )  drop  s" fiona-costume" stub-step ;
: fiona-fear ( F: v -- )  fdrop  s" fiona-fear" stub-step ;
: fiona-free? ( -- flag )  s" fiona-free?" stub-flag ;
: fiona-hewie-react ( -- )  s" fiona-hewie-react" stub-step ;
: fiona-recover ( -- )  s" fiona-recover" stub-step ;
: fiona-recovery-lower ( n -- )  drop  s" fiona-recovery-lower" stub-step ;
: fiona-started? ( v -- flag )  drop  s" fiona-started?" stub-flag ;
: fiona-target ( id frames -- )  drop  drop  s" fiona-target" stub-step ;
: fiona-thrown ( id recover -- )  drop  drop  s" fiona-thrown" stub-step ;
: flicker-sprite ( fx F: x y z -- )  drop  fdrop  fdrop  fdrop  s" flicker-sprite" stub-step ;
: flicker-sprite-var ( fx x y z -- )  drop  drop  drop  drop  s" flicker-sprite-var" stub-step ;
: fog ( a b on F: near far -- )  drop  drop  drop  fdrop  fdrop  s" fog" stub-step ;
: game-over-flag ( v -- )  drop  s" game-over-flag" stub-step ;
: hewie-action ( a b -- )  drop  drop  s" hewie-action" stub-step ;
: hewie-action? ( v -- flag )  drop  s" hewie-action?" stub-flag ;
: hewie-anim ( a anim -- )  drop  drop  s" hewie-anim" stub-step ;
: hewie-anim-root ( anim blend -- )  drop  drop  s" hewie-anim-root" stub-step ;
: hewie-anim-set ( anim -- )  drop  s" hewie-anim-set" stub-step ;
: hewie-bark ( -- )  s" hewie-bark" stub-step ;
: hewie-can-command? ( -- flag )  s" hewie-can-command?" stub-flag ;
: hewie-go-to ( tri b F: x z y -- )  drop  drop  fdrop  fdrop  fdrop  s" hewie-go-to" stub-step ;
: hewie-go-to-zone ( zone run -- )  drop  drop  s" hewie-go-to-zone" stub-step ;
: hewie-look-char ( id F: dy -- )  drop  fdrop  s" hewie-look-char" stub-step ;
: hewie-look-zone ( zone F: dy -- )  drop  fdrop  s" hewie-look-zone" stub-step ;
: hewie-mode ( mode -- )  drop  s" hewie-mode" stub-step ;
: hewie-model ( kind -- )  drop  s" hewie-model" stub-step ;
: hewie-near-command? ( -- flag )  s" hewie-near-command?" stub-flag ;
: hewie-reachable? ( -- flag )  s" hewie-reachable?" stub-flag ;
: hewie-side ( side -- )  drop  s" hewie-side" stub-step ;
: hewie-side? ( side -- flag )  drop  s" hewie-side?" stub-flag ;
: hewie-stay-300 ( -- )  s" hewie-stay-300" stub-step ;
: hewie-stays? ( -- flag )  s" hewie-stays?" stub-flag ;
: hewie-to-room ( room how at -- )  drop  drop  drop  s" hewie-to-room" stub-step ;
: hewie-trust ( n -- )  drop  s" hewie-trust" stub-step ;
: hewie-trust-level? ( v -- flag )  drop  s" hewie-trust-level?" stub-flag ;
: hewie-wait-5 ( on -- )  drop  wait-frame  s" hewie-wait-5" stub-step ;
: item-3F-under-10? ( -- flag )  s" item-3F-under-10?" stub-flag ;
: item-add ( item -- )  drop  s" item-add" stub-step ;
: item-cooldown ( item less -- )  drop  drop  s" item-cooldown" stub-step ;
: item-count? ( item n -- flag )  drop  drop  s" item-count?" stub-flag ;
: item-give ( item -- )  drop  s" item-give" stub-step ;
: item-give-count ( item n -- )  drop  drop  s" item-give-count" stub-step ;
: item-tab ( op item -- )  drop  drop  s" item-tab" stub-step ;
: item-use ( item -- )  drop  s" item-use" stub-step ;
: light ( op light F: k -- )  drop  drop  fdrop  s" light" stub-step ;
: lights-doorway ( F: x0 y0 z0 x1 y1 z1 x2 y2 z2 x3 y3 z3 -- )  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  s" lights-doorway" stub-step ;
: loader-done? ( -- flag )  s" loader-done?" stub-flag ;
: map-page ( page -- )  drop  s" map-page" stub-step ;
: message ( msg -- )  drop  s" message" stub-step ;
: message-close ( msg -- )  drop  s" message-close" stub-step ;
: message-closed? ( -- flag )  s" message-closed?" stub-flag ;
: message-param-room ( n -- )  drop  s" message-param-room" stub-step ;
: message-prepare ( msg -- )  drop  s" message-prepare" stub-step ;
: movie-loop ( -- )  s" movie-loop" stub-step ;
: movie-param ( a b -- )  drop  drop  s" movie-param" stub-step ;
: movie-play ( name class -- )  drop  drop  s" movie-play" stub-step ;
: movie-playing? ( -- flag )  s" movie-playing?" stub-flag ;
: movie-volume ( F: v -- )  fdrop  s" movie-volume" stub-step ;
: music ( op a b -- )  drop  drop  drop  s" music" stub-step ;
: music-stage ( stage -- )  drop  s" music-stage" stub-step ;
: music-stage-end ( -- )  s" music-stage-end" stub-step ;
: noise-level ( v -- )  drop  s" noise-level" stub-step ;
: noise-slot-D? ( -- flag )  s" noise-slot-D?" stub-flag ;
: object-anim ( obj anim -- )  drop  drop  s" object-anim" stub-step ;
: object-anim-loop ( obj anim -- )  drop  drop  s" object-anim-loop" stub-step ;
: object-anim-reset ( obj -- )  drop  s" object-anim-reset" stub-step ;
: object-show ( obj on -- )  drop  drop  s" object-show" stub-step ;
: obstacle-keep-spot ( i -- )  drop  s" obstacle-keep-spot" stub-step ;
: obstacle-model-back ( i n -- )  drop  drop  s" obstacle-model-back" stub-step ;
: obstacle-on? ( i tri -- flag )  drop  drop  s" obstacle-on?" stub-flag ;
: obstacle-place ( i n kind a b -- )  drop  drop  drop  drop  drop  s" obstacle-place" stub-step ;
: obstacle-place-saved ( i n kind -- )  drop  drop  drop  s" obstacle-place-saved" stub-step ;
: obstacle-save ( i -- )  drop  s" obstacle-save" stub-step ;
: obstacle-save-at ( i a b -- )  drop  drop  drop  s" obstacle-save-at" stub-step ;
: obstacle-stop ( i -- )  drop  s" obstacle-stop" stub-step ;
: pad? ( button how -- flag )  drop  drop  s" pad?" stub-flag ;
: panic-98? ( -- flag )  s" panic-98?" stub-flag ;
: panic-grow ( v -- )  drop  s" panic-grow" stub-step ;
: panic-level ( level -- )  drop  s" panic-level" stub-step ;
: partner-load ( id -- )  drop  s" partner-load" stub-step ;
: point-on-camera? ( x y z -- flag )  drop  drop  drop  s" point-on-camera?" stub-flag ;
: reward-item ( -- )  s" reward-item" stub-step ;
: room-doors-state ( who room b -- )  drop  drop  drop  s" room-doors-state" stub-step ;
: room-frames-set ( n -- )  drop  s" room-frames-set" stub-step ;
: room-preload ( room -- )  drop  s" room-preload" stub-step ;
: rumble ( on strength frames -- )  drop  drop  drop  s" rumble" stub-step ;
: scene-change ( scene arg kind -- )  drop  drop  drop  s" scene-change" stub-step ;
: scene-effect-71000 ( var a F: v0 v1 v2 v3 v4 v5 v6 v7 -- )  drop  drop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  fdrop  s" scene-effect-71000" stub-step ;
: scene-effect-8C ( zone n b F: x y z t -- )  drop  drop  drop  fdrop  fdrop  fdrop  fdrop  s" scene-effect-8C" stub-step ;
: scene-ending ( id -- )  drop  s" scene-ending" stub-step ;
: scene-request? ( v -- flag )  drop  s" scene-request?" stub-flag ;
: screen-blend ( a b on -- )  drop  drop  drop  s" screen-blend" stub-step ;
: self-anim ( anim -- )  drop  s" self-anim" stub-step ;
: self-anim-9 ( anim b -- )  drop  drop  s" self-anim-9" stub-step ;
: self-anim-blend ( anim b -- )  drop  drop  s" self-anim-blend" stub-step ;
: self-at-motion-event? ( -- flag )  s" self-at-motion-event?" stub-flag ;
: self-done? ( -- flag )  s" self-done?" stub-flag ;
: self-door-knock ( door how -- )  drop  drop  s" self-door-knock" stub-step ;
: self-doorway-fade ( on -- )  drop  s" self-doorway-fade" stub-step ;
: self-face-zone ( zone -- )  drop  s" self-face-zone" stub-step ;
: self-idle ( -- )  s" self-idle" stub-step ;
: self-look-at ( id -- )  drop  s" self-look-at" stub-step ;
: self-look-at-point ( F: x y z -- )  fdrop  fdrop  fdrop  s" self-look-at-point" stub-step ;
: self-move-16 ( v -- )  drop  s" self-move-16" stub-step ;
: self-move-slot ( slot move -- )  drop  drop  s" self-move-slot" stub-step ;
: self-move-to ( tri face tri2 move F: x z -- )  drop  drop  drop  drop  fdrop  fdrop  s" self-move-to" stub-step ;
: self-move-tri ( tri tri2 move -- )  drop  drop  drop  s" self-move-tri" stub-step ;
: self-near-creature? ( -- flag )  s" self-near-creature?" stub-flag ;
: self-noclip ( on -- )  drop  s" self-noclip" stub-step ;
: self-scripted ( on -- )  drop  s" self-scripted" stub-step ;
: self-through-door ( door -- )  drop  s" self-through-door" stub-step ;
: self-through-exit ( exit -- )  drop  s" self-through-exit" stub-step ;
: self-touching? ( id -- flag )  drop  s" self-touching?" stub-flag ;
: self-turn-angle ( face -- )  drop  s" self-turn-angle" stub-step ;
: self-turn-to ( id -- )  drop  s" self-turn-to" stub-step ;
: self-turn-to-xz ( F: x z -- )  fdrop  fdrop  s" self-turn-to-xz" stub-step ;
: self-wait-anim ( -- )  wait-frame  s" self-wait-anim" stub-step ;
: self-wait-done ( -- )  wait-frame  s" self-wait-done" stub-step ;
: self-walk-anim ( anim tri tri2 face F: x z -- )  drop  drop  drop  drop  fdrop  fdrop  s" self-walk-anim" stub-step ;
: sound-bank-loaded? ( bank -- flag )  drop  s" sound-bank-loaded?" stub-flag ;
: sound-set ( set -- )  drop  s" sound-set" stub-step ;
: sound-stop ( id bank -- )  drop  drop  s" sound-stop" stub-step ;
: sound-volume ( ch vol -- )  drop  drop  s" sound-volume" stub-step ;
: sound-volume-scale ( F: v -- )  fdrop  s" sound-volume-scale" stub-step ;
: specks ( a b c0 c1 c2 c3 F: x y z -- )  drop  drop  drop  drop  drop  drop  fdrop  fdrop  fdrop  s" specks" stub-step ;
: splash ( a b c d0 d1 d2 d3 F: x y z -- )  drop  drop  drop  drop  drop  drop  drop  fdrop  fdrop  fdrop  s" splash" stub-step ;
: sprites-additive ( mode -- )  drop  s" sprites-additive" stub-step ;
: stalker-active? ( -- flag )  s" stalker-active?" stub-flag ;
: stalker-alert? ( v -- flag )  drop  s" stalker-alert?" stub-flag ;
: stalker-free? ( -- flag )  s" stalker-free?" stub-flag ;
: stalker-gift ( -- )  s" stalker-gift" stub-step ;
: stalker-item-cooldown ( -- )  s" stalker-item-cooldown" stub-step ;
: stalker-kind-here? ( kind -- flag )  drop  s" stalker-kind-here?" stub-flag ;
: stalker-kind? ( kind -- flag )  drop  s" stalker-kind?" stub-flag ;
: stalker-knock-down ( id -- )  drop  s" stalker-knock-down" stub-step ;
: stalker-mode ( id mode -- )  drop  drop  s" stalker-mode" stub-step ;
: stalker-rage ( id on -- )  drop  drop  s" stalker-rage" stub-step ;
: stalker-search-delay ( id frames -- )  drop  drop  s" stalker-search-delay" stub-step ;
: stalker-stance-2? ( -- flag )  s" stalker-stance-2?" stub-flag ;
: stalker-to-room ( id room at how -- )  drop  drop  drop  drop  s" stalker-to-room" stub-step ;
: story-flag-set-var ( var -- )  drop  s" story-flag-set-var" stub-step ;
: story-flag-var? ( var -- flag )  drop  s" story-flag-var?" stub-flag ;
: subscreen-bit ( n -- )  drop  s" subscreen-bit" stub-step ;
: subscreen-bit? ( n -- flag )  drop  s" subscreen-bit?" stub-flag ;
: subscreen-open ( mode -- )  drop  s" subscreen-open" stub-step ;
: summon-take ( a -- )  drop  s" summon-take" stub-step ;
: things-clear ( -- )  s" things-clear" stub-step ;
: threat-add ( v -- )  drop  s" threat-add" stub-step ;
: threat-raise ( v -- )  drop  s" threat-raise" stub-step ;
: wait-char-anim ( id -- )  drop  wait-frame  s" wait-char-anim" stub-step ;
: wait-fade ( -- )  wait-frame  s" wait-fade" stub-step ;
: wait-message ( -- )  wait-frame  s" wait-message" stub-step ;
: zone ( z r h kind F: x y z -- )  drop  drop  drop  drop  fdrop  fdrop  fdrop  s" zone" stub-step ;
: zone-at-effect ( z fx r h kind -- )  drop  drop  drop  drop  drop  s" zone-at-effect" stub-step ;
: zone-rect ( z id F: x0 z0 x1 z1 -- )  drop  drop  fdrop  fdrop  fdrop  fdrop  s" zone-rect" stub-step ;
