\ Generated by new-src/tools/roomstrings.py from the executable: the rooms' string tables
\ (RoomXX_ObjectNames: what event commands name by number - scenes, movies, room objects)
\ and the background music's tracks.
IN: events.strings
USING: game-state ;

: room-string ( i -- addr len )   \ string i of the room the scripts are in ("" none)
    event-state ev.room sl@ case
    $00 of  case
        0 of  s" DE0011" endof
        1 of  s" DE0011\DE0011.SFD" endof
        2 of  s" DE0003" endof
        3 of  s" DE0003\DE0003.SFD" endof
        4 of  s" DE0003\DE1003.SFD" endof
        >r s" " r>  endcase  endof
    $02 of  case
        0 of  s" DE000D" endof
        1 of  s" memo" endof
        2 of  s" lever" endof
        3 of  s" DE000D\DE000D.SFD" endof
        4 of  s" O_FIN_M\FIN_101.MTN" endof
        5 of  s" O_DB0\DB0_101.MTN" endof
        6 of  s" O_FIN_M\FIN_105.MTN" endof
        >r s" " r>  endcase  endof
    $03 of  case
        0 of  s" DE0008" endof
        1 of  s" DE0008\DE0008.SFD" endof
        2 of  s" O_DB0\DB0_102.MTN" endof
        >r s" " r>  endcase  endof
    $04 of  case
        0 of  s" DE001A" endof
        >r s" " r>  endcase  endof
    $06 of  case
        0 of  s" EV0013" endof
        1 of  s" EV0013\EV0013.SFD" endof
        2 of  s" O_DNL\DNL_104.MTN" endof
        >r s" " r>  endcase  endof
    $08 of  case
        0 of  s" DE0006" endof
        1 of  s" DE0006\DE0006.SFD" endof
        2 of  s" DE0015" endof
        3 of  s" DE0015\DE0015.SFD" endof
        4 of  s" bal_0" endof
        5 of  s" bal_1" endof
        6 of  s" bal_2" endof
        7 of  s" bal_3" endof
        8 of  s" bal_4" endof
        9 of  s" bal_5" endof
        10 of  s" kaihi" endof
        11 of  s" O_DB0\DB0_106.MTN" endof
        >r s" " r>  endcase  endof
    $09 of  case
        0 of  s" DE0014" endof
        1 of  s" DE0014\DE0014.SFD" endof
        2 of  s" tana" endof
        3 of  s" DE001B" endof
        4 of  s" DE001B\DE001B.SFD" endof
        5 of  s" DE0010" endof
        6 of  s" DE0010\DE0010.SFD" endof
        >r s" " r>  endcase  endof
    $0A of  case
        0 of  s" DE000B" endof
        1 of  s" DE000B\DE000B.SFD" endof
        >r s" " r>  endcase  endof
    $0B of  case
        0 of  s" O_FIN_M\FIN_104.MTN" endof
        >r s" " r>  endcase  endof
    $0C of  case
        0 of  s" DE000C" endof
        1 of  s" DE000C\DE000C.SFD" endof
        2 of  s" EV0012" endof
        3 of  s" EV0012\EV0012.SFD" endof
        4 of  s" EV0011" endof
        5 of  s" EV0011\EV0011.SFD" endof
        6 of  s" ev_door" endof
        7 of  s" DE001C" endof
        8 of  s" DE001C\DE001C.SFD" endof
        9 of  s" chandelier" endof
        10 of  s" chandelier2" endof
        11 of  s" DE003D" endof
        12 of  s" DE003D\DE003D.SFD" endof
        13 of  s" dai_B" endof
        14 of  s" dai_A" endof
        15 of  s" left_lever" endof
        16 of  s" right_lever" endof
        17 of  s" Rope_b" endof
        18 of  s" Rope_a" endof
        >r s" " r>  endcase  endof
    $0E of  case
        0 of  s" EV1033" endof
        1 of  s" EV1033\EV1033.SFD" endof
        >r s" " r>  endcase  endof
    $0F of  case
        0 of  s" EV0004" endof
        1 of  s" DE0004" endof
        >r s" " r>  endcase  endof
    $10 of  case
        0 of  s" O_DB0\DB0_103.MTN" endof
        >r s" " r>  endcase  endof
    $11 of  case
        0 of  s" EV0014" endof
        1 of  s" EV0014\EV0014.SFD" endof
        >r s" " r>  endcase  endof
    $12 of  case
        0 of  s" DE000F" endof
        1 of  s" DE000F\DE000F.SFD" endof
        2 of  s" DE0012" endof
        3 of  s" DE0012\DE0012.SFD" endof
        4 of  s" otama" endof
        5 of  s" O_FIN_M\FIN_101.MTN" endof
        6 of  s" O_DB0\DB0_101.MTN" endof
        >r s" " r>  endcase  endof
    $13 of  case
        0 of  s" DE0019" endof
        1 of  s" DE0019\DE0019.SFD" endof
        >r s" " r>  endcase  endof
    $14 of  case
        0 of  s" O_FIN_M\FIN_108.MTN" endof
        1 of  s" O_DB0\DB0_108.MTN" endof
        >r s" " r>  endcase  endof
    $15 of  case
        0 of  s" DE0005" endof
        1 of  s" DE0005\DE0005.SFD" endof
        2 of  s" lever" endof
        3 of  s" O_FIN_M\FIN_106.MTN" endof
        >r s" " r>  endcase  endof
    $17 of  case
        0 of  s" DE0009" endof
        1 of  s" DE0009\DE0009.SFD" endof
        >r s" " r>  endcase  endof
    $18 of  case
        0 of  s" EV0009" endof
        1 of  s" EV0009\EV0009.SFD" endof
        2 of  s" O_FIN_M\FIN_101.MTN" endof
        3 of  s" O_DB0\DB0_101.MTN" endof
        4 of  s" telephone_a" endof
        5 of  s" telephone_b" endof
        >r s" " r>  endcase  endof
    $19 of  case
        0 of  s" DE0018" endof
        1 of  s" DE0018\DE0018.SFD" endof
        2 of  s" DE1018" endof
        3 of  s" DE1018\DE1018.SFD" endof
        4 of  s" DE2018" endof
        5 of  s" DE2018\DE2018.SFD" endof
        >r s" " r>  endcase  endof
    $1A of  case
        0 of  s" O_FIN_M\FIN_101.MTN" endof
        1 of  s" O_DB0\DB0_101.MTN" endof
        >r s" " r>  endcase  endof
    $1B of  case
        0 of  s" fish1" endof
        1 of  s" fish2" endof
        2 of  s" fish3" endof
        3 of  s" hawk1" endof
        4 of  s" hawk2" endof
        >r s" " r>  endcase  endof
    $1C of  case
        0 of  s" DE0007" endof
        1 of  s" DE0007\DE0007.SFD" endof
        >r s" " r>  endcase  endof
    $1E of  case
        0 of  s" DE0017" endof
        1 of  s" DE0017\DE0017.SFD" endof
        >r s" " r>  endcase  endof
    $1F of  case
        0 of  s" doll" endof
        1 of  s" swing" endof
        >r s" " r>  endcase  endof
    $20 of  case
        0 of  s" DE000E" endof
        1 of  s" DE000E\DE000E.SFD" endof
        2 of  s" O_FIN_M\FIN_102.MTN" endof
        3 of  s" chandelie" endof
        4 of  s" g_chandelie" endof
        >r s" " r>  endcase  endof
    $21 of  case
        0 of  s" EV0002" endof
        1 of  s" EV0002\EV0002.SFD" endof
        2 of  s" EV0003" endof
        3 of  s" EV0003\EV0003.SFD" endof
        4 of  s" EV0007" endof
        5 of  s" EV0007\EV0007.SFD" endof
        6 of  s" EV0008" endof
        7 of  s" EV0008\EV0008.SFD" endof
        8 of  s" O_FIN_M\FIN_101.MTN" endof
        9 of  s" O_HEW\HEW_101.MTN" endof
        10 of  s" O_DB0\DB0_101.MTN" endof
        11 of  s" O_FIN_M\FIN_102.MTN" endof
        >r s" " r>  endcase  endof
    $22 of  case
        0 of  s" drawer" endof
        1 of  s" O_FIN_M\FIN_107.MTN" endof
        >r s" " r>  endcase  endof
    $23 of  case
        0 of  s" DE0000" endof
        1 of  s" DE1000" endof
        2 of  s" DE0000\DE0000.SFD" endof
        3 of  s" DE1000\DE1000.SFD" endof
        4 of  s" EV0010" endof
        5 of  s" EV0010\EV0010.SFD" endof
        6 of  s" cube" endof
        >r s" " r>  endcase  endof
    $24 of  case
        0 of  s" DE0001" endof
        1 of  s" DE0001\DE0001.SFD" endof
        2 of  s" DE0002" endof
        3 of  s" DE0002\DE0002.SFD" endof
        4 of  s" Golem_off_00" endof
        5 of  s" Golem_off_01" endof
        6 of  s" Golem_off_02" endof
        7 of  s" Golem_off_03" endof
        8 of  s" Golem_off_04" endof
        9 of  s" Golem_off_05" endof
        10 of  s" plate" endof
        >r s" " r>  endcase  endof
    $25 of  case
        0 of  s" DE000A" endof
        1 of  s" DE000A\DE000A.SFD" endof
        >r s" " r>  endcase  endof
    $26 of  case
        0 of  s" left_door" endof
        1 of  s" right_door" endof
        >r s" " r>  endcase  endof
    $28 of  case
        0 of  s" O_HEW\HEW_102.MTN" endof
        >r s" " r>  endcase  endof
    $29 of  case
        0 of  s" DE0016" endof
        1 of  s" DE0013" endof
        2 of  s" dool" endof
        3 of  s" DE0016\DE0016.SFD" endof
        4 of  s" DE0013\DE0013.SFD" endof
        >r s" " r>  endcase  endof
    $2A of  case
        0 of  s" EV0006" endof
        1 of  s" EV0006\EV0006.SFD" endof
        >r s" " r>  endcase  endof
    $2C of  case
        0 of  s" O_DNL\DNL_104.MTN" endof
        >r s" " r>  endcase  endof
    $2D of  case
        0 of  s" kibako" endof
        1 of  s" koushi" endof
        2 of  s" kakasi_a" endof
        3 of  s" kakasi_b" endof
        4 of  s" kaihi_a" endof
        5 of  s" kaihi_b" endof
        >r s" " r>  endcase  endof
    $2E of  case
        0 of  s" DE002B" endof
        1 of  s" DE002B\DE002B.SFD" endof
        2 of  s" O_DNL\DNL_109.MTN" endof
        >r s" " r>  endcase  endof
    $2F of  case
        0 of  s" O_HEW\HEW_102.MTN" endof
        >r s" " r>  endcase  endof
    $30 of  case
        0 of  s" O_HEW\HEW_102.MTN" endof
        1 of  s" O_DNL\DNL_104.MTN" endof
        >r s" " r>  endcase  endof
    $31 of  case
        0 of  s" EV0005" endof
        1 of  s" EV0005\EV0005.SFD" endof
        >r s" " r>  endcase  endof
    $33 of  case
        0 of  s" EV1034" endof
        1 of  s" EV1034\EV1034.SFD" endof
        >r s" " r>  endcase  endof
    $34 of  case
        0 of  s" EV0034" endof
        1 of  s" EV0034\EV0034.SFD" endof
        >r s" " r>  endcase  endof
    $35 of  case
        0 of  s" EV0033" endof
        1 of  s" EV0033\EV0033.SFD" endof
        2 of  s" EV0031" endof
        3 of  s" EV0031\EV0031.SFD" endof
        4 of  s" EV0032" endof
        5 of  s" EV0032\EV0032.SFD" endof
        >r s" " r>  endcase  endof
    $36 of  case
        0 of  s" EV1031" endof
        1 of  s" EV1031\EV1031.SFD" endof
        >r s" " r>  endcase  endof
    $37 of  case
        0 of  s" DE0035\FILM.SFD" endof
        1 of  s" fan" endof
        >r s" " r>  endcase  endof
    $40 of  case
        0 of  s" DE0028" endof
        1 of  s" DE0028\DE0028.SFD" endof
        2 of  s" DE0029" endof
        3 of  s" DE0029\DE0029.SFD" endof
        4 of  s" isi_ichi" endof
        5 of  s" ishi_iou" endof
        6 of  s" ishi_gin" endof
        7 of  s" ishi_shiro" endof
        8 of  s" ishi_aka" endof
        9 of  s" exitdoor" endof
        10 of  s" exitdoor1" endof
        11 of  s" kusari" endof
        >r s" " r>  endcase  endof
    $45 of  case
        0 of  s" Curtain" endof
        >r s" " r>  endcase  endof
    $46 of  case
        0 of  s" O_FIN_M\FIN_101.MTN" endof
        1 of  s" O_DNL\DNL_101.MTN" endof
        >r s" " r>  endcase  endof
    $47 of  case
        0 of  s" EV0019" endof
        1 of  s" EV0019\EV0019.SFD" endof
        >r s" " r>  endcase  endof
    $48 of  case
        0 of  s" DE0032" endof
        1 of  s" DE0032\DE0032.SFD" endof
        2 of  s" Kaihi_a" endof
        3 of  s" Kaihi_b" endof
        4 of  s" DE002E" endof
        5 of  s" DE002E\DE002E.SFD" endof
        6 of  s" DE102E" endof
        7 of  s" DE102E\DE102E.SFD" endof
        8 of  s" O_FIN_M\FIN_102.MTN" endof
        >r s" " r>  endcase  endof
    $49 of  case
        0 of  s" DE001D" endof
        1 of  s" DE001D\DE001D.SFD" endof
        2 of  s" mado0" endof
        3 of  s" mado1" endof
        4 of  s" mado2" endof
        5 of  s" mado3" endof
        6 of  s" O_FIN_M\FIN_108.MTN" endof
        >r s" " r>  endcase  endof
    $4A of  case
        0 of  s" DE0027" endof
        1 of  s" DE0027\DE0027.SFD" endof
        2 of  s" wood" endof
        >r s" " r>  endcase  endof
    $4B of  case
        0 of  s" O_FIN_M\FIN_109.MTN" endof
        1 of  s" O_DNL\DNL_109.MTN" endof
        >r s" " r>  endcase  endof
    $4C of  case
        0 of  s" fumi0" endof
        1 of  s" fumi1" endof
        2 of  s" fumi2" endof
        3 of  s" fumi3" endof
        4 of  s" DE0022" endof
        5 of  s" DE0022\DE0022.SFD" endof
        6 of  s" DE0023" endof
        7 of  s" DE0023\DE0023.SFD" endof
        8 of  s" O_FIN_M\FIN_10A.MTN" endof
        9 of  s" O_FIN_M\FIN_10C.MTN" endof
        10 of  s" lever2" endof
        11 of  s" lever2_1" endof
        12 of  s" lever1" endof
        13 of  s" lever1_1" endof
        14 of  s" futa" endof
        15 of  s" toge1" endof
        16 of  s" toge2" endof
        17 of  s" DE0021" endof
        18 of  s" DE0021\DE0021.SFD" endof
        >r s" " r>  endcase  endof
    $4E of  case
        0 of  s" O_FIN_M\FIN_109.MTN" endof
        1 of  s" O_DNL\DNL_109.MTN" endof
        >r s" " r>  endcase  endof
    $4F of  case
        0 of  s" atama_1" endof
        1 of  s" atama_2" endof
        2 of  s" atama_3" endof
        3 of  s" DE002F" endof
        4 of  s" DE002F\DE002F.SFD" endof
        5 of  s" DE0030" endof
        6 of  s" DE0030\DE0030.SFD" endof
        7 of  s" plate" endof
        >r s" " r>  endcase  endof
    $50 of  case
        0 of  s" l_door0" endof
        1 of  s" r_door0" endof
        2 of  s" O_FIN_M\FIN_100.MTN" endof
        3 of  s" O_HEW\HEW_100.MTN" endof
        4 of  s" O_DNL\DNL_100.MTN" endof
        5 of  s" O_DNL\DNL_102.MTN" endof
        6 of  s" DE0031" endof
        7 of  s" DE0031\DE0031.SFD" endof
        >r s" " r>  endcase  endof
    $51 of  case
        0 of  s" DE001F" endof
        1 of  s" DE001F\DE001F.SFD" endof
        2 of  s" DE101F" endof
        3 of  s" DE101F\DE101F.SFD" endof
        4 of  s" DE201F" endof
        5 of  s" DE201F\DE201F.SFD" endof
        6 of  s" DE0020" endof
        7 of  s" DE0020\DE0020.SFD" endof
        8 of  s" l_door0" endof
        9 of  s" r_door0" endof
        10 of  s" O_FIN_M\FIN_100.MTN" endof
        11 of  s" O_HEW\HEW_100.MTN" endof
        12 of  s" O_DNL\DNL_100.MTN" endof
        13 of  s" O_FIN_M\FIN_102.MTN" endof
        >r s" " r>  endcase  endof
    $52 of  case
        0 of  s" DE002C" endof
        1 of  s" DE002C\DE002C.SFD" endof
        2 of  s" mandor_0" endof
        3 of  s" mandor_1" endof
        4 of  s" mandor_2" endof
        5 of  s" mandor_3" endof
        6 of  s" mandor_4" endof
        7 of  s" mandor_5" endof
        8 of  s" mandor_6" endof
        9 of  s" mandor_7" endof
        >r s" " r>  endcase  endof
    $53 of  case
        0 of  s" DE0035\FILM.SFD" endof
        >r s" " r>  endcase  endof
    $54 of  case
        0 of  s" movebook_blue" endof
        1 of  s" hondana_a0" endof
        2 of  s" hondana_a1" endof
        3 of  s" hondana_a2" endof
        4 of  s" movebook_yellow" endof
        5 of  s" hondana_b0" endof
        6 of  s" hondana_b1" endof
        7 of  s" hondana_b2" endof
        8 of  s" movebook_red" endof
        9 of  s" hondana_c0" endof
        10 of  s" hondana_c1" endof
        11 of  s" hondana_c2" endof
        >r s" " r>  endcase  endof
    $55 of  case
        0 of  s" O_DNL\DNL_109.MTN" endof
        1 of  s" DE002D" endof
        2 of  s" DE002D\DE002D.SFD" endof
        >r s" " r>  endcase  endof
    $57 of  case
        0 of  s" DE0027" endof
        1 of  s" DE0027\DE0027.SFD" endof
        2 of  s" wood" endof
        >r s" " r>  endcase  endof
    $58 of  case
        0 of  s" O_FIN_M\FIN_101.MTN" endof
        1 of  s" O_DNL\DNL_101.MTN" endof
        >r s" " r>  endcase  endof
    $59 of  case
        0 of  s" DE0033" endof
        1 of  s" DE0033\DE0033.SFD" endof
        2 of  s" DE1033" endof
        3 of  s" DE1033\DE1033.SFD" endof
        4 of  s" DE0034" endof
        5 of  s" DE0034\DE0034.SFD" endof
        6 of  s" DE1034" endof
        7 of  s" DE1034\DE1034.SFD" endof
        8 of  s" bin0" endof
        9 of  s" bin1" endof
        10 of  s" O_FIN_M\FIN_108.MTN" endof
        11 of  s" EV0022" endof
        12 of  s" EV0022\EV0022.SFD" endof
        >r s" " r>  endcase  endof
    $5A of  case
        0 of  s" dial0" endof
        1 of  s" dial1" endof
        2 of  s" dial2" endof
        >r s" " r>  endcase  endof
    $5C of  case
        0 of  s" O_FIN_M\FIN_10B.MTN" endof
        >r s" " r>  endcase  endof
    $5D of  case
        0 of  s" DE001E" endof
        1 of  s" DE001E\DE001E.SFD" endof
        2 of  s" plate" endof
        3 of  s" wall" endof
        4 of  s" picture" endof
        5 of  s" light" endof
        >r s" " r>  endcase  endof
    $60 of  case
        0 of  s" EV0017" endof
        1 of  s" EV0017\EV0017.SFD" endof
        2 of  s" EV0018" endof
        3 of  s" EV0018\EV0018.SFD" endof
        4 of  s" a_splinter00" endof
        5 of  s" a_splinter01" endof
        6 of  s" a_splinter02" endof
        7 of  s" a_splinter03" endof
        8 of  s" a_splinter04" endof
        9 of  s" a_splinter05" endof
        10 of  s" a_splinter06" endof
        11 of  s" a_splinter07" endof
        12 of  s" a_splinter08" endof
        13 of  s" a_splinter09" endof
        14 of  s" a_splinter10" endof
        15 of  s" a_splinter11" endof
        16 of  s" a_splinter12" endof
        17 of  s" a_splinter13" endof
        18 of  s" a_splinter14" endof
        19 of  s" a_splinter15" endof
        20 of  s" a_splinter16" endof
        21 of  s" a_splinter17" endof
        22 of  s" a_splinter18" endof
        23 of  s" a_splinter19" endof
        24 of  s" a_splinter20" endof
        25 of  s" a_splinter21" endof
        26 of  s" a_splinter22" endof
        27 of  s" a_splinter23" endof
        >r s" " r>  endcase  endof
    $62 of  case
        0 of  s" step" endof
        1 of  s" book0" endof
        >r s" " r>  endcase  endof
    $63 of  case
        0 of  s" DE0024" endof
        1 of  s" DE0024\DE0024.SFD" endof
        2 of  s" DE0025" endof
        3 of  s" DE0025\DE0025.SFD" endof
        4 of  s" DE1025" endof
        5 of  s" DE1025\DE1025.SFD" endof
        6 of  s" DE2025" endof
        7 of  s" DE2025\DE2025.SFD" endof
        8 of  s" body" endof
        9 of  s" bowgun" endof
        10 of  s" dai" endof
        11 of  s" gen_0" endof
        12 of  s" gen_1" endof
        13 of  s" head" endof
        14 of  s" joint" endof
        15 of  s" left_0" endof
        16 of  s" left_1" endof
        17 of  s" left_2" endof
        18 of  s" pol_detach" endof
        19 of  s" pol_detach1" endof
        20 of  s" right_0" endof
        21 of  s" right_1" endof
        22 of  s" right_2" endof
        >r s" " r>  endcase  endof
    $66 of  case
        0 of  s" DE0026" endof
        1 of  s" DE0026\DE0026.SFD" endof
        >r s" " r>  endcase  endof
    $68 of  case
        0 of  s" O_DNL\DNL_104.MTN" endof
        >r s" " r>  endcase  endof
    $6A of  case
        0 of  s" O_FIN_M\FIN_109.MTN" endof
        1 of  s" O_DNL\DNL_109.MTN" endof
        >r s" " r>  endcase  endof
    $6B of  case
        0 of  s" O_FIN_M\FIN_101.MTN" endof
        1 of  s" O_DNL\DNL_101.MTN" endof
        >r s" " r>  endcase  endof
    $6C of  case
        0 of  s" O_FIN_M\FIN_101.MTN" endof
        1 of  s" O_DNL\DNL_101.MTN" endof
        >r s" " r>  endcase  endof
    $6D of  case
        0 of  s" l_door0" endof
        1 of  s" r_door0" endof
        2 of  s" O_FIN_M\FIN_100.MTN" endof
        3 of  s" O_HEW\HEW_100.MTN" endof
        4 of  s" O_DNL\DNL_100.MTN" endof
        >r s" " r>  endcase  endof
    $6E of  case
        0 of  s" l_door0" endof
        1 of  s" r_door0" endof
        2 of  s" O_FIN_M\FIN_100.MTN" endof
        3 of  s" O_HEW\HEW_100.MTN" endof
        4 of  s" O_DNL\DNL_100.MTN" endof
        >r s" " r>  endcase  endof
    $6F of  case
        0 of  s" O_FIN_M\FIN_101.MTN" endof
        1 of  s" O_DNL\DNL_101.MTN" endof
        >r s" " r>  endcase  endof
    $70 of  case
        0 of  s" O_FIN_M\FIN_101.MTN" endof
        1 of  s" O_DNL\DNL_101.MTN" endof
        2 of  s" O_DNL\DNL_104.MTN" endof
        >r s" " r>  endcase  endof
    $81 of  case
        0 of  s" O_FIN_M\FIN_108.MTN" endof
        1 of  s" DE0043" endof
        2 of  s" DE0043\DE0043.SFD" endof
        3 of  s" O_LRO\LRO_100.MTN" endof
        >r s" " r>  endcase  endof
    $83 of  case
        0 of  s" demo_door0" endof
        1 of  s" demo_door1" endof
        2 of  s" demo_door2" endof
        3 of  s" EV0027" endof
        4 of  s" EV0027\EV0027.SFD" endof
        >r s" " r>  endcase  endof
    $84 of  case
        0 of  s" demo_door0" endof
        1 of  s" demo_door1" endof
        2 of  s" demo_door2" endof
        3 of  s" EV0028" endof
        4 of  s" EV0028\EV0028.SFD" endof
        >r s" " r>  endcase  endof
    $85 of  case
        0 of  s" DE0042" endof
        1 of  s" DE0042\DE0042.SFD" endof
        >r s" " r>  endcase  endof
    $88 of  case
        0 of  s" O_FIN_M\FIN_108.MTN" endof
        >r s" " r>  endcase  endof
    $8A of  case
        0 of  s" DE0040" endof
        1 of  s" DE0040\DE0040.SFD" endof
        >r s" " r>  endcase  endof
    $8C of  case
        0 of  s" DE0044" endof
        1 of  s" DE0044\DE0044.SFD" endof
        2 of  s" DE0045" endof
        3 of  s" DE0045\DE0045.SFD" endof
        4 of  s" DE0046" endof
        5 of  s" DE0046\DE0046.SFD" endof
        >r s" " r>  endcase  endof
    $8D of  case
        0 of  s" EV0030" endof
        1 of  s" EV0030\EV0030.SFD" endof
        >r s" " r>  endcase  endof
    $8E of  case
        0 of  s" DE0041" endof
        1 of  s" DE0041\DE0041.SFD" endof
        >r s" " r>  endcase  endof
    $8F of  case
        0 of  s" DE0047" endof
        1 of  s" DE0047\DE0047.SFD" endof
        2 of  s" wall_l" endof
        3 of  s" wall_r" endof
        4 of  s" zou0" endof
        5 of  s" O_FIN_M\FIN_10D.MTN" endof
        6 of  s" DE003F" endof
        7 of  s" DE003F\DE003F.SFD" endof
        8 of  s" O_FIN_M\FIN_101.MTN" endof
        >r s" " r>  endcase  endof
    $92 of  case
        0 of  s" DE0049" endof
        1 of  s" DE0049\DE0049.SFD" endof
        2 of  s" DE0048" endof
        3 of  s" DE0048\DE0048.SFD" endof
        >r s" " r>  endcase  endof
    $9B of  case
        0 of  s" kaihi_a" endof
        1 of  s" kaihi_b" endof
        2 of  s" kaihi_c" endof
        >r s" " r>  endcase  endof
    $C1 of  case
        0 of  s" O_FIN_M\FIN_108.MTN" endof
        >r s" " r>  endcase  endof
    $C2 of  case
        0 of  s" move00" endof
        1 of  s" move01" endof
        2 of  s" lever2" endof
        3 of  s" lever2_1" endof
        4 of  s" O_FIN_M\FIN_10C.MTN" endof
        >r s" " r>  endcase  endof
    $C3 of  case
        0 of  s" move00" endof
        1 of  s" move01" endof
        2 of  s" lever2" endof
        3 of  s" lever2_1" endof
        >r s" " r>  endcase  endof
    $C5 of  case
        0 of  s" DE0039" endof
        1 of  s" DE0039\DE0039.SFD" endof
        2 of  s" earth" endof
        3 of  s" moon" endof
        4 of  s" mercury" endof
        5 of  s" venus" endof
        6 of  s" sun" endof
        7 of  s" mars" endof
        8 of  s" jupiter" endof
        9 of  s" saturn" endof
        >r s" " r>  endcase  endof
    $C7 of  case
        0 of  s" DE003C" endof
        1 of  s" DE003C\DE003C.SFD" endof
        2 of  s" EV0025" endof
        3 of  s" EV0025\EV0025.SFD" endof
        4 of  s" DE003B" endof
        5 of  s" DE003B\DE003B.SFD" endof
        6 of  s" EV0026" endof
        7 of  s" EV0026\EV0026.SFD" endof
        8 of  s" minihashi1" endof
        9 of  s" hashiyoko1" endof
        10 of  s" hashi1" endof
        >r s" " r>  endcase  endof
    $D6 of  case
        0 of  s" uekomi1" endof
        1 of  s" uekomi2" endof
        2 of  s" uekomi3" endof
        >r s" " r>  endcase  endof
    $E0 of  case
        0 of  s" fan" endof
        1 of  s" O_FIN_M\FIN_101.MTN" endof
        >r s" " r>  endcase  endof
    $E3 of  case
        0 of  s" O_FIN_M\FIN_101.MTN" endof
        >r s" " r>  endcase  endof
    $E4 of  case
        0 of  s" fumi_yuka" endof
        1 of  s" hook" endof
        2 of  s" a_Puppet" endof
        3 of  s" Puppetdoor" endof
        4 of  s" ev_door_a" endof
        5 of  s" ev_ddor_b" endof
        >r s" " r>  endcase  endof
    $E5 of  case
        0 of  s" O_FIN_M\FIN_108.MTN" endof
        1 of  s" Cartain" endof
        >r s" " r>  endcase  endof
    $E6 of  case
        0 of  s" kousi" endof
        1 of  s" lever" endof
        >r s" " r>  endcase  endof
    $E7 of  case
        0 of  s" O_FIN_M\FIN_101.MTN" endof
        >r s" " r>  endcase  endof
    >r s" " r>  endcase ;

\ the background music's tracks (pstr_ADX00_AD_01_ADX): the file and whether it loops
: bgm-track ( n -- addr len loop? )
    case
        $00 of  s" ADX00\AD_01.ADX" true  endof
        $01 of  s" ADX00\AD_01.ADX" true  endof
        $02 of  s" ADX00\AD_02.ADX" true  endof
        $03 of  s" ADX00\AD_03.ADX" true  endof
        $04 of  s" ADX00\AD_04.ADX" true  endof
        $05 of  s" ADX00\AD_05.ADX" true  endof
        $06 of  s" ADX00\AD_06.ADX" true  endof
        $07 of  s" ADX00\AD_07.ADX" true  endof
        $08 of  s" ADX00\AD_08.ADX" true  endof
        $09 of  s" ADX00\AD_09.ADX" true  endof
        $0A of  s" ADX00\AD_10.ADX" false  endof
        $0B of  s" ADX00\AD_11.ADX" false  endof
        $0C of  s" ADX00\AD_12.ADX" false  endof
        $0D of  s" ADX00\AD_13.ADX" false  endof
        $0E of  s" ADX00\AD_14.ADX" false  endof
        $0F of  s" ADX00\AD_15.ADX" false  endof
        $10 of  s" ADX00\AD_16.ADX" true  endof
        $11 of  s" ADX00\AD_17.ADX" true  endof
        $12 of  s" ADX00\AD_18.ADX" true  endof
        $13 of  s" ADX00\AD_19.ADX" true  endof
        $14 of  s" ADX00\AD_20.ADX" true  endof
        $15 of  s" ADX00\AD_21.ADX" true  endof
        $16 of  s" ADX00\AD_22.ADX" true  endof
        $17 of  s" ADX00\AD_23.ADX" true  endof
        $18 of  s" ADX00\AD_24.ADX" true  endof
        $19 of  s" ADX00\AD_25.ADX" true  endof
        $1A of  s" ADX00\AD_26.ADX" true  endof
        $1B of  s" ADX00\AD_27.ADX" true  endof
        $1C of  s" ADX00\AD_28.ADX" false  endof
        $1D of  s" ADX00\AD_29.ADX" false  endof
        $1E of  s" ADX01\AD_30.ADX" false  endof
        $1F of  s" ADX01\AD_31.ADX" false  endof
        $20 of  s" ADX01\AD_32.ADX" false  endof
        $21 of  s" ADX01\AD_33.ADX" false  endof
        $22 of  s" ADX01\AD_34.ADX" false  endof
        $23 of  s" ADX01\AD_35.ADX" false  endof
        $24 of  s" ADX01\AD_36.ADX" false  endof
        $25 of  s" ADX01\AD_37.ADX" false  endof
        $26 of  s" ADX01\AD_38.ADX" false  endof
        $27 of  s" ADX01\AD_39.ADX" false  endof
        $28 of  s" ADX01\AD_40.ADX" false  endof
        $29 of  s" ADX01\AD_41.ADX" false  endof
        $2A of  s" ADX01\AD_42.ADX" false  endof
        $2B of  s" ADX01\AD_43.ADX" false  endof
        $2C of  s" ADX01\AD_44.ADX" false  endof
        $2D of  s" ADX01\AD_45.ADX" false  endof
        $2E of  s" ADX01\AD_46.ADX" false  endof
        $2F of  s" ADX01\AD_47.ADX" false  endof
        $30 of  s" ADX01\AD_48.ADX" true  endof
        $31 of  s" ADX01\AD_49.ADX" true  endof
        $32 of  s" ADX01\AD_50.ADX" true  endof
        $33 of  s" ADX01\AD_51.ADX" true  endof
        $34 of  s" ADX01\AD_52.ADX" false  endof
        $35 of  s" ADX01\AD_53.ADX" true  endof
        $36 of  s" ADX01\AD_54.ADX" true  endof
        $37 of  s" ADX01\AD_55.ADX" false  endof
        $38 of  s" ADX01\AD_56.ADX" false  endof
        $39 of  s" ADX01\AD_57.ADX" true  endof
        $3A of  s" ADX01\AD_58.ADX" true  endof
        $3B of  s" ADX01\AD_59.ADX" true  endof
        $3C of  s" ADX02\AD_60.ADX" true  endof
        $3D of  s" ADX02\AD_61.ADX" true  endof
        $3E of  s" ADX02\AD_62.ADX" true  endof
        $3F of  s" ADX02\AD_63.ADX" true  endof
        $40 of  s" ADX02\AD_64.ADX" true  endof
        $41 of  s" ADX02\AD_65.ADX" true  endof
        $42 of  s" ADX02\AD_66.ADX" true  endof
        $43 of  s" ADX02\AD_67.ADX" true  endof
        $44 of  s" ADX02\AD_68.ADX" true  endof
        $45 of  s" ADX02\AD_69.ADX" true  endof
        $46 of  s" ADX02\AD_70.ADX" true  endof
        $47 of  s" ADX02\AD_71.ADX" true  endof
        $48 of  s" ADX02\AD_72.ADX" false  endof
        >r s" " false r>  endcase ;
