#!/usr/bin/env python3
"""Generate config/pointers_auto.txt: raw data words that are confidently pointers.

Rule (high confidence): an aligned data word whose value is exactly the start of
a function (a `glabel` in the code asm), and either
  - it follows 0xFFFFFFFF: an MW C++ pointer-to-member record {delta, -1, func, 0}, or
  - the value is not 4K-aligned (round values are usually packed shorts/sizes).
0x00100000 (crt0's header pseudo-label) is never a pointer.

Also: a 4-aligned 3-character `.asciz` whose 4 bytes, read as a word, point into
the data range is a pointer that the string guesser decoded as text (e.g.
0x00462040 -> "@ F"). Fill patterns ("ZZZ", "@@@") are excluded.

Needs a current build (reads build/SLUS_210.75.elf via tools/ptrcheck.py logic).
Afterwards re-run `configure.py --split`.
"""
import re
import struct
import subprocess
import sys
from pathlib import Path

BASEROM = "baserom/SLUS_210.75"


def func_starts() -> set[int]:
    out = set()
    for p in Path("asm").glob("*.s"):
        pending = False
        for line in p.open():
            if line.startswith("glabel"):
                pending = True
            elif pending:
                m = re.search(r"/\* [0-9A-F]+ ([0-9A-F]{8})", line)
                if m:
                    out.add(int(m.group(1), 16))
                    pending = False
    return out


def main() -> None:
    res = subprocess.run(
        [sys.executable, "tools/ptrcheck.py", "--list", "data"],
        capture_output=True, text=True, check=True,
    )
    funcs = func_starts()
    rom = Path(BASEROM).read_bytes()
    out = [
        "# GENERATED by tools/find_pointers.py -- raw data words equal to a function start.",
        "# Hand-curated entries go in config/pointers.txt.",
    ]
    for line in res.stdout.splitlines():
        m = re.match(r"\s+([0-9a-f]{8}) \.word 0x([0-9a-f]{8})", line)
        if not m:
            continue
        addr, value = int(m.group(1), 16), int(m.group(2), 16)
        if value in funcs and value != 0x00100000:
            (prev,) = struct.unpack_from("<I", rom, addr - 4 - 0x100000 + 0x80)
            if prev == 0xFFFFFFFF:
                out.append(f"0x{addr:08X}  # MW ptmf")
            elif value & 0xFFF:
                out.append(f"0x{addr:08X}")
    for asm in Path("asm/data").glob("*.s"):
        for line in asm.open():
            m = re.match(r'\s*/\* [0-9A-F]+ ([0-9A-F]{8}) \*/ \.asciz "(.*)"$', line)
            if not m:
                continue
            addr = int(m.group(1), 16)
            text = m.group(2).encode("latin1").decode("unicode_escape")
            if addr % 4 or len(text) != 3 or len(set(text)) == 1:
                continue
            (value,) = struct.unpack_from("<I", rom, addr - 0x100000 + 0x80)
            if 0x003AC780 <= value < 0x0047B200:
                out.append(f"0x{addr:08X}  # string-guessed pointer")
    p = Path("config/pointers_auto.txt")
    old = set(p.read_text().splitlines()[2:]) if p.exists() else set()
    # Words already patched are no longer raw, so keep previous entries that
    # still satisfy the rule (re-checked against the rom).
    for line in old:
        a = int(line.split()[0], 16)
        (v,) = struct.unpack_from("<I", rom, a - 0x100000 + 0x80)
        (prev,) = struct.unpack_from("<I", rom, a - 4 - 0x100000 + 0x80)
        if "string-guessed" in line or (
            v in funcs and v != 0x00100000 and (prev == 0xFFFFFFFF or v & 0xFFF)
        ):
            out.append(line)
    body = sorted(set(out[2:]))
    p.write_text("\n".join(out[:2] + body) + "\n")
    print(f"pointers_auto: {len(body)} entries")


if __name__ == "__main__":
    main()
