#!/usr/bin/env python3
"""Generate the inputs of the native (x86, 32-bit) build from the PS2 disassembly.

    tools/native_gen.py [-o build/native]

- data/*.S: asm/data/*.s rewritten for the host assembler. Same symbols, same layout (32-bit
  build), and every pointer is a relocation, so tables, vtables and PTMFs point at the native
  functions. Jump tables into MIPS code (`.word .Lxxxx`) become 0: C code has its own switches.
- stubs.c: a weak stub for every function of the PS2 executable. A function written in C (or a
  platform replacement) is a strong definition and wins at link time; reaching a stub reports
  "undecompiled func_XXXXXXXX" (native/platform/stub.c), which says what to decompile next.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

MACROS = """\
.macro dlabel label, visibility=global
    .\\visibility \\label
    .type \\label, @object
\\label:
.endm
.macro enddlabel label
    .size \\label, . - \\label
.endm
.macro nonmatching label, size=1
.endm
.macro jlabel label, visibility=global
\\label:
.endm
"""

DIRECTIVE = re.compile(r"^(\s*(?:/\*.*?\*/)?\s*)\.(word|align)\b\s*(.*)$")
SECTION = re.compile(r'^\.section\s+(\.\w+)')


def convert(src: Path) -> str:
    out = [MACROS]
    for line in src.read_text().splitlines():
        if line.startswith(".include"):
            continue
        m = SECTION.match(line)
        if m:
            # writable: the PS2 "rodata" split also holds .sdata/.sbss variables
            out.append('.section .bss,"aw",@nobits' if m.group(1) == ".bss" else '.section .data,"aw"')
            # same position modulo 128 as on the PS2, so offsets within the file keep their alignment
            start = int(re.search(r"/\* (?:[0-9A-F]+ )?([0-9A-F]{8})(?: [0-9A-F]+)? \*/", src.read_text()).group(1), 16)
            out.append(f".balign 128\n.space {start % 128}")
            continue
        m = DIRECTIVE.match(line)
        if m:
            pre, d, arg = m.groups()
            if d == "word":
                arg = "0" if arg.startswith(".L") else arg
                line = f"{pre}.long {arg}"
            else:   # MIPS .align n = 2^n bytes; on x86 gas .align counts bytes
                line = f"{pre}.p2align {arg}"
        out.append(line)
    return "\n".join(out) + "\n"


THUNK = re.compile(r"^\s+/\* \w+ \w+ \w+ \*/\s+(\S+)\s*(.*)$")


def thunks():
    """Functions that are only `j target` with `addiu $a0, $a0, imm` (or a nop) in the delay slot:
    C++ this-adjusting thunks and tail-call aliases. -> (name, target, adjust)"""
    out = []
    for fn in ("asm/game.s", "asm/sinit.s"):
        name, ins = None, []
        for line in (ROOT / fn).read_text().splitlines():
            m = re.match(r"^\s*glabel (\S+)", line)
            if m:
                name, ins = m.group(1), []
                continue
            if line.startswith("endlabel"):
                if name and len(ins) == 2 and ins[0][0] == "j" and not ins[0][1].startswith("."):
                    op, args = ins[1]
                    a = [x.strip() for x in args.split(",")]
                    if op == "nop":
                        out.append((name, ins[0][1], 0))
                    elif op == "addiu" and a[0] == "$a0" and a[1] == "$a0":
                        out.append((name, ins[0][1], int(a[2], 0)))
                name = None
                continue
            m = THUNK.match(line)
            if m and name:
                ins.append((m.group(1), m.group(2).strip()))
    return out


def functions():
    """(name, address) of every function and alternate entry in the PS2 executable."""
    lab = re.compile(r"^\s*(?:glabel|alabel)\s+(\S+)")
    addr = re.compile(r"^\s+/\* \w+ (\w+) \w+ \*/")
    for fn in ("asm/game.s", "asm/sinit.s"):
        name = None
        for line in (ROOT / fn).read_text().splitlines():
            m = lab.match(line)
            if m:
                name = m.group(1)
                continue
            if name:
                m = addr.match(line)
                if m:
                    yield name, int(m.group(1), 16)
                    name = None


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--out", type=Path, default=ROOT / "build/native")
    a = ap.parse_args()
    (a.out / "data").mkdir(parents=True, exist_ok=True)
    for src in sorted((ROOT / "asm/data").glob("*.s")):
        if src.name == "elf_header.s":
            continue
        dst = a.out / "data" / (src.stem + ".S")
        text = convert(src)
        if not dst.exists() or dst.read_text() != text:
            dst.write_text(text)

    # x86 versions of the thunks (cdecl: `this` is the first stack argument)
    th = thunks()
    asm = ["/* generated by tools/native_gen.py: PS2 this-adjusting thunks / tail-call aliases */", ".text"]
    for name, target, adj in th:
        asm += [f".weak {name}", f".type {name}, @function", f"{name}:"]
        if adj:
            asm.append(f"    addl ${adj}, 4(%esp)")
        asm.append(f"    jmp {target}")
    asm.append('.section .note.GNU-stack,"",@progbits')
    text = "\n".join(asm) + "\n"
    dst = a.out / "thunks.S"
    if not dst.exists() or dst.read_text() != text:
        dst.write_text(text)
    thunk_names = {t[0] for t in th}

    seen = set(thunk_names)
    lines = ["/* generated by tools/native_gen.py */",
             "extern void hg_undecompiled(const char *name, unsigned addr);", ""]
    for name, addr in functions():
        if name in seen or not re.fullmatch(r"[A-Za-z_]\w*", name):
            continue
        seen.add(name)
        lines.append(f'__attribute__((weak)) void {name}(void) {{ hg_undecompiled("{name}", 0x{addr:08X}u); }}')
    # symbols the data or the C refer to that the disassembly doesn't define (addresses inside
    # crt0 / code, kernel memory): weak placeholders, 256 zero bytes for data
    defined = set(seen)
    refs = set()
    for src in (ROOT / "asm/data").glob("*.s"):
        t = src.read_text()
        defined |= set(re.findall(r"^dlabel (\S+)", t, re.M))
        refs |= set(re.findall(r"\.word ([A-Za-z_]\w*)", t))
    for src in (ROOT / "src").rglob("*.c"):
        refs |= set(re.findall(r"\b((?:func|D)_[0-9A-F]{8})\b", src.read_text()))
    for name in sorted(refs - defined):
        if name.startswith("func_"):
            lines.append(f'__attribute__((weak)) void {name}(void) {{ hg_undecompiled("{name}", 0x{name[5:]}u); }}')
        else:
            lines.append(f"__attribute__((weak)) unsigned char {name}[256];")
    text = "\n".join(lines) + "\n"
    dst = a.out / "stubs.c"
    if not dst.exists() or dst.read_text() != text:
        dst.write_text(text)
    print(f"{len(seen) - len(thunk_names)} stubs, {len(thunk_names)} thunks")


if __name__ == "__main__":
    main()
